### ISSUE TITLE
Armory doesn't support compressed addresses?

### ISSUE THREAD

**Issue by sloanonlinux** [goatpig/BitcoinArmory#102]
So I am experimenting with Armory testnet, and when it is finished loading I find that it doesn't load my bitcoin core testnet wallet. I open bitcoin core and copy the private key, then I paste it into Armory, but it is invalid! Why? Because Armory doesn't support privkeys from anything later than bitcoin core 0.6.0

**Comment by achow101** [comment]
We know. Support for compressed keys is in the works. IIRC It will be a 
part of the new wallet structure with BIP32 support in 0.96.

**Comment by sloanonlinux** [comment]
Thank you, I look forward to the update!
