### ISSUE TITLE
Armory locks up my computer

### ISSUE THREAD

**Issue by sloanonlinux** [goatpig/BitcoinArmory#103]
On the second stage of loading: loading databases or something, right before scanning transactions, it locks my computer up for almost an hour, or hours if I have firefox or vlc open. What's going on??

**Comment by achow101** [comment]
Logfiles please.

Armory uses a lot of RAM, so it may be using too much memory so the computer slows down or hangs.

**Comment by sloanonlinux** [comment]
I have little ram, I use swapspace.
But why doesn't bitcoin core do the same thing? What is Armory doing differently?

**Comment by achow101** [comment]
Bitcoin Core uses quite a bit of RAM as well. Since Armory runs Core in the background, it is possible that running both simultaneously (as you have to) exceeds your RAM while running only Core does not.

**Comment by sloanonlinux** [comment]
Once it is finished loading, my computer becomes useful again. Should I have a permanent swapspace setting, instead of generating swapspace when I need it?

**Comment by achow101** [comment]
I don't think it matters. The slow down is because swap is very slow compared to RAM. Really what you need is more RAM.

**Comment by sloanonlinux** [comment]
I will get more RAM when I have actual bitcoin to experiment with instead of mere testnet coins. For now, I'll have to substitute RAM with patience and habit. Thank you for the quick response.

**Comment by goatpig** [comment]
You should try 0.95. It will let you:

1) Reduce ram usage with the --ram-usage CLI arg
2) Reduce cpu with the --thread-count CLI arg
3) Build the DB while Core is off, to focus resources on Armory for the one time initialization.
