### ISSUE TITLE
0.95: Coin Control broken for wallets with higher numbers of inputs and/or addresses

### ISSUE THREAD

**Issue by CarltonCode** [goatpig/BitcoinArmory#105]
Per-input granularity in 0.95's coin control is welcomed, but broken for wallets with either high (30+) numbers of inputs (paid to a single address) or high (30+) numbers of addresses used. Cannot distinguish which as I only encounter this with wallets that have a mix of both. 

Coin Control misbehaves given these conditions (tested other less "populated" wallets alongside and the bug partially persists a few attempts, but then corrects itself). The issue is that the selection is increasing less respectful of the actual user choice the further down the list of inputs that one tries to choose a given input from. At some point down a list of inputs, clicking "Accept" presents the user with Tx compose dialog box with green "All Addreses" text instead of the expected blue " \* Coin Control Subset \* " text.

**Comment by goatpig** [comment]
Are you saying the larger wallet will not exhibit this bug when manual output selection is only applied to the top entries?

Try to pin point the behavior with the following criterias:

1) Does it happen when you first blanket unselect all outputs then pick a few?
2) Do your wallets happen to have several outputs per single address? If so, does the bug occur when coin selection is only applied to single output addresses?

**Comment by CarltonCode** [comment]
Blanket unselect, then choosing from the topmost inputs functions correctly, until an input from an address with multiple inputs is chosen. That's definitely a refinement of either a or the problem.

**Comment by CarltonCode** [comment]
I provoked this error also:

(ERROR) Traceback (most recent call last):
  File "/home/user/BitcoinArmory/ui/WalletFrames.py", line 253, in doCoinCtrl
    aStr = hash160_to_addrStr(utxo.getRecipientHash160)
  File "/home/user/BitcoinArmory/armoryengine/ArmoryUtils.py", line 2149, in hash160_to_addrStr
    if not len(binStr) == 20:
TypeError: object of type 'instancemethod' has no len()

**Comment by goatpig** [comment]
do you have any non P2PKH outputs in that wallet?

**Comment by CarltonCode** [comment]
It's more than one wallet, and there are no P2SH addresses in any of them.

**Comment by goatpig** [comment]
Any raw multisig?

**Comment by CarltonCode** [comment]
No.

**Comment by goatpig** [comment]
Ok, should be enough to figure it out. Fix scheduled for 0.95.1

**Comment by CarltonCode** [comment]
thanks goatpig

**Comment by voidzero** [comment]
I'm not sure if the problem I encountered is related using the most recent dev branch: when I select one address via coin control and press Accept, the Spendable BTC amount isn't updated to the max spendable amount of that one address. If I select two addresses, it is updated. I haven't tried to actually send anything because I am not sure if it will send from just the one address.

**Comment by voidzero** [comment]
Here's a traceback:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/armory/ui/WalletFrames.py", line 253, in doCoinCtrl
    aStr = hash160_to_addrStr(utxo.getRecipientHash160)
  File "/usr/lib64/python2.7/site-packages/armory/armoryengine/ArmoryUtils.py", line 2149, in hash160_to_addrStr
    if not len(binStr) == 20:
TypeError: object of type 'instancemethod' has no len()
```

**Comment by voidzero** [comment]
It worked when I replaced line 253 of WalletFrames.py: by adding `()` it seems to work.

```
aStr = hash160_to_addrStr(utxo.getRecipientHash160())
```

Not sure if this is the right fix though.

**Comment by goatpig** [comment]
Good catch. This is an error indeed. I don't know if it covers the entire issue Carlton is experiencing, but it needs fixed regarldess. Submit a PR if you'd like.

**Comment by CarltonCode** [comment]
Well, I'm satisfied that this is fixed now. I'm happy to close this, so long as there are no objections.
