### ISSUE TITLE
Wallet Filters Don't Work

### ISSUE THREAD

**Issue by AndySchroder** [goatpig/BitcoinArmory#115]
I'm using armory 0.95.1 . The wallet filter drop down does not work in the lower left of the screen any more.

When you get this fixed, it would also be useful to add an option for "online" wallets too. Offline wallets require a lot more effort to access and it would be useful to quickly evaluate the amount of funds that are available for quick access and simultaneously assess how much risk you have by not having funds in cold storage.

**Comment by goatpig** [comment]
This was left out on purpose in 0.95. The feature will be reintroduced in the next release.

I'll keep the suggestion in mind.
