### ISSUE TITLE
Can't Sort Columns of "Available Wallets" Pane

### ISSUE THREAD

**Issue by AndySchroder** [goatpig/BitcoinArmory#116]
I'm using Armory version 0.95.1 . In this version and all previous versions that I've used, you can't sort columns of the "available wallets" pane. The current sort order is not even alphabetical. It appears to have a totally random sort order.

It would be very useful to give an option to sort by columns and also have a secondary sort for the "security" column because there are many wallets that will share the same security level (you may want the secondary sort order to be by the amount in cold storage or by the wallet name).

**Comment by achow101** [comment]
IIRC they are sorted alphabetically by the wallet ID.

**Comment by AndySchroder** [comment]
They are not sorted by wallet ID in version 0.95.1 .

**Comment by goatpig** [comment]
Nothing changed on that front in the code base, it shouldn't affect the rendering.
