### ISSUE TITLE
Difference between Address and Transaction Labels is confusing

### ISSUE THREAD

**Issue by AndySchroder** [goatpig/BitcoinArmory#119]
As a user, it's hard to tell what the difference is between labels for transactions and addresses is in the GUI. It seems like when initially receiving bitcoins, the label used will be added to the address, and then transactions to that address will use that label, but the transaction label can be overridden. Often times one will likely want to change the transaction and address labels simultaneously since they use only one receiving transaction per address. It's not always clear if changing the address label will then change the transaction label for any future transactions after the address label was changed.

Any ideas on how to make the distinction between these two types of labels more clear?

**Comment by achow101** [comment]
In the big transaction list on the main window, the labels are for transactions. When you open a wallet's properties, the comments are for each transaction. The transaction labels and address comments should not be linked as someone may be receiving Bitcoin at the same address and want to label their transactions separately.

The comments for an address copies over to the transactions because people usually use one address for each transaction, thus making that more convenient. However, as I stated above, some addresses may be reused so the transaction labels and address comments should be separate.

**Comment by AndySchroder** [comment]
Did you mean to say "When you open a wallet's properties, the comments are for each ADDRESS."?

**Comment by AndySchroder** [comment]
Basically, I think most applications will be one address, one receiving one transaction (or a few transactions all from the same person). It may be a convenience feature to have a check box when changing an address label to also change all transaction labels for the same address. Likewise, when changing a transaction label, it would be convenient to have a check box to also change the address's label, and all other transactions' labels with the same address. As it is right now, if you change your mind on the label, you have to change it in a lot of places to ensure there aren't old versions of that label somewhere that you forgot about. Adding these check boxes would also make the labels' associations clearer because everyone doesn't necessarily understand what you said above without doing some trial and error first.

**Comment by achow101** [comment]
> Did you mean to say "When you open a wallet's properties, the comments are for each ADDRESS."?

Yes. Fixed.

> It may be a convenience feature to have a check box when changing an address label to also change all transaction labels for the same address.

Ok, so what if the transaction is being sent from multiple addresses (as many are) or being received on multiple addresses (as many are with change addresses)? If you are receiving Bitcoin and then you want to send it, you don't want the two transactions to be labeled the same if you change the address comment. IMO transaction comments and address comments should not be connected except a transaction inheriting the address comment upon receipt.

**Comment by AndySchroder** [comment]
Right now, I don't think armory inherits any label from an address for the sending transaction label, does it? Also, I would think that one would not care much about change addresses (also part of the sending transaction) since they are more of an internal thing to the current wallet. With those things being said, I don't know that the sending from multiple addresses is an issue, since the sending transactions label should probably not be associated with the address associated with the TXOs for the inputs of that sending transaction.

Do you see a lot of times where there will be multiple receiving addresses in the local armory wallet for a single transaction? Right now since BIP70 isn't implemented, why would anyone be motivated to do that? Even if they do (or BIP70 is later implemented and provides multiple addresses), it would probably be for privacy reasons, but locally, you'd probably want those two addresses to share the same label. Anyway, right now, based on the current design of inheriting a label from the address for the transaction label, what do you do in that case now where there are more than one receiving address with different labels?

Maybe the checkbox I was talking about upon label change should only apply when changing the address label? And/or apply if their have only been receiving transactions so far. And/or only apply to receiving transactions, not sending transactions.

**Comment by goatpig** [comment]
You have to consider this from a development stand point:

1) Any amount of changes that requires modifying the Qt4 ledgers results in a lot of extra work. Something as benign as doubling a row is a nightmare, but this is what would be required to display both address and transaction comment simultaneously.

2) Any kind of scheme that replicates meta data programmatically across entries needs to be carefully designed to avoid endless reentrant loops.

3) The current wallet format is robust but basically locked down. I am not willing to modify it. Any amount of changes that requires additional meta data will have to wait for the new wallet format.

Bottom line, GUI changes require a lot more time and effort than the end result suggests. Please keep this in mind when submitting feature requests. 

Refine the change you want as much as possible until it is eloquent. Asking me to perform 3 different changes to comments logic is not a good use of my time, when there is probably a path to deliver the same amount of information in a single change. 

You should also involve the community in this discussion. Some people may actually prefer to keep the GUI the way it is regarding comments. I basically have little motivation to operate a change when you are the first person in 3 years to ask for it. I'd rather save resources and avoid changing features people have grown used to.

I'll be a lot more motivated to spend time on the GUI if the changes proposed are the result of a debate within the community. In that spirit, I would suggest you take this discussion to the Armory subforum on bitcointalk first, then submit the conclusion to the github issues page, where mostly developers lurk.

**Comment by AndySchroder** [comment]
Okay, thanks for the feedback, I did not know that this website was not the appropriate location to discuss change ideas. Obviously I am just providing suggestions at this point so you are of course at liberty to like/dislike and prioritize them as you see fit since you know what you are doing with the software and I don't. I will look into using the other discussion forum that you mention. Thanks.

**Comment by goatpig** [comment]
The github issue pages is generally meant for bug reporting.

Since github lacks a place for submitting feature requests, I let them live here, but the reality of your request is that it touches on the UX in a fashion that I believe need to be addressed by the user base. However, Armory users do not visit this page, they dwell here: 

https://bitcointalk.org/index.php?board=97.0

Feel free to create a thread there, link it to this page for context and bump it as you see fit.
