### ISSUE TITLE
Transaction lables don't update after changing 

### ISSUE THREAD

**Issue by AndySchroder** [goatpig/BitcoinArmory#120]
After updating to armory 0.95.1, labels in the transaction history don't change until I shut down armory and re-open it.

**Comment by achow101** [comment]
That is a known issue.

**Comment by AndySchroder** [comment]
Also, I had some transaction comments/labels that seemed to disappear after upgrading, but the address labels seem to still be there (I think). Are the transaction labels lost from the wallet file, or will I want to revert to a backup of the wallet after you fix the issue?

**Comment by achow101** [comment]
They should all be there. Whether they actually are, I don't actually know,

**Comment by goatpig** [comment]
No comments are lost from the file, the feature that links transactions in ledgers to comments in files has not been ported in 0.95 yet

**Comment by AndySchroder** [comment]
Okay, I guess let me know when you think you have this fixed and I will try and test it out again then.
