### ISSUE TITLE
Revamp transaction fee options

### ISSUE THREAD

**Issue by AndySchroder** [goatpig/BitcoinArmory#125]
Armory 0.95.1 currently allows setting transaction fees in BTC and satoshi/byte. It would be nice to have a more advanced interface similar to bitcoin core qt. In that interface there is a slider with a prediction for the number of blocks until there is a confirmation.

Also, the armory tooltip for transaction fees says "Most transactions do not require a fee". I think this phrase should be removed because it is no longer relevant.

**Comment by goatpig** [comment]
Will look into it as part of the RBF implementation.
