### ISSUE TITLE
Paper backups with random words instead of random characters

### ISSUE THREAD

**Issue by AndySchroder** [goatpig/BitcoinArmory#127]
It would be nice to have an option to also print a paper backup format that used words instead of characters to encode the private wallet seed information. I'm aware that words would require more total characters to be used, but it's possible one could memorize the random words easier than they could memorize the random characters.

**Comment by goatpig** [comment]
That's the BIP39 standard, and there are plans to introduce it with the new wallets. Legacy wallets are locked down, extra changes are going into that. Reserving BIP39 for the new format is also a good way to differentiate between the 2 format, that will coexist for a long time.

**Comment by AndySchroder** [comment]
Sounds good. Thanks for the information. Look forward to seeing when the new wallet format gets closer.
