### ISSUE TITLE
Consistent transaction history order for sending funds from one wallet to the other

### ISSUE THREAD

**Issue by AndySchroder** [goatpig/BitcoinArmory#129]
If I send bitcoin from one of my wallets to the other (for example, from an online wallet to an offline wallet) there are two transactions listed (which are actually the same transaction). One line shows the funds coming out of one wallet and the other shows funds going into the other. There does not seem to be any consistent order to these two lines. Sometimes the receiving transaction is listed before the sending one, sometimes the sending transaction is listed before the receiving one.

Intuitively it would make sense for the sending transaction to always be listed before the receiving transaction (even through they are really happening at the exact same time in the same transaction). Is there a way to make some logic to detect two identical transaction listings and prioritize/force their display order this way?

**Comment by goatpig** [comment]
This is based on the order of the txouts in the transactions, which are randomized on purpose to reduce privacy leaks. Basically the inconsistent ledger demonstrate the measures in place to improve privacy are doing their job.

As for the logic you are asking about, it would require changing the natural ordering (by block height|txid|txoutid) of the ledger entries. That's actually a large change as it requires introducing an indexing method for ledger entries that is not based on the output indexes.

**Comment by AndySchroder** [comment]
This is happening for me still even for transactions with a single input and a single output and no transaction fee paid or change address. What is there to randomize when there is one input and one output?

**Comment by goatpig** [comment]
The case you are mentioning is dependent on the hash160 ordering of the underlying addresses involved.
