### ISSUE TITLE
Armory crashes after resuming from standby mode

### ISSUE THREAD

**Issue by AndySchroder** [goatpig/BitcoinArmory#130]
I am running ubuntu 14.04 and armory 0.95.1 .

Upon resuming from standby mode, ArmoryQt.py crashes immediately. A few minutes after resuming from standby, ArmoryDB also crashes.

I have this same problem on two different computers.

**Comment by goatpig** [comment]
Standby as in sleep mode?

**Comment by AndySchroder** [comment]
I'm not sure of the difference, but my computer actually calls it "suspend" mode in some places, in addition to "sleep" mode.

I haven't tried "hibernate" mode, which does definitely do something different (it writes the RAM to the disk).

**Comment by goatpig** [comment]
If that standby mode does not respect the consistency of the mmap'd memory, LMDB can't survive it. 

If you want to run Armory over long periods of time under these conditions, previous versions offered no other solution but to disable all standby rules. 

Starting 0.95, the work around would be to run the DB separately on a server machine (that does not allow for any standby mechanics by nature) and run the client on the user facing machine.

**Comment by AndySchroder** [comment]
After further testing, I've actually had a few times where armory doesn't crash after resuming from standby mode. It seems as though the longer the computer is in standby, the more probable the crashing after standby resume, but I'm still trying to correlate it.

I have no problems with any other applications when resuming from standby mode (other than an ssh, vnc, voip, etc. session may disconnect (not crash), which is totally expected).
