### ISSUE TITLE
SDM JSON object error

### ISSUE THREAD

**Issue by WilliamWCYoung** [goatpig/BitcoinArmory#131]
On startup it says 'Please close Bitcoin-Core'. 

After doing so the screen looks like:
![armory](https://cloud.githubusercontent.com/assets/13030427/20160319/fd009906-a6dd-11e6-8c03-eacb625d2280.png)

With this being printed out in the terminal repeatedly:
```
(ERROR) SDM.py:791 - ValueError in bkgd req top blk
Traceback (most recent call last):
  File "/usr/lib/armory/SDM.py", line 765, in __backgroundRequestTopBlock
    numblks = self.proxy.getinfo()['blocks']
  File "/usr/lib/armory/bitcoinrpc_jsonrpc/authproxy.py", line 105, in __call__
    resp = json.loads(resp, parse_float=decimal.Decimal)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Please tell me how I can elaborate in this ticket to help you figure out what is going on if needed!

**Comment by achow101** [comment]
> On startup it says 'Please close Bitcoin-Core'.

 If you have Armory managing the bitcoind, you need to have Bitcoin Core closed first. You can disable the auto management and run Bitcoin Core by yourself if you want.

> With this being printed out in the terminal repeatedly:

That error has to do with connecting to Bitcoin Core's RPCs, it doesn't matter.

Log files please. It would probably be better to take this to the Armory forum though as this is an issue tracker, not a place for tech support.

**Comment by WilliamWCYoung** [comment]
Thanks for getting back so quickly, if that's the right place to take it then I will. 

From not knowing internals I felt reporting it as an issue was the correct thing to do.
