### ISSUE TITLE
Lockbox doesnt display list

### ISSUE THREAD

**Issue by dariusc93** [goatpig/BitcoinArmory#132]
I do not know why, but in 0.95[.1] that newly created multisig wallets/lockboxes arent displaying anything. Its there if you select it in the list but wont show the information regarding it.

**Comment by goatpig** [comment]
Let's see armorylog.txt

**Comment by dariusc93** [comment]
[armorylog.txt](https://github.com/goatpig/BitcoinArmory/files/592899/armorylog.txt)

**Comment by dariusc93** [comment]
Ive attached the armorylog.txt (had to redo it to make sure it still does it). 

[armorylog.txt](https://github.com/goatpig/BitcoinArmory/files/592923/armorylog.txt)
