### ISSUE TITLE
Create a DFDL description of the Armory Wallet format

### ISSUE THREAD

**Issue by VishalRao** [goatpig/BitcoinArmory#142]
https://en.wikipedia.org/wiki/Data_Format_Description_Language

This will help 3rd party developers create wallets, viewers, recovery tools that will be binary compatible with the Armory format and not have to rely on any code that's already written.

**Comment by goatpig** [comment]
I'm implementing BIP32 support in Armory and phasing out the old format, I don't think there is that much of a need for that kind of documentation anymore.
