### ISSUE TITLE
gpg: not a detached signature ?? 

### ISSUE THREAD

**Issue by Beast141** [goatpig/BitcoinArmory#146]
i downloaded sha256sum.asc file from https://www.bitcoinarmory.com/download/
After importing your key, i then tried verifying the .deb file with:
gpg --verify sha256sum.asc
Which shows your key and good signature but still doesnt validate the actual deb file.

then i did:
gpg --verify sha256sum.asc armory_0.95.1_amd64.deb

and it says: gpg: not a detached signature

Can you tell me if im doing something wrong ? or if maybe this file sha256sum.asc shouldnt include the hashes and have a separate .sig file to be able to use for verifying and separate .txt file with hashes ?

**Comment by Beast141** [comment]
When i remove the hashes from the .asc file and have only the signature, i try 
gpg --verify sha256sum.asc armory_0.95.1_amd64.deb
and it throws 
gpg: Signature made Wed 02 Nov 2016 21:05:06 SAST using RSA key ID 4922589A
gpg: BAD signature from "goatpig (Offline signing key for Armory releases) <moothecowlord@gmail.com>"

Shouldnt the signature work perfectly without the hashes in the way?

**Comment by goatpig** [comment]
We use the same release scheme as Bitcoin Core:

1) sha256sum all release packages
2) Save hash and package names in sha256sum.txt
3) Sign sha256sum.txt with offline key.

To verify a package you need to:

1) sha256sum the package. Check that its hash matches the corresponding hash in the sha256sum.txt
2) Check the signature on sha256sum.txt again my offline key.

**Comment by Beast141** [comment]
Ive figured out one way to accomplish verifying the actual file, instead of just verifying _only_ the signature thats coming from you.
What should be in the documentation is, users should run:
sha256sum -c sha256SUMS 2>&1 | grep OK

where sha256SUMS has only the hashes. Provided the actual .deb file or any of the files are in the same folder, it will then respond with OK.

But what puzzles me is the fact when i run:
gpg --verify armory_0.95.1_amd64.asc sha256SUMS

output:
gpg: Signature made Wed 02 Nov 2016 21:05:06 SAST using RSA key ID 4922589A
gpg: BAD signature from "goatpig (Offline signing key for Armory releases) <moothecowlord@gmail.com>"

Where armory_0.95.1_amd64.asc has only your signature in it.

OR 

gpg --verify armory_0.95.1_amd64.asc armory_0.95.1_amd64.deb

output:
gpg: Signature made Wed 02 Nov 2016 21:05:06 SAST using RSA key ID 4922589A
gpg: BAD signature from "goatpig (Offline signing key for Armory releases) <moothecowlord@gmail.com>"

Its not the first time im using the command: 
gpg --verify file.asc sha256SUMS
OR
gpg --verify file.asc file.deb

Usually it would return Good Signature. But not in this case.

Can you help explain why this throws BAD signature like this with these general verify commands?

And yes i have imported your public key like this:
gpg --recv-keys --keyserver keyserver.ubuntu.com 4922589A

**Comment by goatpig** [comment]
I do not understand what your issue is. 

Neither of these commands make any sense:

gpg --verify armory_0.95.1_amd64.asc sha256SUMS
gpg --verify armory_0.95.1_amd64.asc armory_0.95.1_amd64.deb

This is because the only file with an actual signatures is sha256sum.asc. If you insist on verifying the signature on files that do not carry one, you shouldn't be surprised by the failure.
