### ISSUE TITLE
Certificate used to sign package

### ISSUE THREAD

**Issue by manuelra** [goatpig/BitcoinArmory#159]
The page at http://www.bitcoinarmory.com/download/  provides:

1. a link to the file containing the hashes for the platform specific installers (version 0.95.1);
2. the id of the offline signing key (id 0x98832223), which belongs to

    _Alan C. Reiner (Offline Signing Key) <alan@bitcoinarmory.com>_

But the file containing the hashes is signed with a key within certificate 0x8C5211764922589A belonging to goatpig (Offline signing key for Armory releases) <moothecowlord@gmail.com>.

Also note that the video on http://www.bitcoinarmory.com/tutorials/armory-basics/verify-download/ points to Alan C. Reiner's certificate.

**Comment by goatpig** [comment]
bitcoinarmory.com belongs to ATI, I do not have control over its content. As you may have notice, this repo is mine, forked from Alan's (etotheipi).

All versions since 0.93.3 have been my work. I sign my work with my key.

**Comment by manuelra** [comment]
I see.  Interestingly bitcoinarmory.com points to your repo on their downloads page.

Thank you for the clarification.

**Comment by goatpig** [comment]
I'm aware of this. I'm guessing that while they don't maintain the code anymore, they feel it's better for everyone to redirect the community to the ongoing fork.

At any rate, the only thing that matters is the signatures, not who links/hosts it.

**Comment by achow101** [comment]
I think this can be closed. There is documentation for how to verify the binaries on the new website: https://btcarmory.com/docs/verify
