### ISSUE TITLE
Building databases never starts with Armory-managed bitcoind

### ISSUE THREAD

**Issue by mateon1** [goatpig/BitcoinArmory#164]
Armory version 0.95.1-beta-374672b751
Windows 10 x64

When Armory is running its own bitcoind, the ArmoryDB process is never started.
The bitcoind log shows repeated RPC login failures.

Upon closing Armory, starting own bitcoind and restarting armory, building databases starts immediately.

**Comment by achow101** [comment]
Should be fixed for 0.96
