### ISSUE TITLE
getTxByHash RuntimeError: unexpected return value

### ISSUE THREAD

**Issue by jameshilliard** [goatpig/BitcoinArmory#165]
I'm getting this error when trying to send a transaction, I'm using coin control but not sure if that makes a difference. Running Bitcoin Core 0.13.2.
```
2017-01-23 22:55 (ERROR) -- Traceback (most recent call last):
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/ui/TxFrames.py", line 829, in createTxAndBroadcast
    ustx = self.validateInputsGetUSTX()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/ui/TxFrames.py", line 810, in validateInputsGetUSTX
    utxoSelect, scriptValPairs, pubKeyMap)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/armoryengine/Transaction.py", line 2259, in createFromTxOutSelection
    return self.createFromPyTx(thePyTx, pubKeyMap, txMap, p2shMap)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/armoryengine/Transaction.py", line 2169, in createFromPyTx
    cppPrevTx = TheBDM.bdv().getTxByHash(txhash)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/CppBlockUtils.py", line 2505, in getTxByHash
    return _CppBlockUtils.BlockDataViewer_getTxByHash(self, txHash)
RuntimeError: unexpected return value
```

**Comment by goatpig** [comment]
You want to rebuild & rescan.

**Comment by jameshilliard** [comment]
I had tried that already but it didn't seem to help.

**Comment by goatpig** [comment]
Do you know your way around Python?

**Comment by jameshilliard** [comment]
Yeah

**Comment by goatpig** [comment]
print the txHash value here:

https://github.com/goatpig/BitcoinArmory/blob/master/armoryengine/Transaction.py#L2169

Make sure it isn't empty, and that the value is a valid tx hash

**Comment by jameshilliard** [comment]
It is not empty and is the txhash for a valid confirmed transaction(I looked it up on blockchain.info to check).
I printed it using `print binary_to_hex(txhash, BIGENDIAN)`

**Comment by jameshilliard** [comment]
After further testing I was able to determine it always fails if I have either(or both) of 2 particular outputs selected(2 txid's) in coincontrol.

**Comment by goatpig** [comment]
Right, the few outputs for which the txhash has not been resolved. Try a rescan balances. If that fails, you'll have to figure out why these hashes are not seen by this piece of code:

https://github.com/goatpig/BitcoinArmory/blob/master/cppForSwig/BlockchainScanner.cpp#L1512

**Comment by jameshilliard** [comment]
Any log messages I should add to that?

**Comment by goatpig** [comment]
Any you feel are relevant. The idea is that I unless I can reproduce locally, you'll have to narrow down the range of possible culprits.
