### ISSUE TITLE
tx broadcast time out

### ISSUE THREAD

**Issue by vvv9** [goatpig/BitcoinArmory#166]
[armorylog_20170125_1232.txt](https://github.com/goatpig/BitcoinArmory/files/730885/armorylog_20170125_1232.txt)

per the system's request, I've attached a log file as the error continues...

trying to send from offline wallet... signing goes fine, but cant broadcast without error:

tx broadcast time out

please advise
thanks

**Comment by goatpig** [comment]
You are better off posting that stuff here: https://bitcointalk.org/index.php?board=97.0

As for now, either turn off auto bitcoind and try to broadcast again, or grab the signed tx from the broadcast dialog and manually broadcast from your node.

**Comment by vvv9** [comment]
Thanks so much.

How do I manually broadcast?

On Jan 25, 2017 6:25 PM, "goatpig" <notifications@github.com> wrote:

You are better off posting that stuff here: https://bitcointalk.org/index.
php?board=97.0

As for now, either turn off auto bitcoind and try to broadcast again, or
grab the signed tx from the broadcast dialog and manually broadcast from
your node.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/goatpig/BitcoinArmory/issues/166#issuecomment-275293198>,
or mute the thread
