### ISSUE TITLE
Time out and Transfers in the same wallet

### ISSUE THREAD

**Issue by ricardowsky** [goatpig/BitcoinArmory#178]
He
Do not let me send from one wallet  address to another wallet, time out herror

how can I do this? How can I avoid the time out?

**Comment by PaulBendall** [comment]
Same issue as above. Can't send Bitcoin from Armory, TX error

**Comment by ricardowsky** [comment]
it has a solution?

**Comment by goatpig** [comment]
Grab the raw tx and broadcast it with your node, this will get you a better error message. Post it here.

**Comment by Pegasusltd** [comment]
I got time out also and has follow message in armorylog.....

Transaction:
   TxHash:    4e0dd72dc290584bab7b8e36a332ebbc888be10a4a0c459f98c82a0db7fc83c4 (BE)
   Version:   1
   nInputs:   1
   nOutputs:  2
   LockTime:  0
   Inputs: 
      PyTxIn:
         PrevTxHash: f1224babfc316bc82860cc2a68c0e01f75c8475ee4c9ec22f28700ff186a56b8 (BE)
         TxOutIndex: 1
         Script:     (47304402203c89f859bb763133243fbffa4129e3b103ad9b9c7e0a2a50ea6897)
         Sender:     1DJ66sM8dXHqoA7btBRzVkzEAcdU1W1f7B
         Seq:        4294967295
   Outputs: 
      TxOut:
         Value:   740000 (0.0074)
         Script:  OP_DUP OP_HASH160 (1C7xV2fdPZj4xC1wtQYFw17bRc3mpTnRQZ) OP_EQUALVERIFY OP_CHECKSIG
      TxOut:
         Value:   50000 (0.0005)
         Script:  OP_DUP OP_HASH160 (1AGASET28MKVJb3uUZ9MPp7FY782dsr3BD) OP_EQUALVERIFY OP_CHECKSIG

2017-03-03 12:07 (ERROR) -- ArmoryQt.py:3514 - Failure message: tx broadcast timed out

**Comment by ricardowsky** [comment]
tx prima ?????

**Comment by ricardowsky** [comment]
no me vale para nada el armory así, no tiene solución o no se sabe por que da el fallo?

**Comment by goatpig** [comment]
> Grab the raw tx and broadcast it with your node, this will get you a better error message. Post it here.

My instructions have not change. 

Stick to english.

**Comment by ricardowsky** [comment]
How do you do that, I do not see instructions??

**Comment by ricardowsky** [comment]
Parse: exception decoding Hex string: invalid characters encountered in Hex string

**Comment by ricardowsky** [comment]
Where is the raw tx ???

**Comment by goatpig** [comment]
Copy raw tx from Armory.

Use this command to broadcast it from your node:

https://bitcoin.org/en/developer-reference#sendrawtransaction

**Comment by ricardowsky** [comment]
Unable To find all tx inputs [09d26604ca9e858fc55aaeb8ce6887b8a9ac30414040f76f7eeb9f4348a483ba]

**Comment by ricardowsky** [comment]
??? 
I have already located the raw but this new failure I do not know

**Comment by ricardowsky** [comment]
raw=

{
"lock_time":0,
"size":258,
"inputs":[
{
"prev_out":{
"index":1,
"hash":"09d26604ca9e858fc55aaeb8ce6887b8a9ac30414040f76f7eeb9f4348a483ba"
},
"script":"483045022100c19de032335cc9e2b3628762f6280aa5f20333c5f7b21284a0756b529a65903002201fcb5154ad3f669f443ea8479aaa04ed5c2945dcf71159a9e582c51e77dd7ac301410470ad952d1f6b7167954883c34cfefb012cf9dcc5c2e010fa25a5ef4471abaa73af0d24682d676102c5fb3242cb5c24f36badc9b639097961cac7edd79cd77390"
}
],
"version":1,
"vin_sz":1,
"hash":"ed83e5aa485cc827c87fa48e05ad92ffc07bbf44524a552752759765ec334109",
"vout_sz":2,
"out":[
{
"script_string":"OP_DUP OP_HASH160 2f6c4e8de625c7857fe13109b39985cc24e4d370 OP_EQUALVERIFY OP_CHECKSIG",
"address":"15KkWJsPhZ1pWbuHwmDPkn75Bz1KRRHYZJ",
"value":4546000,
"script":"76a9142f6c4e8de625c7857fe13109b39985cc24e4d37088ac"
},
{
"script_string":"OP_DUP OP_HASH160 57f294d6b676b8ff4a216f8379348a1956a250ea OP_EQUALVERIFY OP_CHECKSIG",
"address":"1922PYMDKZ48a1zHiRU23SmGeyJiZbDrCr",
"value":11420180,
"script":"76a91457f294d6b676b8ff4a216f8379348a1956a250ea88ac"
}
]
}

**Comment by ricardowsky** [comment]
https://blockchain.info/pushtx

In this web

**Comment by goatpig** [comment]
That tx is formated. You need the straight up hexit string (only 0-9 a-f, no spaces, linebreaks or symbols)

**Comment by ricardowsky** [comment]
0100000001ba83a448439feb7e6ff740404130aca9b88768ceb8ae5ac58f859eca0466d209010000008b483045022100c19de032335cc9e2b3628762f6280aa5f20333c5f7b21284a0756b529a65903002201fcb5154ad3f669f443ea8479aaa04ed5c2945dcf71159a9e582c51e77dd7ac301410470ad952d1f6b7167954883c34cfefb012cf9dcc5c2e010fa25a5ef4471abaa73af0d24682d676102c5fb3242cb5c24f36badc9b639097961cac7edd79cd77390ffffffff02d05d4500000000001976a9142f6c4e8de625c7857fe13109b39985cc24e4d37088ac1442ae00000000001976a91457f294d6b676b8ff4a216f8379348a1956a250ea88ac00000000


I'm good, it's a copy  parte of armory

**Comment by goatpig** [comment]
Means your db is out of sync. You should rebuild & rescan then try again.

**Comment by ricardowsky** [comment]
Well now armory no longer indicates the transaction but I do not have the money either, what can I do?

**Comment by ricardowsky** [comment]
Let's see if I understand before I said that I had more BTC than I have and that is the problem or money has come out and armory does not tell me?

**Comment by goatpig** [comment]
> Let's see if I understand before I said that I had more BTC than I have and that is the problem or money has come out and armory does not tell me?

I don't know which it is. Check the transaction history for the output you wanted to spend, that should tell you where the money went and which one of your assumption is right.

**Comment by ricardowsky** [comment]
Now gives me an **inexplicable error**, what do I do?

**Comment by ricardowsky** [comment]
For a month I can not do anything with armory, it happens to me alone?

**Comment by ricardowsky** [comment]
error in write to socket: 10038 

in the msdos windos???? what???

**Comment by goatpig** [comment]
Build dev and try with that.

**Comment by ricardowsky** [comment]
????

**Comment by goatpig** [comment]
Pull the dev branch, build the code and test spends with that revision.

**Comment by hadzajlic** [comment]
Update core bitcoin client to v0.14.0 and now I can not send bitcoins
used default armory recommended fee 
[armorylog_20170319_1254.txt](https://github.com/goatpig/BitcoinArmory/files/852886/armorylog_20170319_1254.txt)
I had to submit raw transaction :
https://blockchain.info/tx/c8a8800dab2ceaf849fd5b624bb28df4b16334f3206884451425d9c2e1b0f9e8

**Comment by achow101** [comment]
Anyone who has this error, please post both the armorylog.txt and dbLog.txt files which can be found in the Armory data directory.
