### ISSUE TITLE
armory tx broadcast timed out

### ISSUE THREAD

**Issue by achillesuk** [goatpig/BitcoinArmory#190]
[armorylog_20170319_2102.txt](https://github.com/goatpig/BitcoinArmory/files/853568/armorylog_20170319_2102.txt)

I tried selecting the default fee when it prompts but I still getting the same error.

**Comment by achow101** [comment]
Can you please post your dbLog.txt file which can be found in C:\Users\Achilles\AppData\Roaming\Armory\

**Comment by sbitzer** [comment]
I had the same issue and resolved it by reverting back from version 0.14.0 of Bitcoin core to 0.13.2.

**Comment by micressor** [comment]
+1
Same issue with Armory 0.95.1 + bitcoin core 0.14.0.

```
.bitcoin/debug.log:
2017-03-29 12:40:10 Misbehaving: 127.0.0.1:47978 peer=32 (0 -> 1)
2017-03-29 12:40:10 ProcessMessages(inv, 37 bytes) FAILED peer=32
```


```
~/.armory/dbLog.txt
(ERROR) ArmoryQt.py:3509 - Transaction was not accepted by the Satoshi client
(ERROR) ArmoryQt.py:3510 - Raw transaction:
(ERROR) (PPRINT from /usr/bin/../lib/armory/ArmoryQt.py:3511)
  [...]
(ERROR) ArmoryQt.py:3512 - Transaction details
(ERROR) (PPRINT from /usr/bin/../lib/armory/ArmoryQt.py:3513)
Transaction:
 [...]
(ERROR) ArmoryQt.py:3514 - Failure message: tx broadcast timed out
```

Receive transactions: OK
Send transactions does not work.

**Comment by achow101** [comment]
Please read https://bitcointalk.org/index.php?topic=1846233.0
