### ISSUE TITLE
Error building databases use bitcoinarmory-v0.95.1

### ISSUE THREAD

**Issue by jackyxie** [goatpig/BitcoinArmory#193]
I use bitcoinarmory-v0.95.1 and bitcoin-0.13.1. After the bitcoin loading all the blockchain data. But armory still processing database of itself as several day passed. After I downgrade to v0.93.3, it work immediately.

**Comment by goatpig** [comment]
0.95 DB is not compatible with 0.93. Either delete the old DB or use another folder.
