### ISSUE TITLE
Disconnect GitHub fork link?

### ISSUE THREAD

**Issue by STRML** [goatpig/BitcoinArmory#194]
The fact that this is forked from etothepi/BitcoinArmory causes it not to be searchable via the GH UI; rumor has it this link can be severed via a simple email to support. Would be a helpful addition; then the fork note can just be added to the top of the README.

**Comment by goatpig** [comment]
There also was a proposal to move the project to an enterprise style repo named after the project (instead of my own repo), ala Bitcoin Core. 

You should discuss this with @achow101

**Comment by achow101** [comment]
Moving the repo to an organization repo would still have it marked as a fork. I think it would be better to ask github support to remove the fork marker regardless so that it can be searched. The codebase has significantly diverged from the original by this point.

**Comment by goatpig** [comment]
Ok, will deal with it after 0.96 is released.

**Comment by MichaelGooden** [comment]
@goatpig Just a reminder, 0.96 has been released now.
