### ISSUE TITLE
tx broadcast timed out

### ISSUE THREAD

**Issue by Ondart1** [goatpig/BitcoinArmory#198]
I need help. I am using the latest Armory Client 0.95.1 and Bitcoin Core 14.0000. I attempted to send four signed off-line broadcast transactions using the same BTC amount. The first two sent without error; the second two produced an error 'tx broadcast timed out'. I used the recommended fee and the fee was the same for all four transactions. I attempted to use the bitcoin-cli sendrawtransaction using bitcoin core and received error code: -22, error message: TX decode failed. Here are the log details for the first one for reference:

`2017-03-28 20:31 (INFO) -- TxFrames.py:1917 - Selected transaction file to load: /media/XXXX/VoyagerGT/armory_XXXXXXXX_.signed.tx
2017-03-28 20:31 (INFO) -- (PPRINT from /usr/lib/armory/ArmoryQt.py:3491)

  01000000 017c21f7 314197ca fe1c460a 1275a0e8 8cabb348 1f08a7b1 001a0251 
  f9b29311 7e000000 008a4730 44022021 88a8a718 7dbd0a1f 062fa728 9a908fa7 
  294fc67d 653f24a4 22bbc3f6 3da72d02 202cabda 7ec982de 35806077 04962039 
  5ea78bc2 8dff61e1 065bca1f 98478da7 14014104 f73289c6 b16c2b7b 6e01f7d7 
  b30da299 5bcd8f9e 136c86a4 5039ec8a 31023d8b a37e6fb8 d19808a6 f4f5820f 
  3e122587 c4589988 d3a0ba6c 2473b316 fe475e87 ffffffff 02d776d4 17000000 
  001976a9 1465d136 b0e5aa69 b24caccb 041aff3f 5740274e 6688ac00 c2eb0b00 
  00000019 76a9144f 12f9d869 87b81719 830732c4 9a420450 8a9d7c88 ac000000 
  00 
2017-03-28 20:31 (INFO) -- (PPRINT from /usr/lib/armory/ArmoryQt.py:3492)
Transaction:
   TxHash:    97b99c976dad70c67acf2416b27f5114d99f0e796578d63fb17354b7dd36c76a (BE)
   Version:   1
   nInputs:   1
   nOutputs:  2
   LockTime:  0
   Inputs: 
      PyTxIn:
         PrevTxHash: 7e1193b2f951021a00b1a7081f48b3ab8ce8a075120a461cfeca974131f7217c (BE)
         TxOutIndex: 0
         Script:     (47304402202188a8a7187dbd0a1f062fa7289a908fa7294fc67d653f24a422bb)
         Sender:     1C1twjuHXXWjABiGeRxebpmBRbFQNJNhfZ
         Seq:        4294967295
   Outputs: 
      TxOut:
         Value:   399800023 (3.99800023)
         Script:  OP_DUP OP_HASH160 (1AHMso1JYBhY8qWJBAEtCzE8p9y4TzHHHo) OP_EQUALVERIFY OP_CHECKSIG
      TxOut:
         Value:   200000000 (2.0)
         Script:  OP_DUP OP_HASH160 (18D77dPGgHZXoLN2UgyFhb6BqmQKhhqwK4) OP_EQUALVERIFY OP_CHECKSIG

2017-03-28 20:31 (INFO) -- ArmoryQt.py:3496 - Sending Tx, 6ac736ddb75473b13fd67865790e9fd914517fb21624cf7ac670ad6d979cb997
2017-03-28 20:31 (ERROR) -- ArmoryQt.py:3509 - Transaction was not accepted by the Satoshi client
2017-03-28 20:31 (ERROR) -- ArmoryQt.py:3510 - Raw transaction:
2017-03-28 20:31 (ERROR) -- (PPRINT from /usr/lib/armory/ArmoryQt.py:3511)

  01000000 017c21f7 314197ca fe1c460a 1275a0e8 8cabb348 1f08a7b1 001a0251 
  f9b29311 7e000000 008a4730 44022021 88a8a718 7dbd0a1f 062fa728 9a908fa7 
  294fc67d 653f24a4 22bbc3f6 3da72d02 202cabda 7ec982de 35806077 04962039 
  5ea78bc2 8dff61e1 065bca1f 98478da7 14014104 f73289c6 b16c2b7b 6e01f7d7 
  b30da299 5bcd8f9e 136c86a4 5039ec8a 31023d8b a37e6fb8 d19808a6 f4f5820f 
  3e122587 c4589988 d3a0ba6c 2473b316 fe475e87 ffffffff 02d776d4 17000000 
  001976a9 1465d136 b0e5aa69 b24caccb 041aff3f 5740274e 6688ac00 c2eb0b00 
  00000019 76a9144f 12f9d869 87b81719 830732c4 9a420450 8a9d7c88 ac000000 
  00 
2017-03-28 20:31 (ERROR) -- ArmoryQt.py:3512 - Transaction details
2017-03-28 20:31 (ERROR) -- (PPRINT from /usr/lib/armory/ArmoryQt.py:3513)
Transaction:
   TxHash:    97b99c976dad70c67acf2416b27f5114d99f0e796578d63fb17354b7dd36c76a (BE)
   Version:   1
   nInputs:   1
   nOutputs:  2
   LockTime:  0
   Inputs: 
      PyTxIn:
         PrevTxHash: 7e1193b2f951021a00b1a7081f48b3ab8ce8a075120a461cfeca974131f7217c (BE)
         TxOutIndex: 0
         Script:     (47304402202188a8a7187dbd0a1f062fa7289a908fa7294fc67d653f24a422bb)
         Sender:     1C1twjuHXXWjABiGeRxebpmBRbFQNJNhfZ
         Seq:        4294967295
   Outputs: 
      TxOut:
         Value:   399800023 (3.99800023)
         Script:  OP_DUP OP_HASH160 (1AHMso1JYBhY8qWJBAEtCzE8p9y4TzHHHo) OP_EQUALVERIFY OP_CHECKSIG
      TxOut:
         Value:   200000000 (2.0)
         Script:  OP_DUP OP_HASH160 (18D77dPGgHZXoLN2UgyFhb6BqmQKhhqwK4) OP_EQUALVERIFY OP_CHECKSIG

2017-03-28 20:31 (ERROR) -- ArmoryQt.py:3514 - Failure message: tx broadcast timed out`

Here is the failed send raw transaction result:

`bitcoin-cli sendrawtransaction 01000000017c21f7314197cafe1c460a1275a0e88cabb3481f08a7b1001a0251f9b293117e000000008a47304402202188a8a7187dbd0a1f062fa7289a908fa7294fc67d653f24a422bbc3f63da72d02202cabda7ec982de35806077049620395ea78bc28dff61e1065bca1f98478da714014104f73289c6b16c2b7b6e01f7d7b30da2995bcd8f9e136c86a45039ec8a31023d8ba37e6fb8d19808a6f4f5820f3e122587c4589988d3a0ba6c2473b316fe475e87ffffffff02d776d417000000001976a91465d136b0e5aa69b24caccb041aff3f5740274e6688ac00c2eb0b000000001976a9144f12f9d86987b81719830732c49a4204508a9d7c88ac000000
error code: -22
error message:
TX decode failed`

I appreciate the assistance,
-Ondart

**Comment by Ondart1** [comment]
Here is additional information. When I sent the raw transaction using bitcoin core, I had taken the transaction data from the log and was stripping out the spaces and carriage returns but realized afterwards that Armory had the ability to copy the transaction data. When I rebroadcast both transactions, I got a different error so I obviously had made a typo initially. This is the error I am getting now when using the 'Copy Raw TX (hex)' feature in Armory an then attempting to sendrawtransaction:
'
error code: -25
error message:
Missing inputs
'

**Comment by Ondart1** [comment]
I think I just had an epiphany (maybe). When I signed my off-line transactions, i did them in a row, 4 ea, from two different wallets. When I broadcast them, I did not send them in the order that I signed them as I can see the time stamp on the file names are one minute apart and I had randomly selected the two oldest transactions from the four and both of the two transactions that succeeded were from each of the two wallets. Could there be a problem when signing multiple transactions from a single wallet and attempting to broadcast them out of order? I do see the change is different on two of the four. Maybe I should have created one transaction at a time and sent them before doing another. I have no idea if this is even relevant but wanted to throw this out there for comment.

**Comment by Ondart1** [comment]
I did another test using coin I received today. When I attempted to send bitcoin, I received the same Failure message: tx broadcast timed out. I decided to use coin control and send only coin that had come from a single source address instead of from all addresses that had a balance in my wallet and the transfer was successful. I think this means that Armory had a problem with some of the addresses from my wallet balance and I have no idea why one or more of those addresses prevent sending bitcoin. Tomorrow evening I intend to try and send new off-line transactions again but I will use only one source address with coin control to work around the problem and I think this will work. I'll send more detail when I do this. If you have any ideas on this issue, please let me know goatpig or achow. Hope this helps...

-Ondart

**Comment by goatpig** [comment]
This is known issue, fixed in 0.96

**Comment by achow101** [comment]
Please read https://bitcointalk.org/index.php?topic=1846233.0

You will need to downgrade to Bitcoin Core 0.13.2 for now.
