### ISSUE TITLE
Armory won't send my transaction

### ISSUE THREAD

**Issue by pessisteel** [goatpig/BitcoinArmory#200]
had trouble broadcasting straight though armory, opened bitcoin core first and the error says to check direct link for transaction, but it never shows up.
[armorylog_20170405_1718.txt](https://github.com/goatpig/BitcoinArmory/files/900948/armorylog_20170405_1718.txt)

**Comment by goatpig** [comment]
https://bitcointalk.org/index.php?topic=1846233.0
