### ISSUE TITLE
0.95.1: ArmoryDB crashes on the FreeBSD, 'Building Databases' step freezes at 98%

### ISSUE THREAD

**Issue by yurivict** [goatpig/BitcoinArmory#207]
I am trying to update the FreeBSD port to 0.95.1.
ArmoryDB crashes:
> pid 49427 (ArmoryDB), uid 1001: exited on signal 6

and 'Building Databases' step freezes.

The problem didn't exist in 0.93.3.

**Comment by goatpig** [comment]
Did you give it a fresh DB folder? 0.93 and 0.95 DBs are not compatible.

**Comment by yurivict** [comment]
This happens after I deleted the DB folder.

**Comment by goatpig** [comment]
show dblog.txt

**Comment by yurivict** [comment]
dbLog.txt: https://expirebox.com/download/6b0d3cff7f81a100b27ef1d8ecaccc3d.html

armory doesn't sense the ArmoryDB process crash.

**Comment by goatpig** [comment]
do the unit tests pass?

**Comment by yurivict** [comment]
These tests fail:
```
[  FAILED  ] TransactionsTest.CheckChain_Test (186 ms)
[  FAILED  ] TransactionsTest.Wallet_SpendTest_P2PKH (197 ms)
[  FAILED  ] TransactionsTest.Wallet_SpendTest_P2WPKH (149 ms)
[  FAILED  ] BlockUtilsBare.Load3Blocks_RBF (48 ms)
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] TransactionsTest.CheckChain_Test
[  FAILED  ] TransactionsTest.Wallet_SpendTest_P2PKH
[  FAILED  ] TransactionsTest.Wallet_SpendTest_P2WPKH
[  FAILED  ] BlockUtilsBare.Load3Blocks_RBF
```

**Comment by goatpig** [comment]
These are 0.96 tests, Which version are you actually running?

**Comment by yurivict** [comment]
I am running 0.95.1 and getting these failures.

**Comment by goatpig** [comment]
Besides the RBF test, everything else is testing 0.96 code. At any rate, you should work with 0.96 instead.

**Comment by yurivict** [comment]
0.96 isn't released. I only see 0.95.99.2-testing.
I am trying to update the FreeBSD port, and can only update to the officially released version.

**Comment by goatpig** [comment]
0.96 is in testing atm. Any fix you have for 0.95 can only go into 0.96. I will not go through an entire release process to push fixes to 6 months old code when the new stuff is out the door in a week or 2.

Your way forward is this:

1) Get 0.96 to build. It lays in the testing branch atm.
2) Run the unit tests in there, if they are failing, I'll try to figure it out.
3) Run it against the testnet. Again, if it fails there, I'll try to figure it out.
4) Run it against the mainnet. Same deal.

In return, I'll delay the release until these issues are fixed, unless they are too convoluted, in which case they will go in for 0.96.1

**Comment by yurivict** [comment]
Ok, I will try to build 0.96.

**Comment by yurivict** [comment]
Same problem with 0.96. ArmoryDB crashes, armory shows 99% and 2 seconds forever.

**Comment by goatpig** [comment]
Try the unit tests then the testnet. I'm off to bed for today.

**Comment by yurivict** [comment]
Makefile in 0.96 doesn't have a test target (used to be ```test: gtest pytest```).

**Comment by goatpig** [comment]
The test binaries are built in the cppForSwig/gtest folder regardless.

**Comment by yurivict** [comment]
CppBlockUtilsTests has failures:
```
[  FAILED  ] 10 tests, listed below:
[  FAILED  ] LMDBTest.OpenClose
[  FAILED  ] LMDBTest.OpenCloseOpenNominal
[  FAILED  ] LMDBTest.PutGetDelete
[  FAILED  ] LMDBTest.STxOutPutGet
[  FAILED  ] LMDBTest.PutGetBareHeader
[  FAILED  ] LMDBTest.PutGetStoredTxHints
[  FAILED  ] LMDBTest.PutGetStoredScriptHistory
[  FAILED  ] TransactionsTest.CheckChain_Test
[  FAILED  ] BlockUtilsBare.Load3Blocks_RBF
[  FAILED  ] BlockUtilsBare.Replace_ZC_Test
```
ContainerTests never stops, but prints this:
```
DB1kIterTest.cpp:691: Failure
Value of: 105 * 100000000ULL
  Actual: 10500000000
Expected: unconfirmedBalance
Which is: 13500000000
```

**Comment by goatpig** [comment]
There is some issue with how std::thread and/or std::promise is implemented with this compiler.

Are you sure the stdc=c++11 argument is added to the compiler calls?

**Comment by yurivict** [comment]
```c++11``` is in the command lines.

**Comment by goatpig** [comment]
For the good measure try syncing on the testnet, but at this rate, I have to test the operating system directly.

**Comment by yurivict** [comment]
Yes, I think so.

**Comment by yurivict** [comment]
Just in case, the current port version I am trying to build is here: https://github.com/yurivict/FreeBSD-finance-bitcoin-armory

**Comment by goatpig** [comment]
Have you considered making a PR of the patch instead? It would be simpler to maintain it all within the same code base.

**Comment by yurivict** [comment]
I did:
* https://github.com/etotheipi/BitcoinArmory/pull/227
* https://github.com/etotheipi/BitcoinArmory/pull/228
but they have never been merged.

**Comment by goatpig** [comment]
etotheipi's repo has not been maintained in almost 2 years now.

**Comment by yurivict** [comment]
Overcome by events.
