### ISSUE TITLE
tx broadcast timed out

### ISSUE THREAD

**Issue by Pertou** [goatpig/BitcoinArmory#208]
Hello,

It looks like this is a classic error but even after reading many posts I can't find a solution.

You can find the log attached. 

[armorylog_20170413_1902.txt](https://github.com/goatpig/BitcoinArmory/files/920331/armorylog_20170413_1902.txt)

The goal is : Transfert funds from my Armory online wallet to an offline wallet via Watch Only Adresse.

Thank you for your help, I'll answer any question if needed.

EDIT : 
Armory version : 0.95.1
Bitcoin Core version v0.14.0 (64-bit)
I disable the option "Let armory run bitcoin core"

Regards,
Pertou

**Comment by Pertou** [comment]
Nevermind, I had to downgrade Bitcoin Core to v0.13.2.

It works fine now.

**Comment by Xummerland** [comment]
Having the same problem.
Version 0.95.1 beta 374672b751
I disabled the option "Let armory run ...", because that was the only way not having it crushing on startup
Now I'm running Bitcoint QT (V 5.7.1) first, and start Armory when QT has finished the sync.

Please advise.

**Comment by achow101** [comment]
Upgrade to [Armory 0.96.1-testing builds](https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.0.1-testing)
