### ISSUE TITLE
Build errors and warnings in 0.96

### ISSUE THREAD

**Issue by yurivict** [goatpig/BitcoinArmory#209]
First few errors:

```
CppBlockUtils_wrap.cxx:5522:14: error: cannot initialize return object of type 'std::vector<unsigned long long, std::allocator<unsigned long long> > *' with an rvalue of type 'std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > *'
      return swig::getslice(self, i, j, 1);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CppBlockUtils_wrap.cxx:5545:14: error: cannot initialize return object of type 'std::vector<unsigned long long, std::allocator<unsigned long long> > *' with an rvalue of type 'std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > *'
      return swig::getslice(self, id, jd, step);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CppBlockUtils_wrap.cxx:5581:14: warning: returning reference to local temporary object [-Wreturn-stack-address]
      return *(swig::cgetpos(self, i));
             ^~~~~~~~~~~~~~~~~~~~~~~~~
CppBlockUtils_wrap.cxx:5596:190: error: no matching member function for call to 'erase'
SWIGINTERN std::vector< unsigned long long >::iterator std_vector_Sl_uint64_t_Sg__erase__SWIG_0(std::vector< uint64_t > *self,std::vector< unsigned long long >::iterator pos){ return self->erase(pos); }
                                                                                                                                                                                       ~~~~~~^~~~~
/usr/include/c++/v1/vector:731:40: note: candidate function not viable: no known conversion from '__wrap_iter<pointer>' to '__wrap_iter<const_pointer>' for 1st argument
    _LIBCPP_INLINE_VISIBILITY iterator erase(const_iterator __position);
                                       ^
/usr/include/c++/v1/vector:732:14: note: candidate function not viable: requires 2 arguments, but 1 was provided
    iterator erase(const_iterator __first, const_iterator __last);
             ^
CppBlockUtils_wrap.cxx:5597:241: error: no matching member function for call to 'erase'
SWIGINTERN std::vector< unsigned long long >::iterator std_vector_Sl_uint64_t_Sg__erase__SWIG_1(std::vector< uint64_t > *self,std::vector< unsigned long long >::iterator first,std::vector< unsigned long long >::iterator last){ return self->erase(first, last); }

                                            ~~~~~~^~~~~
CppBlockUtils_wrap.cxx:5598:246: error: no matching member function for call to 'insert'
SWIGINTERN std::vector< unsigned long long >::iterator std_vector_Sl_uint64_t_Sg__insert__SWIG_0(std::vector< uint64_t > *self,std::vector< unsigned long long >::iterator pos,std::vector< unsigned long long >::value_type const &x){ return self->insert(pos, x); }

                                                 ~~~~~~^~~~~~
```

The full build log is here:
https://expirebox.com/download/56a8a614f390351084cfe40836f1f0a4.html

clang is the main compiler on FreeBSD, and previous versions of armory were building with clang fine.
Commit: dc50e4b

**Comment by goatpig** [comment]
the makefile supports clang as evidenced here:

https://github.com/goatpig/BitcoinArmory/blob/testing/cppForSwig/Makefile.am#L11

Your code is complaining about uint64_t defined as unsigned long long which demonstrates clang has been properly detected:

https://github.com/goatpig/BitcoinArmory/blob/testing/cppForSwig/CppBlockUtils.i#L43

You should consider forcing the uint64_t definition in the .i to long unsigned int to see if that fixes your issue.

**Comment by yurivict** [comment]
Thanks, changing uint64 type fixed build errors.

Now 'install' target doesn't install .png files any more, like it did before.

Another new problem is that 'gmake install' tries to repeat some build steps, beginning with ```swig -c++ -python -threads  -D__CLANG__ CppBlockUtils.i``` command.

**Comment by goatpig** [comment]
make install is broken atm. None of the supported OSes use that, so it has not received much attention.

As for the swig part, that's the only when autotools provides to guarantee the wrapper is rebuilt, as it doesn't understand what file swig itself depends on.

You should focus on getting the binaries to work, The autotools setup is orthogonal to that.

**Comment by yurivict** [comment]
> make install is broken atm. None of the supported OSes use that, so it has not received much attention.

Projects that use autotools are supposed to install with ```make install```. In any case, it was still working in 0.95.1. This is a bad regression IMO. Running binaries now.

**Comment by goatpig** [comment]
> This is a bad regression IMO

I'm not suggesting that the install target won't be fixed. I simply stated the in its current state, it is broken. It had to be left on the side for the time and effort it took to get autotools working with both Linux and OSX.

Fixing the install target isn't particularly hard, hence not a top priority item.

> In any case, it was still working in 0.95.1

It used plain makefiles, which made it painful to use external libraries or support exotic operating systems. Autotools is also an important step towards deterministic builds.

**Comment by yurivict** [comment]
Overcome by events.
