### ISSUE TITLE
Armory doesn't sync up when port 9001 is in use

### ISSUE THREAD

**Issue by dermoth** [goatpig/BitcoinArmory#214]
Armory communicates with ArmoryDB over port 9001. If the port is already in use, Armory just sits there syncing forever. The only error I could find is in `armorycpplog.txt`:

    Log file opened at 1494007129: /home/user/.armory/armorycpplog.txt
    -ERROR - 1494007130: (SocketObject.cpp:438) POLLERR error in readAndWrite
    -ERROR - 1494007130: (SwigClient.cpp:61) POLLERR error in readAndWrite

It turns out Tor's default listen port for relay is also 9001 and when I decided to get my relay back online it clashed with Armory.

I think the best solution might be using a dynamic port by default for ArmoryDB (i.e. let the OS pick) and find a way to tell Armory what port it was launched on... Otherwise, at least something not used by Tor might be a good idea.

In any case if the port is static or forced through config there should be an explicit error when ArmoryDB fails to start because of that.

Regards

**Comment by goatpig** [comment]
I already changed it from 9050 because that was Tor's port >_>

Your solution is not acceptable, it breaks predicting the port by other processes. What you want is a cli arg to customize the listen port.

**Comment by dermoth** [comment]
I meant to suggest *either* using a dynamic port when the user didn't specifically define a listen port *or* just use a different port that's not widely used.

More importantly, when ArmoryDB fails to start, will Armory UI at least give proper feedback to the user? Right now I couldn't see any clue to the issue in the UI nor log files and I think most users would have a very hard time figuring out an issue like this.

Regards

**Comment by goatpig** [comment]
> More importantly, when ArmoryDB fails to start, will Armory UI at least give proper feedback to the user? 

https://github.com/goatpig/BitcoinArmory/blob/master/cppForSwig/BDM_Server.cpp#L1158

No the DB exits leaving a message in its log.

**Comment by achow101** [comment]
Tor uses multiple ports. Ports 80, 443, 9001, and 9030 are commonly used ORPorts which are used for setting up relays. 9050 is the SOCKS proxy port used by clients.

**Comment by dermoth** [comment]
The only relevant error I could find was in the OP and is not very helpful. I could test again, but either ArmoryDB did not log to a file or the function referenced above did not run or fail as expected.

**Comment by goatpig** [comment]
https://github.com/goatpig/BitcoinArmory/commit/920d79378cc03e4baa2da8975ed30bbc05a273bc

This commit should cover the issue

**Comment by dermoth** [comment]
I'd love to test but the latest -testing release wasn't compiled for libstdc++6-4.9 (the gcc 4.7 version). Is it hard to add it?

I wanted to reproduce an offline signing issue I've seen on an old version using testnet, and testnet conflicts with tor too.

**Comment by goatpig** [comment]
I'll be doing these builds once I do the full 0.96.1 release. It is not hard to build it per se, just time consuming.

**Comment by dermoth** [comment]
Thanks for the quick reply, in that case I will test on that version once released. FWIW I tried to work around it using `--armorydb-port=<unused_port>` and it failed, explicitly this time (I guess the non-explicit failure so far was because it can actually connect when port is in use). That was on v0.95.1-1.

Thank you for the awesome work!

**Comment by goatpig** [comment]
That's because that command line arg was ambiguous before. 

The DB only speaks FCGI and listens to 127.0.0.1. FCGI itself is a web service layer that encapsulated HTTP. It is meant to run behind a daemon. When the client spawns the DB, it speaks directly FCGI to the DB instead of native HTTP, which would require spawning a daemon too (don't want that for local operations).

Prior to this change, the client would only speak FCGI if it was using the default IP and port to connect to the DB. After this change, the client will only speak FCGI if it is trying to connect to 127.0.0.1, regardless of the port.

At the time there also was no CLI arg to give the DB another listening port, the --armorydb-port arg assumed the DB was behind a http daemon.
