### ISSUE TITLE
TX broadcast time out (send)

### ISSUE THREAD

**Issue by OrangeDirk** [goatpig/BitcoinArmory#215]
Hi,

After days of trying my armory wallet is up and running. I created a wallet in 2013 and luckily i made i back up.

Now i want to get my funds out but it doesnt send. I get the message in my title. I tried it a couple of times and also with a larger fee. Can somebody help me? I included the log file.

[armorylog_20170506_0904.txt](https://github.com/goatpig/BitcoinArmory/files/980760/armorylog_20170506_0904.txt)

**Comment by goatpig** [comment]
Delete your Armory database and start it again.

Use the forum for the follow up, the issue page is for developers.

https://bitcointalk.org/index.php?board=97.0
