### ISSUE TITLE
poll() may be unreliable on some versions of OSX

### ISSUE THREAD

**Issue by jameshilliard** [goatpig/BitcoinArmory#223]
I may have hit [this issue](https://daniel.haxx.se/blog/2016/10/11/poll-on-mac-10-12-is-broken/) with Armory 0.96 built on OSX 10.12 although it doesn't seem to readily reproduce. It may be a good idea to move to libevent or Boost.Asio in any case.

```
-ERROR - 1494752276: (BitcoinP2P.cpp:851) caught SocketError exception in processDataStackThread: POLLNVAL in readFromSocketThread
```

**Comment by goatpig** [comment]
I'm trying not to inflate the list of dependencies over simple usage. If poll is indeed broken on OSX 10.12, I'll considering replacing the 50 LoC for poll with 50 LoC for select.

**Comment by jameshilliard** [comment]
I'd normally agree but this may be a case where it make sense to use a library due to portability issues. libevent and Boost.Asio use the newer underlying api's like epoll on linux and kqueue on BSD/OSX which have advantages over poll and select, Bitcoin Core is planning to move to libevent from select for networking.
