### ISSUE TITLE
tx broadcast timed out (get) armory 0.96.0.1 bitcoin core 14.1

### ISSUE THREAD

**Issue by sharkkkman** [goatpig/BitcoinArmory#228]
Title says it all - here are my log files -> https://pastebin.com/6zMpPyjZ

I've been trying to get this to work literally all week but I've gotten 0 results
here's some of the stuff I've done:
- I deleted my database folder so new ones could be created
- upgraded to 0.96.0.1
- restarted my computer (multiple times)
- raised sending amount to .0005
- cleared unconfirmed transactions (switched to expert mode)

I would like some help ASAP because my VPN expires in less than 24 hrs and I only have enough bitcoins for the purchase I'd like to make

**Comment by goatpig** [comment]
There's nothing in your log file indicating you even attempted to create a transaction.

**Comment by goatpig** [comment]
01000000 028769a7 7b2353b8 ac71a40a a3f6728d c3eb6dac e00f4c45 6325ccab 
  c1b0f11f 3c010000 008b4830 45022100 85033ac3 dbaf9c3f 4d144e28 6d74430e 
  3cd65ac8 c8d33a94 3328d9df cbe53822 02204196 0db5e5ad f644fbfe dae929e3 
  c88b1418 fbc93f22 2252a2fa e9775c97 6e570141 04424d50 8b2226bc 4dc49c2f 
  281bc7a8 f481fc99 b11c2658 08662d41 ba2f1352 88a3c93f 6c0c4e1e b3874ac1 
  119fccc5 41c14636 221c0c0f bbba9196 40497535 adffffff ff539361 11ad6a0f 
  7bf0add6 b3c791bc 355e7587 9417e641 200f7e1f f3e108b9 71000000 008a4730 
  44022040 76d3a929 b2389163 c54db34f bf235dc3 ce4a4de8 ab827fd7 24984ec8 
  3c12c802 20637e7e e494c337 6a529217 a3e27573 48825f34 88392feb 030aae56 
  1b3a65ee 6a014104 dc875d42 efe31db5 1052aa32 b7fdbfa0 635b2ec2 42494169 
  8a28887b 8d06627d 8b618e26 2f702c96 e134e83a 3c2a85f8 1d22f2ee b4a95386 
  ea5ea4fb d707d4f8 ffffffff 01533028 00000000 001976a9 14adbad7 ca869f2e 
  ca2c5149 330b39fd 448a0300 ad88ac42 200700 
2017-05-18 15:14:03 (ERROR) -- ArmoryQt.py:3116 - Transaction details
2017-05-18 15:14:03 (ERROR) -- (PPRINT from ArmoryQt.py:3117)
Transaction:
   TxHash:    f3b653e105dc85d16da6f34556d3abff40571eb2ec7466bc7edebb39314ebc65 (BE)
   Version:   1
   nInputs:   2
   nOutputs:  1
   LockTime:  467010
   Inputs: 
      PyTxIn:
         PrevTxHash: 3c1ff1b0c1abcc2563454c0fe0ac6debc38d72f6a30aa471acb853237ba76987 (BE)
         TxOutIndex: 1
         Script:     (48304502210085033ac3dbaf9c3f4d144e286d74430e3cd65ac8c8d33a943328)
         Sender:     1CsAKXBk1nHiZkSXsyydSVyrayYXF7jRRU
         Seq:        4294967295
      PyTxIn:
         PrevTxHash: 71b908e1f31f7e0f2041e6179487755e35bc91c7b3d6adf07b0f6aad11619353 (BE)
         TxOutIndex: 0
         Script:     (47304402204076d3a929b2389163c54db34fbf235dc3ce4a4de8ab827fd72498)
         Sender:     1RNdJuA2zB9PxRtDpiLTmJkdFL7t1ibMT
         Seq:        4294967295
   Outputs: 
      TxOut:
         Value:   2633811 (0.02633811)
         Script:  OP_DUP OP_HASH160 (1GqbjGA3zYNL4PTfKk4BVicwKGXikh6VpT) OP_EQUALVERIFY OP_CHECKSIG

2017-05-18 15:14:03 (ERROR) -- ArmoryQt.py:3118 - Failure message: tx broadcast timed out (get)

**Comment by goatpig** [comment]
This appears the be the tx failing to broadcast. You'll want to broadcast the raw binary straight from your node to get a better error code.

**Comment by sharkkkman** [comment]
How would I be able to do that? Honestly I'm a noob, I only first accessed the dark net last week.

**Comment by sharkkkman** [comment]
How would I be able to do that? Honestly I'm a noob, I only first accessed the dark net last week.

**Comment by goatpig** [comment]
Search it or ask on the forums. Explaining Bitcoin RPC features is out of the scope of this repo. This issue page is for developers. You can get help with your troubleshooting on the forums:

https://bitcointalk.org/index.php?board=97.0
