### ISSUE TITLE
tx broadcast timed out (get)

### ISSUE THREAD

**Issue by bierdopjeee** [goatpig/BitcoinArmory#230]
Hi all,

Been using Armory since about 2014.

I hope someone can help with this. For a few days now I'm getting this error:
**tx broadcast timed out (get)**

I've already reinstalled Armory and restored my wallet a few times. I came from 0.93 version I believe, now using 0.96.

I also tried a higher fee, of 600s/byte. Did not make a difference.

Might there be some kind of corruption?
I shall attach the error en log file.

Thank you for your time.

[armorylog_20170520_1459.txt](https://github.com/goatpig/BitcoinArmory/files/1016177/armorylog_20170520_1459.txt)
<img width="321" alt="tx broadcast timed out get" src="https://cloud.githubusercontent.com/assets/28825425/26276018/6515d5e8-3d6e-11e7-8863-f3f2438c4298.PNG">

**Comment by goatpig** [comment]
https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.0.1-testing

Try this version

**Comment by bierdopjeee** [comment]
Thanks, trying this right now.

**Comment by bierdopjeee** [comment]
I think there might be no blockchain at all. I can't find any big blob of data that should be the blockchain folder.

**Comment by goatpig** [comment]
You can't create transactions without blockchain data. This page is for devs and advanced users. At this point you need to post in the forums:

https://bitcointalk.org/index.php?board=97.0

**Comment by bierdopjeee** [comment]
Alright, thanks.
