### ISSUE TITLE
Armory's 'libfcgi.so.0.0.0' conficts with Ubuntu 17.04's 'libfcgi.so.0.0.0' from package 'libfcgi0ldbl'

### ISSUE THREAD

**Issue by nikolajsheller** [goatpig/BitcoinArmory#236]
When attempting to install Armory on Ubuntu 17.04 where package 'libfcgi0ldbl' is installed, the installation fails with:

dpkg: error processing archive armory_0.96-gcc5.4_amd64.deb (--install):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libfcgi.so.0.0.0', which is also in package libfcgi0ldbl:amd64 2.4.0-8.4

I suspect this file should be removed from the package and a dependency for 'libfcgi0ldbl' should be added to the .deb package.

**Comment by RockWest** [comment]
I am having the same issue in Ubuntu 18.04.2 LTS while attempting to install armory_0.96-gcc5.4_amd64.deb
