### ISSUE TITLE
Armory stuck on "preparing databases"

### ISSUE THREAD

**Issue by fresheneesz** [goatpig/BitcoinArmory#238]
What is armory doing? I thought maybe after 2 years Armory would get easier to use... I downloaded version 0.96-beta-a3d01aa722 and its been "Preparing Databases" with no visible progress on that bar for 30 minutes now. Is there a log I can look at? What's going on here?

**Comment by goatpig** [comment]
Post your logs. They in your datadir.

https://github.com/goatpig/BitcoinArmory/blob/master/cppForSwig/BlockDataManagerConfig.cpp#L28

**Comment by fresheneesz** [comment]
[armorycpplog.txt](https://github.com/goatpig/BitcoinArmory/files/1030382/armorycpplog.txt)
[armorylog.txt](https://github.com/goatpig/BitcoinArmory/files/1030381/armorylog.txt)

I should also mention it says "offline"

**Comment by goatpig** [comment]
Please use pastebin, I don't want to download random files.

**Comment by fresheneesz** [comment]
They're just text files, but ok...

My armorylog.txt: https://pastebin.com/A0WkRaiw

My armorycpplog.txt says:

```
Log file opened at 1495749124: C:\Users\fresheneesz\AppData\Roaming\Armory\armorycpplog.txt
-ERROR - 1495749132: (..\SwigClient.cpp:61) unexpected return value


Log file opened at 1495751218: C:\Users\fresheneesz\AppData\Roaming\Armory\armorycpplog.txt
-ERROR - 1495751220: (..\SwigClient.cpp:61) unexpected return value
```

**Comment by fresheneesz** [comment]
Oh damnit, it needs bitcoin core now. There should be a nice big user-facing message that says "GO DOWNLOAD CORE". I'll do that right now. I suggest keeping this open until a nice error message is implemented. Thanks for the help!

**Comment by goatpig** [comment]
```
2017-05-25 15:27 (ERROR) -- BDM.pyc:275 - setSatoshiDir: directory does not exist: C:\Users\fresheneesz\AppData\Roaming\Bitcoin\
2017-05-25 15:27 (ERROR) -- ArmoryQt.py:1840 - Failed to setup SDM
```

db doesn't know where to look at for your blockchain data.

**Comment by goatpig** [comment]
>  Oh damnit, it needs bitcoin core now. There should be a nice big user-facing message that says "GO DOWNLOAD CORE". I'll do that right now. I suggest keeping this open until a nice error message is implemented. Thanks for the help!

It's implicit with Armory. This stack always required a full node to operate.

**Comment by fresheneesz** [comment]
@goatpig Whether its implicit or not, some people won't RTFM. Wouldn't it be plenty easy to create a little warning popup that says "Armory can't find bitcoin-core"?

**Comment by goatpig** [comment]
Sure, that would improve UX to the extent that it would ease bootstrapping for new comers. At some point it will be dealt with.
