### ISSUE TITLE
tx broadcast time out (send)

### ISSUE THREAD

**Issue by donnyman** [goatpig/BitcoinArmory#239]
I tried sending BTC from my armory wallet but got  tx broadcast time out despite increasing the transaction fee.
Please you can find the logs here https://pastebin.com/p8NzgfPy

Thanks for your support!

**Comment by goatpig** [comment]
This is dbLog.txt, I need to see armorylog.txt as well.

**Comment by donnyman** [comment]
Thanks goatpig for your support.

I downgraded to Armory 0.96 and bitcoin core 0.13.2 and everything seem to work perfectly well! Smiley

Once again thanks!

**Comment by pessisteel** [comment]
Same issue here
[armorylog_20170614_2304.txt](https://github.com/goatpig/BitcoinArmory/files/1076542/armorylog_20170614_2304.txt)

**Comment by goatpig** [comment]
Use the testing builds:

https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.0.3-testing
