### ISSUE TITLE
Problem sending BTC

### ISSUE THREAD

**Issue by pimpsv** [goatpig/BitcoinArmory#247]
[armorylog_20170613_2341.txt](https://github.com/goatpig/BitcoinArmory/files/1072982/armorylog_20170613_2341.txt)

I get the message tx broadcast timed out. What should I do?

I use version 0.96 on a Win10 Laptop. BTC core 14 I think. I refer to the log file. Thanks!

**Comment by goatpig** [comment]
Build the testing branch and run that, otherwise wait for the next RC for 0.96.1

**Comment by pimpsv** [comment]
Still no solution?

**Comment by goatpig** [comment]
The instructions have not changed, try the latest RC.

**Comment by pimpsv** [comment]
Where can I find that?? What does RC mean?

**Comment by pimpsv** [comment]
Goatpig - thanks, it worked using the latest version!
