### ISSUE TITLE
Cannot get a Send payment to go through

### ISSUE THREAD

**Issue by semigh** [goatpig/BitcoinArmory#248]
Have made multiple attempts and increased BC fee. Log file attached.
[armorylog_20170615_0816.txt](https://github.com/goatpig/BitcoinArmory/files/1078082/armorylog_20170615_0816.txt)

**Comment by goatpig** [comment]
Update to this:

https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.0.3-testing
