### ISSUE TITLE
armory updated but transaction timed out

### ISSUE THREAD

**Issue by confuseduser11** [goatpig/BitcoinArmory#251]
[armorylog_20170620_1242.txt](https://github.com/goatpig/BitcoinArmory/files/1086857/armorylog_20170620_1242.txt)

Im having issues sending coins even with using the suggested fee amount.

i have installed the latest client and also deleted the armory database.

I do have a bad net connection today could that be the cause?
log file attached.

**Comment by goatpig** [comment]
Use this:

https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.0.3-testing

**Comment by confuseduser11** [comment]
uninstall old client or install to old directory or just a new install folder?

**Comment by goatpig** [comment]
You can just install over, it's just a bunch of binaries.

**Comment by confuseduser11** [comment]
does the bitcoin client need to be updated?

**Comment by goatpig** [comment]
That's unrelated to the issue.

**Comment by confuseduser11** [comment]
ok thanks i will download that client and give it a shot :)

**Comment by confuseduser11** [comment]
installed the client and on start up it verifies but no progress occurs for preparing databases

**Comment by confuseduser11** [comment]
should i delete the files in the c///roaming folders?

**Comment by goatpig** [comment]
no

**Comment by goatpig** [comment]
post your logs

**Comment by confuseduser11** [comment]
[armorylog_20170620_1340.txt](https://github.com/goatpig/BitcoinArmory/files/1086945/armorylog_20170620_1340.txt)

**Comment by confuseduser11** [comment]
i got that error this morning so i deleted the roaming folder armory db folder and installed the new client on the website.

**Comment by goatpig** [comment]
How old is the db in C:\Users\admin\AppData\Roaming\Armory\databases?

The error suggests you are using a folder with pre 0.95 db files. Consider emptying that folder.

**Comment by confuseduser11** [comment]
i created it this morning based on a previous error so i deleted the folder and it recreated the database files. i will delete the whole folder and we can start fresh

**Comment by goatpig** [comment]
This is an unexpected error, it's possible your logs are getting mashed together. Redo the operation and post the individual log files you can find in C:\Users\admin\AppData\Roaming\Armory\

These would armorylog.txt and dbLog.txt

**Comment by goatpig** [comment]
2017-06-20 13:52:24 (ERROR) -- BDM.pyc:200 - DB error: C:\Users\admin\AppData\Roaming/Bitcoin/blocks is not a valid path

Remove the /blocks at the end of the path.

**Comment by confuseduser11** [comment]
where is that setting because i have set armory to look for bitcoin in a d:/bitcoin folder

**Comment by goatpig** [comment]
pass it as --satoshi-datadir in the command line args, or set it in armoryqt.conf in your datadir. If the file is missing, just create it.

**Comment by confuseduser11** [comment]
i have deleted all the conf files and started again and after a restart it is rebuilding the databases

**Comment by confuseduser11** [comment]
armory seems to be up and running. does each time you restore a wallet from paper backup does it move the coins to a new wallet?

**Comment by goatpig** [comment]
Restoring from a paper backup just recreates the wallet's keys. No coins are moved.

**Comment by confuseduser11** [comment]
so the balance will appear after a little bit?

**Comment by goatpig** [comment]
Once it is done scanning.

**Comment by confuseduser11** [comment]
it seems to be working and i tried to send some bitcoin and i got this message
![capture](https://user-images.githubusercontent.com/29557855/27317805-421bd1c0-55cc-11e7-99a4-6a31ab321e10.PNG)

**Comment by goatpig** [comment]
Means either you PC spec are on the low, that your node is getting overwhelmed by zero conf transactions or that it is connected to very few/laggy nodes.

You should figure out which it is and consider improving your node's health.

**Comment by confuseduser11** [comment]
how do i know which node im connected to and then change it?

**Comment by goatpig** [comment]
Run bitcoin-qt with -disablewallet
