### ISSUE TITLE
Coin Control doesn't let you select a single utxo

### ISSUE THREAD

**Issue by jimmysong** [goatpig/BitcoinArmory#252]
Try selecting a single output for coin control when sending and it will select all outputs.

**Comment by goatpig** [comment]
Which version?

**Comment by jimmysong** [comment]
0.95-beta-eb4d550091

**Comment by goatpig** [comment]
Build testing and try that.

**Comment by jimmysong** [comment]
Will do, can't promise it'll be soon, though.

**Comment by goatpig** [comment]
Try the latest RC if you want to speed things up:

https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.0.3-testing

**Comment by milanroxe** [comment]
you will speed up through the 4 havel block chains
