### ISSUE TITLE
Transfer with Bitcoin Armory - tx broadcast time out

### ISSUE THREAD

**Issue by Armoire** [goatpig/BitcoinArmory#254]
Hello,

I can't perform my BTC transfer to another wallet. I increased the fees as resquested without success , I have always the same answer:

"tx broadcast time out".

You will find here after the log file:

[armorylog_20170628_2337.txt](https://github.com/goatpig/BitcoinArmory/files/1111018/armorylog_20170628_2337.txt)

Do you have any idea for solving this problem? 

Thank you for your support!

**Comment by goatpig** [comment]
Use this:

https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.0.3-testing

**Comment by Armoire** [comment]
Hello,

Thank you for the fast answer.

Unfortunately, the issue is not solved, I have a similar issue with the updated version
[armorylog_20170629_2039.txt](https://github.com/goatpig/BitcoinArmory/files/1113203/armorylog_20170629_2039.txt)
. Here is the corresponding log file

Thank you for the support!

**Comment by goatpig** [comment]
What version of Bitcoin are you using?

**Comment by Armoire** [comment]
v.0.14.2

**Comment by goatpig** [comment]
Are you signing with this version of Armory as well?

**Comment by goatpig** [comment]
Should be fixed here:

https://github.com/goatpig/BitcoinArmory/commit/88d7e78fb6e61a4f176d32ce29abe43f6e00b2d8

**Comment by Armoire** [comment]
Thanks for the support, I 'm going to try something, I will let you inform.

++

**Comment by Armoire** [comment]
Finally, the issue is solved, thanks to your help. Once I had the entire blockchain Bitcoin core downloaded, it worked normally. 

++
