### ISSUE TITLE
armoryd.py references deleted txjsonrpc folder

### ISSUE THREAD

**Issue by STRML** [goatpig/BitcoinArmory#257]
f6312a88b890bea4e6f8b78ab85c51abbb529afd removed the `txjsonrpc` folder, whereas https://github.com/goatpig/BitcoinArmory/blob/98578163debe1df4d62c2f6b338e2c3c23397780/armoryd.py#L104 still references it.

**Comment by goatpig** [comment]
I'm aware of this, this is the result of removing the twisted dependency. I will be moving armoryd to its own repo as a result, since the RPC interface is build on top of twisted.
