### ISSUE TITLE
Armory stuck "Preparing Databases" forever

### ISSUE THREAD

**Issue by fresheneesz** [goatpig/BitcoinArmory#259]
Since Armory isn't giving me any feedback as to what's going on (The little partially green circle spins forever, the Preparing Databases bar is completely empty), I opened up bitcoin core first, then opened armory. Same behavior except now I can see that I've all caught up with the blockchain. Yet Armory still says its offline and just seems stuck. 

My armorylog.txt has a TON of logs that look like this at the end (here's the full thing: https://pastebin.com/8Fps1sPa):

`2017-07-10 19:01 (INFO) -- ArmoryQt.py:4619 - Dashboard switched to "Scanning" mode`

And my armorycpplog.txt has this error:

`-ERROR - 1499735399: (..\SwigClient.cpp:61) unexpected return value`

Any idea what might be going on?

I'm on Armory v0.96-beta-a3d01aa722 (for windows 64 bit)

**Comment by goatpig** [comment]
Build the testing branch.

**Comment by fresheneesz** [comment]
Does the testing branch have a specific fix for this, or do you just want to make sure I'm on the latest?

**Comment by goatpig** [comment]
It has a lot of fixes atop 0.96. Pull tag 0.96.04 and try with that.

**Comment by fresheneesz** [comment]
Ok I'm now running armory v0.96.1-beta-b77932c8e3 . Instead of it saying "preparing databases" forever, it doesn't even get that far. It says "offline" and the "preparing databases" and "scanning transaction history" bars are completely blank and unmoving. 

My blockchain is 99% complete (shown in bitcoin core) and I know for a fact all of my wallet transactions are already downloaded and processed, because I've previously had armory magically work when the blockchain was fully downloaded (tho it didn't work immediately). And yet Armory refuses to show me my wallet balances and addresses. This is incredibly frustrating. Why isn't Armory able to consistently give me access to my wallet? 

I see in my log that I have one error in my most recent run of Armor: 

```
-ERROR - 1501869731: (..\BitcoinP2P.cpp:1037) caught StopBlockingLoop in processDataStackThread
```

Here's an export of my logs: https://pastebin.com/WUE1fvxH

**Comment by fresheneesz** [comment]
After Bitcoin core got to 100%, Armory is still offline and unusable. I restarted armory, same deal - unusable. : (

**Comment by fresheneesz** [comment]
Ok, I went and found my Armory log files and it looks like Armory's "Export Log File..." option in the file menu is NOT exporting the right logs. I had to manually delete the logs and rerun for "Export Log File..." to export the right info. I'll write another issue about that.

Looks like the relevant error is:

```
2017-08-04 12:11:15 (ERROR) -- BDM.pyc:200 - DB error: C:\Users\fresheneesz\AppData\Roaming/Bitcoin/blocks is not a valid path
```

And yes, that's the wrong path. Why is it setting it to that path? My ArmorySettings.txt contains the correct path C:\Bitcoin - so why is it trying to access the wrong (default?) path ^?

**Comment by fresheneesz** [comment]
Also, why does Armory not shut down ArmoryDB.exe when you close ArmoryQT? This means people trying to debug issues like this will likely fail because they don't remember or don't know they need to restart ArmoryDB, assuming that restarting the Armory GUI is all that's needed.

I temporarily worked around this issue by making a symlink from C:\Users\fresheneesz\AppData\Roaming/Bitcoin/ to my actual Bitcoin directory, then restarting Armory QT AND ArmoryDB. 

Honestly, thanks for all the work you do on Armory, but I've just never had a good experience using this software. I'm going to move to electrum. I just can't deal with problems like this every time I want to have access to my bitcoins.

**Comment by Trinitek** [comment]
I've got the same issue, except the `blocks` path is correct. It seems that it's not parsing the directory separators correctly, however. It probably doesn't help that there's a space.
```
BDM.pyc:199 - DB error: C:\Users\Blake Burgess\AppData\Roaming/Bitcoin/blocks is not a valid path
```
