### ISSUE TITLE
after a windows fresh install i cant get armory to connect

### ISSUE THREAD

**Issue by confuseduser11** [goatpig/BitcoinArmory#261]
I have tried the beta version armory_0.96.0.4-testing_win64 and now  armory_0.96_win64

After trying armory is errors and crashes 

attached is my log 
[armorylog.txt](https://github.com/goatpig/BitcoinArmory/files/1144673/armorylog.txt)
[dbLog.txt](https://github.com/goatpig/BitcoinArmory/files/1144675/dbLog.txt)

**Comment by confuseduser11** [comment]
I did a fresh install of armory and bitcoin but left the database folders in the bitcoin folder install and created the folder C:\Users\mctri\AppData\Roaming\Bitcoin and restarted armory and it seems to be recreating the dbfiles....not sure how long this will take

**Comment by goatpig** [comment]
You need help trouble shooting, take this to the forums.
