### ISSUE TITLE
Send Transaction was not accepted by the Satoshi client

### ISSUE THREAD

**Issue by gpellly** [goatpig/BitcoinArmory#264]
While attempting to send all my Bitcoins, it fails with a timeout screen. On checking the transaction link, it says no transaction. The relevant line in the log:
2017-07-16 10:36 (INFO) -- ArmoryQt.py:3094 - Sending Tx, 70771cdc40b81140ff1d4fa47ca28fbd16accb6bf3c06985b246652543ef625e
2017-07-16 10:36 (ERROR) -- ArmoryQt.py:3108 - Transaction was not accepted by the Satoshi client
2017-07-16 10:36 (ERROR) -- ArmoryQt.py:3109 - Raw transaction:
2017-07-16 10:36 (ERROR) -- (PPRINT from ArmoryQt.py:3110)

I've attached the full log.
Thanks for your help.
[armorylog_20170716_1044.txt](https://github.com/goatpig/BitcoinArmory/files/1150744/armorylog_20170716_1044.txt)

**Comment by goatpig** [comment]
Update to the testing builds

**Comment by gpellly** [comment]
I've updated to  v0.96.0.4-testing, and now have a new error:
---------------------------
Transaction Not Accepted
---------------------------
The transaction that you just attempted to broadcast has timed out. <br><br>The RPC interface of your node is disabled, therefor Armory cannot use it to gather more information about the timeout. It is recommended that you enable the RPC and try again.

I also disabled my antivirus (AVG) without success.  I've attached the log.
[armorylog_20170717_1404.txt](https://github.com/goatpig/BitcoinArmory/files/1151592/armorylog_20170717_1404.txt)

Thanks

**Comment by goatpig** [comment]
Enable your node's RPC.

**Comment by gpellly** [comment]
Thanks for that. How do I enable the RPC ?

**Comment by goatpig** [comment]
Create a thread here and ask for help or google it:

https://bitcointalk.org/index.php?board=97.0

The issue page is for technically oriented users with yet to be documented bug reports.
