### ISSUE TITLE
(ERROR) ArmoryUtils.pyc:3747 - Unsupported language  specified. Defaulting to English (en)

### ISSUE THREAD

**Issue by Consort** [goatpig/BitcoinArmory#267]
OS: Windows 10 64x - Creators update
Armory version: 0.96

Hello, 

I've tried with standalone and installation versions and I can read these errors in the log:

```
(ERROR) ArmoryUtils.pyc:3747 - Unsupported language  specified. Defaulting to English (en)
(ERROR) Traceback (most recent call last):
  File "ArmoryQt.py", line 5929, in <module>
  File "ArmoryQt.py", line 244, in __init__
  File "ArmoryQt.py", line 2190, in loadWalletsAndSettings
  File "ArmoryQt.py", line 2196, in loadCppWallets
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 11: ordinal not in range(128)

Traceback (most recent call last):
  File "ArmoryQt.py", line 5929, in <module>
  File "ArmoryQt.py", line 244, in __init__
  File "ArmoryQt.py", line 2190, in loadWalletsAndSettings
  File "ArmoryQt.py", line 2196, in loadCppWallets
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 11: ordinal not in range(128) 
```

Thanks you for your help.

**Comment by goatpig** [comment]
What locale do you use? Did you put comments in your wallet with non ASCII charaters?

**Comment by Consort** [comment]
Thanks for your quick response.

I have "English (United Kingdom)" as locale.

**Comment by goatpig** [comment]
Update to this:

https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.0.4

**Comment by Consort** [comment]
I've already tried this testing version and I have got the same error.

Just out of curiosity: My username in Win, has an "ú", it's my own name. Could be the problem?

Thanks!!

**Comment by goatpig** [comment]
Yes, that is an issue. Please use a different datadir. You can learn how to path for Armory here:

https://btcarmory.com/docs/pathing
