### ISSUE TITLE
Rpc interface 

### ISSUE THREAD

**Issue by moviathan** [goatpig/BitcoinArmory#269]
How do i enable the rpc interface on my node so i can send my bitcoin from this wallet

[armorylog_20170721_1646.txt](https://github.com/goatpig/BitcoinArmory/files/1166734/armorylog_20170721_1646.txt)

**Comment by baselbers** [comment]
Create a file called 'bitcoind.conf' with `server=1` and place it within your Bitcoin data dir.
Start ArmoryDB.exe before you start ArmoryQT.exe and wait for the RPC enabled message.
Let me know if you see the message.
