### ISSUE TITLE
illegal instruction (core dumped) / SyntaxError: invalid syntax in ArmoryQt.py, line 1818 (except Exception, e)

### ISSUE THREAD

**Issue by nimbosa** [goatpig/BitcoinArmory#279]
followup to #275 :

wrong (/local/) folder and icons aside, opening a new issue for continuing errors, not sure if this is related or adjacent:
```
~$ /usr/bin/armory %u
/home/user
Illegal instruction (core dumped)

~$ /usr/lib/armory/ArmoryQt.py %u
/home/user
Illegal instruction (core dumped)
```

and this:
```
>>> %cd /usr/lib/armory
>>> %Run ArmoryQt.py
  File "/usr/lib/armory/ArmoryQt.py", line 1818
    except Exception, e:
                    ^
SyntaxError: invalid syntax

>>> 
```

**Comment by nimbosa** [comment]
will try to build fresh from testing now, this instance was from a fresh install from the [latest release 0.96.1](https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.1) ([armory_0.96.1_amd64.deb](https://github.com/goatpig/BitcoinArmory/releases/download/v0.96.1/armory_0.96.1_amd64.deb))

**Comment by goatpig** [comment]
Fixed the exception typo,  The illegal instruction error means your CPU does not support the ASM optimizations the code was built with. You will have to build yourself.

**Comment by nimbosa** [comment]
Thanks! i was able to build the latest testing branch as of 2017-08-02 17:32:08 (26cd6401245ce6e28c47234f8ec795290d0c103a)

it installs and starts successfully, it recovers old backups and can create new wallets but could not "Export Key Lists" (Step 4: Backup Wallet), instead of expected behaviour, it does nothing, so i opened a new issue: #281
