### ISSUE TITLE
bitcoind fails to stop on exit

### ISSUE THREAD

**Issue by elitak** [goatpig/BitcoinArmory#287]
This is on armory release 0.96.1, paired with bitcoind 0.14.0. I get this when I start, let settle, and try to exit:

    2017-08-05 15:02:34]user@host:~$ armory
    /home/user
    (ERROR) ArmoryUtils.py:3747 - Unsupported language  specified. Defaulting to English (en)         
    /nix/store/xhv8i40xmvnib1ajlccn97pq5iq5byzf-python2.7-bitcoinarmory-0.96.1/lib/armory/armoryengine/Transaction.py:2790: SyntaxWarning: import * only allowed at module level                        

      def PyCreateAndSignTx_old(srcTxOuts, dstAddrsVals):                                             
    (WARNING) SDM.py:403 - Spawning DB with command:ArmoryDB --db-type="DB_FULL" --cookie --satoshi-datadir="/home/user/.bitcoin/" --datadir="/home/user/.armory/" --dbdir="/home/user/.armory/databases"  
    BDM is ready!
    (ERROR) SDM.py:484 - bitcoind failed to shutdown in less than 2 minutes. Terminating.

bitcoind is happily synced to the latest block and should be receptive to a shutdown command; I just don't think it's getting dispatched properly. Something's wrong with the code in that shutdown try block in SDM.py, maybe. I couldn't figure out what.

This bug is not too critical, but is annoying because bitcoind must be manually killed before starting armory up again, or else it complains about the socket being in use.

**Comment by goatpig** [comment]
I have plan to rework a bunch of stuff on this front for the next version (hopefully). Stay tuned.
