### ISSUE TITLE
tx broadcast timed out (send)

### ISSUE THREAD

**Issue by schmelim** [goatpig/BitcoinArmory#289]
Trying to send bitcoin and keep getting the tx broadcast timed out (send) error. Was getting with core 14 and tried 13.2. still not working. Log is attached
[armorylog_20170808_2234.txt](https://github.com/goatpig/BitcoinArmory/files/1210389/armorylog_20170808_2234.txt)

**Comment by schmelim** [comment]
Also, I'm a fairly basic user. Not a tonne of computer knowledge / expertise. Just trying to get bitcoin to easier wallet.

**Comment by goatpig** [comment]
Upgrade to 0.96.1
