### ISSUE TITLE
Building is nearly impossible

### ISSUE THREAD

**Issue by kokx** [goatpig/BitcoinArmory#290]
So, I've been trying to build armory (both the last version and master from the repository). And so far it has failed miserably.

In the basis, there is no `Makefile` currently, thus it is impossible to build from the start. And neither is there a `configure` file to allow this.

I did see several of the standard autotools files (like `configure.ac`). Hence, I just tried running most of the autotools chain. Which then gives a `configure` file that gives the following error:

```
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

This also breaks building for arch linux (see #286 , but that issue has it's own merit as well).

**Comment by goatpig** [comment]
https://btcarmory.com/docs/building/
