### ISSUE TITLE
Armory 0.96 - cannot send BTC

### ISSUE THREAD

**Issue by MerrekSK** [goatpig/BitcoinArmory#292]
I cannot send BTCs using Bitcoin Core v. 0.14.2 and Armory 0.96
[armorylog_20170814_0910.txt](https://github.com/goatpig/BitcoinArmory/files/1221569/armorylog_20170814_0910.txt)

Already reinstalled 5 times over and over again and no improvement. I kept copying old blocks to save time, though. Is this the problem? 

The transaction always gets rejected with 130 satoshi / byte. "Transaction was not accepted by the Satoshi client"

Shall I enclose armorylog.txt as well?

Thanks for your help.

**Comment by goatpig** [comment]
Update to 0.96.1
