### ISSUE TITLE
Cant fund BitPay (tx broadcast timeout)

### ISSUE THREAD

**Issue by BitPayProblem** [goatpig/BitcoinArmory#295]
Everything had been working fins ... recently update too latest versions of BitCoin Core (0.14.2/64bit/Windows 10) and BitCoin Armory (0.96.0.0/64bit/Windows 10)) ... now I always get **tx broadcast timeout** error when I try and fund card ... log attached ... any help appreciated .. 
[armorylog_20170817_1256.txt](https://github.com/goatpig/BitcoinArmory/files/1232035/armorylog_20170817_1256.txt)

also, I now always get a console window for ArmoryDb.exe when I start Armory ... normal ?

**Comment by achow101** [comment]
Use Armory 0.96.1: https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.1

**Comment by BitPayProblem** [comment]
Helped ... console disappeared ... THANKS !

But now I get "The transaction that you just attempted to broadcast has timed out. The RPC interface of your node is disabled, therefore Armory cannot use it to gather ... ". How do I turn on RPC interface debugging ? New log attached ... 
[armorylog_20170817_1324.txt](https://github.com/goatpig/BitcoinArmory/files/1232108/armorylog_20170817_1324.txt)


Thank again ...

**Comment by achow101** [comment]
Find or make a bitcoin.conf file in Bitcoin Core's datadir. Add `server=1` to it.

**Comment by BitPayProblem** [comment]
Thanks again Andrew.

Made requested updates ... opertaions became very unstable .... took many many many runs to get Armory to "come up" ... after db setup/review ... many runs hung .. tried lots of different things (didn't want to bother you again until I had a clean run) ... finally just got one ... after rebuild of db's and scan of trans ...  same results (but took a whole lot longer!) ... new log file attached.
[armorylog_20170818_1539.txt](https://github.com/goatpig/BitcoinArmory/files/1235516/armorylog_20170818_1539.txt)

I appreciate the help (will donate), but I need to get this done ... should I go back to old versions?

Don

**Comment by baselbers** [comment]
#231

**Comment by keithlovett** [comment]
Hey Goatpig. Sorry I haven't got back to you on this but as BTC were doing so well I was glad I didn't withdraw funds,.
I had to reset the timer on my computer today *(via msc)".  Could problems with timer have been an issue? Another thing is my wallets have all been recovered at some point and renamed.
I think I will download entire blockchain onto another computer, create a new wallet, attempt to transfer funds there and see how it goes. I'll keep you informed.
Thanks for all your ongoing & unselfish support goatpig. We will resolve this!

**Comment by BitPayProblem** [comment]
reloaded everything from scratch (latest versions) ... still same error ... TX BROADCAST TIMEOUT ... see attached log file ... ANY HELP APPRECIATED ! regards .....
[armorylog_20170905_1607.txt](https://github.com/goatpig/BitcoinArmory/files/1278739/armorylog_20170905_1607.txt)

**Comment by goatpig** [comment]
It looks like your node is choking on its own. Start BitcoinQt manually and let it full sync then start Armory.

Also, update to 0.96.2, you're using 0.96

**Comment by BitPayProblem** [comment]
As soon as I start BitcoinQt.exe Armory starts up ... found this ... does it help 

(ERROR) ArmoryUtils.pyc:3747 - Unsupported language  specified. Defaulting to English (en)
(WARNING) SDM.pyc:396 - Spawning DB with command:./ArmoryDB.exe --db-type="DB_FULL" --cookie --satoshi-datadir="C:\Users\donlfernandez\AppData\Roaming\Bitcoin\blocks" --datadir="C:\Users\donlfernandez\AppData\Roaming\Armory\" --dbdir="C:\Users\donlfernandez\AppData\Roaming\Armory\databases"
(WARNING) ArmoryQt.py:4057 - Called updateSyncProgress while not sync'ing

**Comment by bull1980** [comment]
plaese help??? can't transfer bitcoins!!
[armorylog_20170908_1633.txt](https://github.com/goatpig/BitcoinArmory/files/1288007/armorylog_20170908_1633.txt)

**Comment by BitPayProblem** [comment]
Bull1980 ... did you find/solve your problem ... I have been struggling with this for several weeks ???

**Comment by BitPayProblem** [comment]
Still struggling with this ... tried everything .. any help appreciated ... log attached ...
[armorylog_20170912_1404.txt](https://github.com/goatpig/BitcoinArmory/files/1296936/armorylog_20170912_1404.txt)

**Comment by goatpig** [comment]
You've been instructed to update. If you're not going to, I'm just going to close this ticket.

**Comment by BitPayProblem** [comment]
I have tried it both ways .. same result ... will do t yet again and send new log file ...

**Comment by goatpig** [comment]
Your logs show you've never use anything newer than 0.96. That's a version from April, and 2 bug fix versions have been out since. I can't help you if you won't update.

**Comment by bull1980** [comment]
sorry for dumb question but on the armory site there is not a newer version?
where we can find a actual version?

**Comment by goatpig** [comment]
On the github page (i.e. here), in the release section...

https://github.com/goatpig/BitcoinArmory/releases

**Comment by bull1980** [comment]
thanks
should I rescan the blockchain again?

**Comment by goatpig** [comment]
Only if you're coming from a version earlier than 0.96

**Comment by BitPayProblem** [comment]
Thank you for the response, but I have to admit that when I read it, I was somewhat/very confused, because I quite clearly remember upgrading Armory to 0.096.2 and doing some testing ... with no luck. I gave some thought to why your research indicated that I had never ran the newest version(s), and then remembered that (after uinstalling both Armory and BTC core) I reinstalled BTC Core (0.14.2) and Armory (0.96.2) and tried to test. I could not get the newly installed sw to run at all ... it just hung everytime I tried to run it. While I will admit that things are somewhat "fuzzy" (I have tried so many things in an effort to resolve this issue with as little of your time as possible), maybe the sw never got far enought to allow me to save a new log file. I appologize for any confusion, and I totally understand your position re: folks who report problems, and don't follow thru your recommendations .. I fully appreciate your work/efforts and don't want to be one of those folks. 

So, I started over and tried it again ... details;

1. Made sure no BTC sw (BTC Core or Armory) were running (I run Armory manually when I want to do something related to BTCs ... i.e., I don't have this sw configured to run in the background ... "system tray" ... Armory is allowed to run/control BTC Core); I used the Windows Task Manager for this step.

2. I rebooted my machine (Windows 10/64 bit) ... just for good measure.

3. I then uninstalled BTC Armory sw using Windows Control Panel ... successfull.

4. I then uninstalled BTC Core sw using Windows Control Panel ... successfull.

5. I then deleted the C:\Users\XXXXXXXXXXX\AppData\Roaming\Armory\databases dir using the file manager ... successfull ... just for good measure and since my trouble started when I upgraded dfrom a very old versions of Armory & BTC Core.

6. I rebooted my machine ... again ... just for good measure.

7. I then downloaded and installed the latest BTC Core sw from the web (bitcoin-0.14.2-win64-setup.exe). When this completed, it gave me an option to "run/open" ... I said OK. The BTC Core sw started and ran for I want to say 30+ min (resyncing to the network and rebuilding databases I assume).

It finally finished (no errors reported) and indicated everything was "good" ... as expected it showed 0 BTC balances/transactions.

8. I then downloaded and installed the latest Armory sw from GitHub (armory_0.96.2_win64.exe). When this completed, it gave me an option to "run/open" ... I said OK. The Armory sw started and ran for A LONG TIME (>5 hours). Looked OK ... three "loading bars" on the dashboard made sense ... and went alng as expected (% completes looked normal, etc.). The only anomoly during this initial run was that while "prepatring databses" or "organizing blockchain" I got a "disconnected" notifictation from BTC Core ... suspected this was OK for now (while Armory was scanning data). When it finally "finished" (dashboard tab bars "done") ... the Armory sw remained "offline" (as expected since BTC Core was disconnected). I let this sit for another hour or so (just to be safe) and then shut Armory down manually (X).

9. I rebooted my machine ... again ... just for good measure.

10. I then manually stated Armory ... somewhere in here I got the message about associating the btc url with Armory ... said yes. Shut Armory down to make sure change took. Restarted Armory ... gave it a few minutes to show connected .. all looked well. I was hopefull.

11. At this point I surfed to my BitPay webpage (via Chrome) ... and tried to "add funds" (receive bcs) ... this webpage displays also display a QR-code/3D-bar code but also includes a button to "start wallet" ... clicking this had worked in the past (transaction dialog box would pop up in Armory). I tried this button with Armory running and not running prior to pudhinh BitPay button ... in neither configuration did Armory appear to be alerted by the url. I don't know how to "manually" send this funds via Armory or I would have tried that.

12. I tied things many many different was over the next few days ... no joy. And yes, I used the Armory settings menue to make sure Armory was assoicated with the btc url and that I was running 0.96.2.

Open wallet button url is bitcoin:XXXXXXXXXXXXXXXXXXXXxBmcd?amount=0.053965&r=https%3A%2F%2Fbitpay.com%2Fi%2XXXXXXXXXXXXXXXXXXXXXXXXXX

13. Just one other note that might be of some help ... sometimes when starting Armory, I initially get a funny looking dashboard ... {"synchronizing network" label is missing ... loading bar is present but doesn't have any shaded portion ... and there are some funny numbers like 23 and 25 and so on to the right of the bar ... many times this would hang and I would never get connected. Sometime it would finish initializing but still not recognize BitPay send request. Sometimes, I would get multiple connect/disconnect notifications during initialization processing.

14. Latest log files attached.

ANY HELP GREATLY APPRECIATED .. EVEN IF IT IS JUST TO ALLOW ME TO MOVE MY BTCs to another sw wallet (Armory or not).

Regards.
[armorylog_20170917_1451.txt](https://github.com/goatpig/BitcoinArmory/files/1309298/armorylog_20170917_1451.txt)

**Comment by goatpig** [comment]
11&12: 
a) copy the bitcoin: url link from your payment page
b) In Armory, pick "Send Bitcoins" in the main lobby (top left button frame)
c) In the "Send" dialog, click the button named: 'Manually Enter "bitcoin:" Link".
d) Paste the link in there and click Done.

13: This is borked progress report from when your node is syncing and the DB is waiting on it to be ready before initializing. Will fix that in the release.

**Comment by BitPayProblem** [comment]
Thanks ... that did it.

Not sure what "borked process report" means ... should I simply wait longer after bringu=ig up Armory before trying future transactions?

Regards.

**Comment by goatpig** [comment]
You have to wait for your node to synchronize with the network before starting Armory.

**Comment by baselbers** [comment]
I've synced bitcoinABC and would like to send my Bitcoin Cash to another wallet outside of Armory. Do I have to create another wallet in Armory and transfer funds to this wallet before sending? I also need to do this for BTC?

**Comment by goatpig** [comment]
Don't hijack the thread.

https://bitcointalk.org/index.php?topic=2070058.0
