### ISSUE TITLE
Transactions not sent

### ISSUE THREAD

**Issue by RobJ1945** [goatpig/BitcoinArmory#296]
Twice now I have tried to send a transaction from my wallet a recipient. Both have "timed out" with the message "possibly because the transaction fee is not enough" I've tried to increase the fee to no avail. Here are the event logs relevant to the attempted transactions. Please let me know what's going wrong. Thank
[armorylog_20170821_0900.txt](https://github.com/goatpig/BitcoinArmory/files/1238165/armorylog_20170821_0900.txt)

**Comment by goatpig** [comment]
Upgrade to 0.96.1

**Comment by RobJ1945** [comment]
Thanks, I'll try that and let you know.

**Comment by RobJ1945** [comment]
Slight problem - where can I find 0.96.1. Download site (https://www.bitcoinarmory.com/download/) only has 96.0 at the moment!

**Comment by goatpig** [comment]
This isn't the official page anymore. Releases are all distributed on the release page of this github repo: 

https://github.com/goatpig/BitcoinArmory/releases

**Comment by RobJ1945** [comment]
Not fixed yet. I  now get and error message about "the orc of your node" - is this in Armory or the receiving address. If in Armory how do I set it?

**Comment by goatpig** [comment]
Post your logs first

**Comment by RobJ1945** [comment]
It looks like a network traffic problem. I'll try again later and, if necessary, raise another issue. Thanks for your help.
