### ISSUE TITLE
Transactions not updating?

### ISSUE THREAD

**Issue by ThatBitcoinGuy** [goatpig/BitcoinArmory#297]
I'm a newish Bitcoin user and just wiped my old PC and restored a BTC Armory wallet on a new one. It has my first transaction - receiving about 0.02 BTC, but I have 2 or three transactions in total, none of which are showing. This has meant I haven't been able to go through with a transaction to purchase a VPN.
[armorylog_20170826_2141.txt](https://github.com/goatpig/BitcoinArmory/files/1253960/armorylog_20170826_2141.txt)

**Comment by tril0byte** [comment]
have you gone to Help and chosen Rescan Balance (and if that doesn't work, the other options below that)?
