### ISSUE TITLE
[0.96.2] BCH transactions not signed (empty scriptSig) while selecting BCH signer

### ISSUE THREAD

**Issue by ixje** [goatpig/BitcoinArmory#298]
I'm following the instructions given by Goatpig at this [bitcointalk thread](https://bitcointalk.org/index.php?topic=2070058.0) but I end up with a rawtx that looks unsigned? I can't tell if this is a bug or not, so I'll start here and if you want we can move the discussion to bitcointalk.org or elsewhere. 

My goal is to simply send the BCH to some exchange and that's it.
 
Let me start by describing my environment and the steps I've taken.
- I'm running a bitcoin-abc node that's fully synced (i start this manually using `bitcoin-qt.exe`)
- Armory is started using the following command:
`armoryqt.exe --datadir="C:\Users\Erik\AppData\Roaming\Armory-abc" --satoshi-datadir="D:\bitcoin"`
- The Armory settings have "Let Armory run Bitcoin Core/bitcoind in the background" unchecked.
- Armory nicely shows my 'BCH' value. (I know this is my actual my BCH value because I moved my BTC to another wallet first. So far so good.)
- The ArmoryQT gui shows 'Amory online' in the Dashboard tab, but shows "Node offline" in the bottom right of the window. I find this odd, as `bitcoin-qt.exe` is running and shows it's connected to the network. Any concerns here?

**Attempt 1 - sending BCH directly from Armory**

1. Select "Send bitcoins"
2. In the new window; enter bitcoin address, check MAX for BTC, uncheck `enable RBF` as mentioned [here](https://bitcointalk.org/index.php?topic=2070058.msg21006674#msg21006674)
3. in the Confirm transaction window; Select BCH signer and press the send button.
**Result**: "Transaction not accepted. Error message: "node is offline, cannot broadcast". 
Ok this message makes sense given my previous indication that the GUI thinks the node is offline, even though I don't understand why it reports that.

**Attempt 2 - sending BCH using a raw TX**
Step 1 + 2 is the same as in Attempt 1 (see above)
Step 3: I first select the BCH signer, then look at the transaction details and press the "Copy Raw Tx(hex)" button.
Step 4: I go to [blockdozer.com/insight/tx/send](blockdozer.com/insight/tx/send) to broadcast the raw transaction. 
**Result**: There I get the error message: `"code":-26,"message":"16: mandatory-script-verify-flag-failed (Operation not valid with the current stack size)"`

With some googling I end up at this [StackExchange](https://bitcoin.stackexchange.com/questions/42516/testnet-mandatory-script-verify-flag-failed-when-doing-op-return) post with the same problem. Their conclusion is that the `scriptSig` key is empty. To confirm I run `bitcoin-cli.exe decoderawtransaction <value>` and indeed all `vin` entries have a `scriptSig` with where the `asm` and `hex` keys have no values.

This is as far as I've gotten. Even if I would solve the issue of the node being reported as offline, then it would probably still fail because the message is not signed. 

So did I miss any steps or is this a bug? Any pointers/help would be appreciated. The sole purpose is getting the coins out and be done with it, nothing else. So if there's a manual step to perform once then that's fine also. 

Thank you in advance.

**Comment by goatpig** [comment]
I don't have time to look at this directly. At first glance you need to setup your node properly, and you do not know how to use offline transactions in Armory. Ask on the forums, this is a benign setup mistake.

https://bitcointalk.org/index.php?board=97.0

**Comment by ixje** [comment]
Thanks a lot, this was all the feedback I needed to figure it out.  It's solved now and successfully broadcasted :)

For anyone that ends up here via google or a search, here's what I eventually did for my case (I had no coldstorage wallet):
- choose "send bitcoins"
- fill in the details and check "create unsigned" at the bottom of the window
- on the next screen press "Copy to clipboard" and then press "continue"
- paste the content into the text field and press "Sign", choose the BCH signer, press "continue"
- press the "Click here for more information about this transaction" (blue text in right bottom corner)
- press "Copy raw tx (Hex)" button and paste the results into e.g. blockdozer.com to broadcast it

**Comment by goatpig** [comment]
Good to hear. You should look at your connectivity issue. Probably a port snafu.

**Comment by ixje** [comment]
To be honest I'm not interested in solving that for the bitcoin-abc client. It's going to be gone soon. Also, the connectivity is working fine for the bitcoin-core. I'm clueless why it differs, but again I'm fine with it only working for core.

**Comment by goatpig** [comment]
Ah. If it's only BCH screwing up, you're fine.
