### ISSUE TITLE
Cant send BTC, and Armory dont run after short time 

### ISSUE THREAD

**Issue by brookerxx** [goatpig/BitcoinArmory#299]
Hello,

now, maybee since twi weeks a have big problems with Armory. In this time i must install 3 times. And now, armory is running, but dont sending BTC. 

Main problems: after short time no connection to bitcoin core 0.14. and now, no sending from BTC 

What is the problem?

Armory say, make a issue with attachment. Here they are. I hope you find a solution.

[armorylog_20170829_2225.txt](https://github.com/goatpig/BitcoinArmory/files/1261642/armorylog_20170829_2225.txt)

Regards

brookerxx

**Comment by goatpig** [comment]
Upgrade to 0.96.1

If that doesn't fix it, ask for help on the forums: 

https://bitcointalk.org/index.php?board=97.0
