### ISSUE TITLE
Cant sent BTC - RPC interface of your note is disable ??

### ISSUE THREAD

**Issue by brookerxx** [goatpig/BitcoinArmory#300]
Hello, now, more trouble. After updating Armory this mistake.

What can i do?

![armory](https://user-images.githubusercontent.com/31454467/29879933-c72317b8-8da6-11e7-9568-46edc3abe128.jpg)

**Comment by goatpig** [comment]
Ask for help setting up Armory over here:

https://bitcointalk.org/index.php?board=97.0

Post your logs as well, and please protect your privacy...
