### ISSUE TITLE
Unable to send bitcoin

### ISSUE THREAD

**Issue by MrT63** [goatpig/BitcoinArmory#302]
Either you click on the send button and nothing happens at all - or I get:

The transaction you just executed failed with the following error message: tx broadcast timed out

Entries appear with zero change, then disappear - altho one remains.  The minimum fee - i set it to exceed ie 0.0035 . Transaction does not show up.  I attach the log
[armorylog_20170902_1138.txt](https://github.com/goatpig/BitcoinArmory/files/1271886/armorylog_20170902_1138.txt)

Thanks for any help.  Am runnn Armory 0.95.1 beta

**Comment by goatpig** [comment]
Use 0.96.2
