### ISSUE TITLE
Setup error.System is Win10 64bit,language is Chinese.

### ISSUE THREAD

**Issue by dujbo** [goatpig/BitcoinArmory#303]
The armyory.exe.log is:
-------------------------------------
(ERROR) ArmoryUtils.pyc:3719 - Unsupported language  specified. Defaulting to English (en)
(ERROR) Traceback (most recent call last):
  File "ArmoryQt.py", line 5975, in <module>
  File "ArmoryQt.py", line 247, in __init__
  File "ArmoryQt.py", line 2209, in loadWalletsAndSettings
  File "ArmoryQt.py", line 2215, in loadCppWallets
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-11: ordinal not in range(128)
-------------------------------------
Wish to you help...

**Comment by goatpig** [comment]
Your pathing, both for the binary and the datadir, has to have only ASCII characters.

**Comment by dujbo** [comment]
Thank you for your answer.
The datadir include window user name(Chinese),but i don't want to change my user name.
How do i change the datadir? or another solution?

**Comment by goatpig** [comment]
https://btcarmory.com/docs/pathing

**Comment by dujbo** [comment]
Thank you very much!
The last question:
Can i build a watching-only wallet by import/input addresses(not watching-only wallet file) into armory?
Thanks.

**Comment by goatpig** [comment]
In the "wallet properties" dialog, there's a menu on the right side that let's you pick "export watching-only copy".

In there you can create a WO wallet file, or copy the WO string
