### ISSUE TITLE
I run armory offline on ubuntu 14.04 32bit,and system show me:"core dumped".

### ISSUE THREAD

**Issue by dujbo** [goatpig/BitcoinArmory#304]
My notebook is IBM T42.The cpu is Intel Pentium M Dothan-400,the RAM is 512MB.
I installed armory on Xubuntu 14.04 32bit through deb file.
When i type "armory" in console,system show me "Illegal Instruction core dumped".
Anybody can help me?
Thanks.

**Comment by goatpig** [comment]
Your CPU is too old for this build, you have to build from source.

**Comment by dujbo** [comment]
Thanks!
