### ISSUE TITLE
missing bitcoin

### ISSUE THREAD

**Issue by bull1980** [goatpig/BitcoinArmory#307]
Hello, prior to the fork I have X BTC in my armory wallet. Because then armory haven,t had a bitcoin cash option, I claim my bitcoin cash with 'BITCOIN ABC' with this totural:https://www.youtube.com/watch?v=XaRWNdRW9kE. 
It worked, and I hade the same amount bitcoin cash as BTC in my armory wallet. 
I send the bitcoin cash from the bitcoin abc wallet to karken.com.
The amount in my armory wallet was normal. A couple of days ago I wanted to send some BTC from wallet to kraken, but couldn't. I asked way, and was told to upgrade to armory 0.96.2, which I did. To my surprise and shock all my BTC where missing. There was a new transaction with the time and bitcoin cash address, when I have send the cash to kraken a 25 days ago.
One other thing - when I have send the bitcoin cash to kraken, it was received with not a problem.
Please if somebody cah help, I would be thankful.

**Comment by goatpig** [comment]
Post on the forums, link your logs, use pastebin.

https://bitcointalk.org/index.php?board=97.0
