### ISSUE TITLE
Armory 0.96 Cannot send due to TX broadcast timed out( Send).  cannot solve pls help

### ISSUE THREAD

**Issue by MrT63** [goatpig/BitcoinArmory#321]
Using Armory 0.96.  Had Bitcore 13.2 - was working then started getting timeouts .  Installed Bitcore 14.1 - didnt work/ then 15.0 which caused Armory to crash.  Uninstalled and installed 14.2.  TX issue came back .  First it said blocks not synced and re-synced over 2 days.

Amory boots up ok tells me ready to 
[armorylog_20170926_1658.txt](https://github.com/goatpig/BitcoinArmory/files/1332434/armorylog_20170926_1658.txt)

**Comment by MrT63** [comment]
[armorylog.txt](https://github.com/goatpig/BitcoinArmory/files/1332466/armorylog.txt)
[ArmorySettings.txt](https://github.com/goatpig/BitcoinArmory/files/1332471/ArmorySettings.txt)

**Comment by MrT63** [comment]
Causing me a right pain as i cant pay people with my coins and i wanted to buy bitmain equipment as they only accept bitcoins now.  Any help appreciated.

**Comment by goatpig** [comment]
Update the software.

**Comment by MrT63** [comment]
Update what software?  There was no later version of Armory that I could find ( 0.96), nor bitcoin core (14.2).  I did as I say try a core 15.0 it just caused Armory to crash and exit non stop?

 

Which software are you referring to sir?

 

 

Tristan Tabori

 

Tel +65 6334 4104

MP +65 9686 1950

**Comment by achow101** [comment]
> Update what software?

Update Armory. The most recent version is 0.96.3 which can be found right here: https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.3. You are getting your software from bitcoinarmory.com; don't do that. bitcoinarmory.com is not Armory's website anymore, use this github repo and btcarmory.com.

**Comment by MrT63** [comment]
Thank you.  Is there a version of Bitcore I should use specifically with this?  Now Armory is preparing databases but it is sending Windows 10 a notification every 2-3 secsonds informing me “ Connected.  Connection to Bitcoin core established”

 

This non stop and repeats indefinitely.

 

Any fix?

 

Thanks

 

Tristan
