### ISSUE TITLE
NixOS build — a lot to clean up

### ISSUE THREAD

**Issue by michalrus** [goatpig/BitcoinArmory#324]
Hey,

to build BitcoinArmory properly on NixOS, we had to some non-trivial changes to `src/`.

Cf. https://github.com/NixOS/nixpkgs/pull/29977/files#diff-ce2b0ed7ddf127a39fb4dd55b6628ef7R39

Would it be possible to move them upstream? I.e. tweak your build process so that, even if you want to include Crypto++, fcgi, lmdb in the repo (which is not the best idea), the build tools would treat them as `-isystem` instead of `-I` (similar for `-l`), and all the `#include <cryptopp/integer.h>` would then be correct?

Thanks,

**Comment by goatpig** [comment]
I have modified all of these libs, which is why they are linked statically.

**Comment by michalrus** [comment]
s/linked statically/copy-pasted into the repo/ =)

But why? What’s the reasoning? Are these modifications useful to the community around those libs? If so, why not push them upstream?

On the other hand, if they’re _not_ useful in those libs, why did you make them in those libs instead of Armory’s code?

**Comment by michalrus** [comment]
If anything, it makes the app much harder to audit. :wink:
