### ISSUE TITLE
0.96.3 Wallet Properties UI Bug

### ISSUE THREAD

**Issue by Saicere** [goatpig/BitcoinArmory#327]
There appears to be a problem with the wallet properties screen in conjunction with the "Receive Bitcoins" button in which all "Used Addresses" revert to being listed as "Unused Addresses" with a Tx Count of 0. I tested this on a couple of different wallets and computers, both running Windows 10 64-bit and connected to Core 0.14.2 nodes, with the same outcome. I specifically encountered this with standard P2PKH addresses, but it might affect other address types as well.

Reproduction: In an online and fully synced Armory instance, using a wallet with any spending history, open "Wallet Properties", then click "Receive Bitcoins", then click "Done".

Result: All open trees will be collapsed. Any addresses that were previously listed as "Used" are now listed as "Unused" with zero transactions.

Closing and reopening the "Wallet Properties" screen does not resolve the display issue. Restarting Armory does however restore it.

**Comment by goatpig** [comment]
Can you try this with 0.96.4 RC1?

**Comment by Saicere** [comment]
Sure. 0.96.4 RC1 seems to have the same issue.

I did some more poking on this, and it doesn't actually seem to matter whether or not you do this from the Wallet Properties screen, or even if you have this window open initially. If you use the Receive Bitcoins button from the main window right after a restart, Wallet Properties will still exhibit this behavior if it is opened afterwards.

I had a peek in the log files, it's not logging anything unusual when this happens.
