### ISSUE TITLE
tx time out issue 

### ISSUE THREAD

**Issue by tjskott01** [goatpig/BitcoinArmory#328]
[armorylog_20171013_0929.txt](https://github.com/goatpig/BitcoinArmory/files/1383327/armorylog_20171013_0929.txt)

I cannot send any transaction without this tx error message.

**Comment by gh0stshell** [comment]
Sill having issues getting your coins out? I did as well and after days of tinkering I came up with a way to get my coins into another wallet without sending from Armory that does not require downloading the blockchain along with taking up so much space building another database and was able to get my coins moved to coinbase. I may be able to help.
