### ISSUE TITLE
ArmoryDB does not quit after app is closed

### ISSUE THREAD

**Issue by elcolie** [goatpig/BitcoinArmory#333]
GNU/Linux Debian Stretch
Armory version: `0.96.3.99` install from `deb`

```bash
sarit     5497  0.0  0.1 247984  4600 tty2     Sl+  16:27   0:00 ArmoryDB --db-type="DB_FULL" --cookie --datadir="/home/sarit/.armory/" --dbdir="/home/sarit/.armory/databases"
```

It prevent `Armory` app from starting up 2nd time

**Comment by dffffffff** [comment]
This is also true for 0.96.3.99-beta on macOS

**Comment by dffffffff** [comment]
Actually ArmoryDB does quit on macOS with 0.96.3.99-beta but it takes roughly a minute on a Macbook Air 6,2.
How you tried waiting it out @elcolie?

**Comment by initCCG** [comment]
Can confirm this is still  issue in 0.96.5 built from source on Debian 9.9, no matter how long waiting for it to finish.
Must kill -s 3 ArmoryDB to restart ArmoryQt.
