### ISSUE TITLE
tarball build: fatal error: ./fcgi/include/fastcgi.h: No such file or directory

### ISSUE THREAD

**Issue by linas** [goatpig/BitcoinArmory#338]
Attempting to compile `BitcoinArmory-0.96.3.99` on Ubuntu 16.04 Xenial, it doesn't build, fails with the error:
```
In file included from ../../cppForSwig/FcgiMessage.cpp:9:0:
../../cppForSwig/FcgiMessage.h:16:36: fatal error: ./fcgi/include/fastcgi.h: No such file or directory
compilation terminated.
Makefile:802: recipe for target 'libCppBlockUtils_la-FcgiMessage.lo' failed
make[2]: *** [libCppBlockUtils_la-FcgiMessage.lo] Error 1
``` 

Google does not offer any reasonable suggestions for where this file can be found; I'm stumped.

**Comment by linas** [comment]
From what I can tell, you forgot to check in the contents of directory `./cppForSwig/fcgi` -- it is completely empty in github.

**Comment by achow101** [comment]
Read the build instructions. It is a git submodule, you need to do `git submodule init` and `git submodule update`.

**Comment by linas** [comment]
This is a build from the tarball, not from git.  There are no submodules in tarballs.

**Comment by droark** [comment]
Long story short, there's a long-standing bug in GitHub that prevents submodules from being included in code from the "Download ZIP" button. You'll have to download from the [Releases](https://github.com/goatpig/BitcoinArmory/releases/) page if you want to download code.
