### ISSUE TITLE
gpg key is not verifiable

### ISSUE THREAD

**Issue by linas** [goatpig/BitcoinArmory#340]
The build instructions state that I can get the pgp key as
```
gpg --recv-keys --keyserver keyserver.ubuntu.com 4922589A
```

but exploring the web of trust shows its not connected to anything: 
```
https://pgp.surfnet.nl/pks/lookup?op=vindex&fingerprint=on&search=0x8c5211764922589a
```
and clicking through the signatures there
```
sig  sig   4D1CC810 2016-04-27 __________ __________ Yuhanon Noble Corcair <fakeaddress@fakeserver.com>
sig  sig   7B1CFEC6 2016-05-24 __________ __________ Yuhanon Noble Corcair <fakename@fakeserver.com>
sig  sig   B0918824 2016-06-06 __________ __________ Seán P. Corcoran <Sean@PCorcoran.com>
sig  sig   F57D3C3A 2016-06-16 __________ __________ Paul Diederich <paul@shinseki.us>
```
indicates that they're not connected to anything.  Crawling around in https://pgp.cs.uu.nl/ I can't find any connections from 4922589A to any well-known landmarks.  This becomes a kind-of security theatre ...

**Comment by goatpig** [comment]
I don't care for WoT constructs, they're about as pointless as the CA infrastructure. 

I migrated the project to autotools to eventually support gitian, which actually improves on the trust model for builds. 

If you can't trust the key, read the source. The signature guarantees the integrity of the source snapshot, and the author. If you cannot trust the author and can't read code, no amount of cryptography will help you there. It's trivial to get dozens upon dozens of notable individuals in this space to sign my key without ever looking at my code. I don't see what value this adds.
