### ISSUE TITLE
fragment id when testing backup doesn't match

### ISSUE THREAD

**Issue by Dr-Nix** [goatpig/BitcoinArmory#342]
I tried the new fragmented backup in v0.96.3. The paper backup gives a (random) fragment ID.
When I test this backup it informs me that it contains a different fragment ID. When the fragments are assembled I receive the original wallet ID. 
So while I guess the backup still works, this is not trust inspiring.

**Comment by goatpig** [comment]
Have you tried this:

https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.3.99

**Comment by Dr-Nix** [comment]
Yup, it's fixed!
