### ISSUE TITLE
tx broadcast timed out (get) error message all day.

### ISSUE THREAD

**Issue by Userrrrname** [goatpig/BitcoinArmory#346]
I have been trying to carry out a transaction all day, but this error message keeps popping up, even after rebuilding and rescanning databases.
I don't really know a lot about it, but it shouldn't be anything to do with my connection, since i have an Ethernet cable plugged in.
Any and all help will be greatly appreciated.
Thanks.
[armorylog_20171027_1722.txt](https://github.com/goatpig/BitcoinArmory/files/1422734/armorylog_20171027_1722.txt)

**Comment by goatpig** [comment]
Update.

**Comment by Userrrrname** [comment]
My Armory is full up to date

**Comment by goatpig** [comment]
https://github.com/goatpig/BitcoinArmory/releases
