### ISSUE TITLE
Best version for MacOS Sierra 10.12.3?

### ISSUE THREAD

**Issue by oirman** [goatpig/BitcoinArmory#347]
JUST FOUND DROARK'S README ON OSX, so will go through that first...

Hey there,

I had some time out issues with 0.93.3 from a low fee, and as I couldn't resend with a higher fee my  coins have been trapped for months.  I have tried various versions of Armory which won't run on my OS.

Can anyone recommend the best version or another way around the low fee/time out issue please?

Thanks

**Comment by droark** [comment]
0.93.3 is beyond ancient. Please use [0.96.4 RC1](https://github.com/goatpig/BitcoinArmory/releases/). Thanks.
