### ISSUE TITLE
Python 3.6+ support or burn in hell

### ISSUE THREAD

**Issue by kamikaze** [goatpig/BitcoinArmory#348]
Python 3.6+ support or burn in hell

**Comment by goatpig** [comment]
That's being worked on but I personally believe that Python is trash so I have it half in me to just dump Python as a whole =)

**Comment by kamikaze** [comment]
We will find you

**Comment by goatpig** [comment]
I shall be waiting

**Comment by fotten333** [comment]
https://www.reddit.com/r/ProgrammerHumor/comments/7mofwg/python_36_support_or_burn_in_hell/

**Comment by AlexStefanov2** [comment]
I wanna be in the repost!

**Comment by survivormon** [comment]
^ same
