### ISSUE TITLE
Minimize or Close UI bug macOS

### ISSUE THREAD

**Issue by dffffffff** [goatpig/BitcoinArmory#350]
System: macOS 10.12.6
Armory: 0.96.3.99-beta

How to reproduce 

Run armory, press the red upper left button to quit the application in the main UI.
On dialogue Minimize or Close "Would you like to minimize Armory to the system tray instead of closing it" select minimize (do not select remember answer).

Result: Armory is minimized to the Dock, however, it is not possible to access it again.
To confirm, right click on armory icon in the Dock. Select "Show all windows" - "No windows available"

Secondly, if you press the red button of the Minimize or Close dialogue, the entire Armory Bitcoin Client is closed. Expected behaviour would be that only the Minimize or Close dialogue is closed and that the user is returned to the main UI.

As a side note, the text should say Dock on macOS, not system tray.

**Comment by droark** [comment]
Thanks for the report. I confirmed that it's a bug. I'll take a look when I can. I suspect this is a Qt 4 library issue. Qt 4 is no longer supported. Depending on the nature, I may be unable to fix the issue beyond forcing Armory to shut down altogether.

**Comment by droark** [comment]
Fixed in #353. As a workaround for now, use the Armory icon in the menu bar.
