### ISSUE TITLE
Missing Transactions / incorrect bitcoin

### ISSUE THREAD

**Issue by Si0r** [goatpig/BitcoinArmory#351]
Hi all

I have just had to do a restore of my wallet using a paper backup and after syncing, the balance is incorrect and transactions are missing.

Any idea on how to sort this?

Cheers si

**Comment by droark** [comment]
What version of Armory are you running? What's your OS?

**Comment by Si0r** [comment]
Hi Mate

I have sorted this now by moving wallets, i was finding armory to much hassle.

Thanks for replying tho.

Cheers si
