### ISSUE TITLE
Convenience request for macOS users

### ISSUE THREAD

**Issue by droark** [goatpig/BitcoinArmory#352]
Hi. I've been going through the documentation recently, and helping some macOS users here & there. A few people have tried to compile Armory and have run into issues. As I sorted those out, I realized that the sha256sum_osx.txt.asc has only the SHA-256 for the macOS binary, and not the source code. Would it be possible to include the source hash in the file too? I know it's in the other file. I just want to have a one-stop-shop for macOS users if possible. (Ideally, there would be only one file, period, but I get that this might not be feasible for now.)

Thanks.

**Comment by goatpig** [comment]
I split the sigs in 2 files because I forgot the OSX package the first time around when I pushed 0.96.4 out. It was not my intention to do so. Are you requesting for a stand OSX sig file from now on?

**Comment by droark** [comment]
Naaaah, I'm fine with them all being together. I just want to make sure I know the intention so that my documentation updates are correct.

**Comment by goatpig** [comment]
My intent is to keep on providing a signed source from now on. The naming pattern is the same previously displayed:

armory_versionnumber_src.tar.gz

**Comment by droark** [comment]
Thanks. I'll close this and do a fixup on my docs.
