### ISSUE TITLE
Need help (Armory).. Tried every which way and checked all FAQs

### ISSUE THREAD

**Issue by Splibio** [goatpig/BitcoinArmory#354]
[armorylog_20171106_1655.txt](https://github.com/goatpig/BitcoinArmory/files/1447911/armorylog_20171106_1655.txt)

Attached log, Armory either crashes or gets a timeout error.. ive checked other tickets and I keep getting the same results.. Please help!

**Comment by goatpig** [comment]
Update

**Comment by Splibio** [comment]
update what?

**Comment by goatpig** [comment]
Armory

**Comment by Splibio** [comment]
its the latest release

**Comment by goatpig** [comment]
https://github.com/goatpig/BitcoinArmory/releases
