### ISSUE TITLE
unable to send bitcoins 

### ISSUE THREAD

**Issue by aramah** [goatpig/BitcoinArmory#359]
please i keep receiving transaction broadcast  failure
[armorylog_20171115_0143.txt](https://github.com/goatpig/BitcoinArmory/files/1473048/armorylog_20171115_0143.txt)

**Comment by gh0stshell** [comment]
Sill having issues getting your coins out? I did as well and after days of tinkering I came up with a way to get my coins into another wallet without sending from Armory that does not require downloading the blockchain along with taking up so much space building another database and was able to get my coins moved to coinbase. I may be able to help.
