### ISSUE TITLE
Add support for sending to BIP173 addresses

### ISSUE THREAD

**Issue by Walter-Bishop** [goatpig/BitcoinArmory#360]
Please add support for sending to [BIP173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki) ("bech32") addresses.

There is a reference implementation here: https://github.com/sipa/bech32/tree/master/ref/python

**Comment by goatpig** [comment]
This is being worked on the dev branch already.

**Comment by mysil2** [comment]
Any plans for the bech32 implementation in dev going into master/RC anytime soon? Or is it in need of more work or testing?

**Comment by goatpig** [comment]
It will be part of 0.97. The addition itself is part of a major change that introduces a new wallet format along with BIP32 support.
