### ISSUE TITLE
P2WPKH Transactions not working with multiple inputs

### ISSUE THREAD

**Issue by s1kx** [goatpig/BitcoinArmory#361]
When trying to spend from multiple P2WPKH inputs at once, Armory silently fails before being able to sign the transaction. Thus right now it's only possible to spend from 1 P2WPKH input per transaction.

```
(WARNING) Transaction.py:1263 - Unexpected nested type for TxIn 16 (Type: 6, len(p2shMap): 3) 
(WARNING) Transaction.py:1263 - Unexpected nested type for TxIn 16 (Type: 6, len(p2shMap): 3) 
(WARNING) Transaction.py:1263 - Unexpected nested type for TxIn 16 (Type: 6, len(p2shMap): 3) 
(WARNING) Transaction.py:1263 - Unexpected nested type for TxIn 16 (Type: 6, len(p2shMap): 3) 
(ERROR) Traceback (most recent call last): 
  File "/opt/armory/ui/TxFrames.py", line 1411, in previewTx 
    txDlg = DlgDispTxInfo(ustx, self.wlt, self.parent(), self.main) 
  File "/opt/armory/qtdialogs.py", line 5261, in __init__ 
    pytx = ustx.getPyTxSignedIfPossible(signer=ustx.signerType) 
  File "/opt/armory/armoryengine/Transaction.py", line 2859, in getPyTxSignedIfPossible 
    if self.evaluateSigningStatus().canBroadcast: 
  File "/opt/armory/armoryengine/Transaction.py", line 2677, in evaluateSigningStatus 
    for ustxi in self.ustxInputs] 
  File "/opt/armory/armoryengine/Transaction.py", line 1863, in evaluateSigningStatus 
    signStatus.allSigned = (signStatus.statusM[-1] in \ 
 IndexError: list index out of range
```

**Comment by goatpig** [comment]
What version are you using?

**Comment by s1kx** [comment]
I'm using `v0.96.3.99`.

The initial warnings (from the `Transaction` constructor) come from `p2shMap` being larger than 2, but I'm not familiar enough with the code yet to dig deeper into how the transaction is processed from there on out...

**Comment by goatpig** [comment]
Does this happen before, during or after the signing process? If signing is involved, do you sign with an offline instance? If so, is it the same version as the instance created the transaction?

**Comment by s1kx** [comment]
I use the same instance where the wallet resides and it happens when I click "Send" in the dialog after filling in the recipient address and amount. The passphrase dialog does not spawn, since the errors that are thrown prevent Armory from even reaching that point. Instead, I'm just stuck at the Transaction dialog.

The same error also occurs when I click "Preview Transaction".

The only way to get past this has been to go into Coin Control and select a single P2WPKH address. Any attempts with n >= 2 P2WPKH inputs have resulted in the errors mentioned above, presumably due to this step preventing the `UnsignedTxInput` from being populated properly:

```
if scrType in CPP_TXOUT_NESTED_SINGLESIG and len(self.p2shMap) == 2:
# ...
elif scrType == CPP_TXOUT_P2WSH:
# ...
else:
            LOGWARN("Unexpected nested type for TxIn %d (Type: %d, len(p2shMap): %d)" % (i, scrType, len(p2shMap))) # modified for debugging
            pass
```

**Comment by goatpig** [comment]
Ok I will investigate, thanks for the bug report.

**Comment by goatpig** [comment]
This commit should fix it:

https://github.com/goatpig/BitcoinArmory/commit/f73c2fbe4afac7932491e16338c3f17af9c95be6

**Comment by s1kx** [comment]
Confirmed, commit fixes the issue. Thanks goatpig!
