### ISSUE TITLE
Minor UI bug macOS

### ISSUE THREAD

**Issue by dffffffff** [goatpig/BitcoinArmory#362]
System: macOS 10.13.1
Armory: 0.96.3.99-beta

Run Armory, open Armory Settings.
Text for Fee and Address Types does not fit in tab.

![screen shot 2017-11-19 at 16 48 34](https://user-images.githubusercontent.com/33299550/32992491-96165aa6-cd4b-11e7-9633-fefe9ee9320b.png)

**Comment by goatpig** [comment]
The joy of Qt4 on OSX...
This may have to wait till Py3/Qt5

**Comment by droark** [comment]
Yeah, there's some sort of Qt4 inconsistency. I don't have that problem myself (exact same setup as the OP). Not much that can be done, AFAIK.
