### ISSUE TITLE
v0.96.4 RC1 on OSX fails

### ISSUE THREAD

**Issue by TheCranston** [goatpig/BitcoinArmory#363]
I'm getting: 

Illegal instruction: 4

on startup
Running on 10.13.1

**Comment by goatpig** [comment]
Your CPU is too old, build from source.

**Comment by TheCranston** [comment]
Really?  It's an Intel quad i7.  iMac model iMac13,2

**Comment by TheCranston** [comment]
Building from source fails with already installed python modules:  six & setuptools

ImportError: No module named six.moves
ImportError: No module named setuptools

$ pip install six
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
$ pip install setuptools
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python

**Comment by goatpig** [comment]
> Really?

Typical error when the code is trying to access special registers your CPU lacks.

>  It's an Intel quad i7. iMac model iMac13,2
Doesn't mean much. iMacs are build on laptop hardware, where they shave silicon off of core to reduce the TDP. Desktop high end 5th gen i7s are 110W and up CPUs. Laptop i7s are in the 20~40W.

> Building from source fails with already installed python modules: six & setuptools

Are you following the instructions in the readme?

https://github.com/goatpig/BitcoinArmory/blob/master/README_OSX.md

**Comment by TheCranston** [comment]
Yup, following the guide, letter for letter.  even rebooted the mac when instructed.  I started with a git clone of the current tree.  Now I'm compiling the source code that was posted in the release section.  It's getting much further.   Package built successfully, but on invocation:

/Applications/Armory.app/Contents/MacOS/Python: can't open file '/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/ArmoryQt.py': [Errno 2] No such file or directory

All that's in that folder is ArmoryMac.so

I'm going to try to build on a fresh OSX install in a VM and see what happens.

**Comment by goatpig** [comment]
If you're using VMs, consider a Ubuntu one. Accessorely, try to get in touch droark on bitcointalk forums or on #bitcoin-armory on IRC@Freenode, he's the one charge of the OSX maintenance.
