### ISSUE TITLE
Generate P2SH-P2WPKH Address in Offline Wallet

### ISSUE THREAD

**Issue by david-yam** [goatpig/BitcoinArmory#364]
I noticed that in the Change Log of v0.96.2, it requires connection to Bitcoin Core 0.13.1 or above in order to create P2SH-P2WPKH addresses.

> Since Segregated Witness has activated on mainnet, Armory now allows for the creation of P2SH nested segwit addresses (P2SH-P2WPKH) provided that the full node that it is connected to signals for segwit support via having the NODE_WITNESS service bit set. Using Bitcoin Core 0.13.1 or later will allow these addresses to be made.

However, if I am in an offline Armory wallet without Bitcoin Core installed, is possible to have an option in settings to allow creation of P2SH-P2WPKH address?

**Comment by goatpig** [comment]
https://github.com/goatpig/BitcoinArmory/blob/testing/changelog.txt#L9
