### ISSUE TITLE
Can't send Bitcoin

### ISSUE THREAD

**Issue by SimonVillage** [goatpig/BitcoinArmory#365]
Using segwit, I am unable to send Bitcoin.
Any workaround to access them?

```
2017-11-23 07:54:42 (INFO) -- TxFrames.pyc:776 - Change address behavior: NewAddr
2017-11-23 07:54:42 (ERROR) -- Traceback (most recent call last):
  File "ui\TxFrames.pyc", line 897, in createTxAndBroadcast
  File "ui\TxFrames.pyc", line 851, in validateInputsGetUSTX
  File "armoryengine\Transaction.pyc", line 2461, in createFromTxOutSelection
  File "armoryengine\Transaction.pyc", line 2368, in createFromPyTx
  File "CppBlockUtils.pyc", line 3015, in getTxByHash
DbErrorMsg: <CppBlockUtils.DbErrorMsg; proxy of <Swig Object of type 'DbErrorMsg *' at 0x00000000061FA2D0> >
```

**Comment by goatpig** [comment]
What version are you using? Is this happening when you craft the transaction? How many inputs?

**Comment by TAiS46** [comment]
Armory is 0.96.3.99 Bitcoin is 0.14.2 (I tried also with 0.15.1)

When I am sending I get a fee warning. I click yes (to send with lower fee) after this nothing happens.
Preview transaction doesn't work as well.

Inputs are about 7

**Comment by TAiS46** [comment]
I tried to create a watch only / unsigned transaction but this also doesn't work. Is there any way that I can access the funds? Importing the priv key to another wallet doesn't work as I get the message `no inputs found` (at least on electrum)

**Comment by goatpig** [comment]
Post armorylog.txt and dbLog.txt

**Comment by juanluperez** [comment]
Same problem using Armory 0.96.3.99 and Bitcoin Core 0.15.1
I cannot send from 2 or more segwit UTXO. No problem if I send from only one segwit UTXO.

**Comment by goatpig** [comment]
juanluperez: that's been fixed in the testing branch.

**Comment by juanluperez** [comment]
Is that branch safe to use or I better wait til you release RC2?

**Comment by goatpig** [comment]
It's just 2 fixes on top of RC1

**Comment by TAiS46** [comment]
The most important out of the armorylog.txt is this
```
2017-11-25 05:53:01 (ERROR) -- Traceback (most recent call last):
  File "ui\TxFrames.pyc", line 897, in createTxAndBroadcast
  File "ui\TxFrames.pyc", line 851, in validateInputsGetUSTX
  File "armoryengine\Transaction.pyc", line 2461, in createFromTxOutSelection
  File "armoryengine\Transaction.pyc", line 2368, in createFromPyTx
  File "CppBlockUtils.pyc", line 3015, in getTxByHash
DbErrorMsg: <CppBlockUtils.DbErrorMsg; proxy of <Swig Object of type 'DbErrorMsg *' at 0x00000000063DDBD0> >```

There are no other errors of important debug information.
db log seems also fine. Few skip block errors but nothing to this problem related.
As juanluperez has deleted his posts, it this fix related to my problem?
When will there be a release of this version?

**Comment by goatpig** [comment]
I need full logs.

**Comment by TAiS46** [comment]
attached the logs

[armorylog.txt](https://github.com/goatpig/BitcoinArmory/files/1503094/armorylog.txt)
[Uploading dbLog.txt…]()

**Comment by goatpig** [comment]
Do you have any Python in you? Can you add a print statement to display the error message attached with the thrown exception?

**Comment by TAiS46** [comment]
add a print statement where? I am using the bin not self compiled. Is there another way without compiling I can do it sure.

**Comment by TAiS46** [comment]
any update to this?

**Comment by gh0stshell** [comment]
Sill having issues getting your coins out? I did as well and after days of tinkering I came up with a way to get my coins into another wallet without sending from Armory that does not require downloading the blockchain along with taking up so much space building another database and was able to get my coins moved to coinbase. I may be able to help.

**Comment by TAiS46** [comment]
What was your solution, yes, my coins are still stuck

**Comment by TAiS46** [comment]
@goatpig can you please tell me how to get my Bitcoins out of it? Or how to get the private key?

**Comment by goatpig** [comment]
To get Armory online, you have to sync Bitcoin Core fully, update Armory to the latest testing version as found on this repo's release page, and delete your Armory's databases folder so as to build your db from scratch. Once that process is completed, Armory will work.

If you want to export your private keys, you can do so from any instance of Armory (offline or otherwise), by using the Backup Center from your wallet's Properties dialog.

**Comment by TAiS46** [comment]
I am using armory_0.96.3.99_osx.tar.gz, deleted the database folder and Bitcoin Core is fully synced. Same error

**Comment by goatpig** [comment]
> I am using armory_0.96.3.99_osx.tar.gz, deleted the database folder and Bitcoin Core is fully synced. Same error

Something is off with your DB. What top block is Armory advertising? Core?

> I need the private key for the legacy address.

The method I described will get you all your private keys.
