### ISSUE TITLE
Bump Fee not working, RBF Control not working, SegWit Fee underestimate

### ISSUE THREAD

**Issue by Thoro** [goatpig/BitcoinArmory#366]
Hey

so seems my coins are stuck because I believed what armory showed as a fee (5 sat/byte)  (non segwit -> to segwit)

Then I wanted to bump via right click -> there I get the error "RuntimeError: invalid asset index"

Then I wanted to send it again via Spend Bitcoins -> There I get Invalid Spend Input

Suggestions?

**Comment by goatpig** [comment]
Let's see armorylog.txt

**Comment by Thoro** [comment]
Woaw u are fast, here you go:

I tried 0.96.3.99 and 0.96 and 0.96.3

[armorylog.txt](https://github.com/goatpig/BitcoinArmory/files/1503977/armorylog.txt)

Last logs are from 0.96.3 - there the Bump fee dialog has the error and the RBF Control dialog doesn't open.

With 0.96.3.99 the RBF Control dialog opens, but afterwards it's impossible to continue. Also the Bump Fee Dialog can't open because of the same error "Invalid Spend value"

[armorylog_96.3.99.txt](https://github.com/goatpig/BitcoinArmory/files/1503979/armorylog_96.3.99.txt)

**Comment by goatpig** [comment]
Build the current state of testing and try with that, should have a fix for this.

**Comment by Thoro** [comment]
Tried it, didn't work.

Same error 

```
Traceback (most recent call last):
  File "ArmoryQt.py", line 3409, in showContextMenuLedger
    self.bumpFee(wltID, txHash)
  File "ArmoryQt.py", line 5934, in bumpFee
    dlgSpend.frame.prefillFromBatch(batchStr)
  File "/root/BitcoinArmory/ui/TxFrames.py", line 1496, in prefillFromBatch
    self.prefill(prefillData)
  File "/root/BitcoinArmory/ui/TxFrames.py", line 1535, in prefill
    self.addOneRecipient(hash160, value, comment, plainText=addrStr)
  File "/root/BitcoinArmory/ui/TxFrames.py", line 336, in addOneRecipient
    self.resolveCoinSelection()
  File "/root/BitcoinArmory/ui/TxFrames.py", line 534, in resolveCoinSelection
    raise e
RuntimeError: Invalid spend value
```


And now the RBF dialog shows:

<img width="588" alt="screen shot 2017-11-26 at 17 41 14" src="https://user-images.githubusercontent.com/554474/33242179-059d8d06-d2d1-11e7-884b-6f354cccf46a.png">

**Comment by goatpig** [comment]
When you try the RBF control dialog, what do you get?

**Comment by Thoro** [comment]
That was displayed when selecting the RBF dialog.

My Process:

"Send Bitcoins" -> "Select Wallet" -> "RBF Control" -> "Accept" -> message from the screenshot is displayed -> "OK" -> "Select same address as the previous transaction" -> "Preview Transaction" -> "Coin selection failed with: Invalid spend value"

**Comment by Thoro** [comment]
yep

**Comment by goatpig** [comment]
ok let me find the issue in the log

**Comment by goatpig** [comment]
actually, can you delete your logs, reproduce the RBF control issue and post the log anew so I'm sure this is the one error?

**Comment by Thoro** [comment]
I think the one I posted should be the error.

I started it with --debug and --logfile and nothing is outputted to the log when the error is displayed. (On stdout) - the logfile isn't beeing created - not sure why.

**Comment by goatpig** [comment]
there is no --debug or --logfile cli arg for armory, the log is made for every instance, and you can't control the verbose level.

**Comment by Thoro** [comment]
ok, but --help displays

```
  --debug               Increase amount of debugging output
  --nologging           Disable all logging
  --netlog              Log networking messages sent and received by Armory
  --logfile=LOGFILE     Specify a non-default location to send logging
                        information
```

anyways, not sure what I could send you to better debug it

**Comment by goatpig** [comment]
ah yeah vestige of an old age i have to cleaned up in a loooong time. dont use those

**Comment by goatpig** [comment]
i just want to look at the python traceback for the error around the rbf control dialog

**Comment by Thoro** [comment]
nothing outputted, but message is the same as when clicking Bump fee in the menu.

**Comment by goatpig** [comment]
since you can build from source, you're gonna be guinea pig for this

**Comment by Thoro** [comment]
yeah :D - please tell me where to put what and I'll try my best

**Comment by goatpig** [comment]
add this line
         LOGERROR("CoinSelection error: %s" % e)

before this line:
https://github.com/goatpig/BitcoinArmory/blob/testing/ui/TxFrames.py#L533

**Comment by Thoro** [comment]
```
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value
```

**Comment by goatpig** [comment]
the RBF control dialog shows the right value though?

**Comment by Thoro** [comment]
Yep, same sending address (checked it in the raw transaction) - and also the correct amount

**Comment by goatpig** [comment]
im adding some verbose on the cpp side. ill push the changes, you'll have to rebuild

**Comment by Thoro** [comment]
kk no problem

**Comment by goatpig** [comment]
go ahead, back in 30min

**Comment by Thoro** [comment]
```
-ERROR - 17:23:39: (DataObject.h:296) returned ErrorType: pageId out of range
-ERROR - 17:23:39: (DataObject.h:296) returned ErrorType: pageId out of range
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
-INFO  - 17:23:43: (TransactionBatch.cpp:57) Processed transaction batch successfully
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value. total: [TOTAL BTC SENT], spendable: 0
(ERROR) TxFrames.py:533 - CoinSelection error: Invalid spend value. total: 2*[TOTAL BTC SENT], spendable: 0
(ERROR) Traceback (most recent call last):
  File "ArmoryQt.py", line 3409, in showContextMenuLedger
    self.bumpFee(wltID, txHash)
  File "ArmoryQt.py", line 5934, in bumpFee
    dlgSpend.frame.prefillFromBatch(batchStr)
  File "/root/BitcoinArmory/ui/TxFrames.py", line 1497, in prefillFromBatch
    self.prefill(prefillData)
  File "/root/BitcoinArmory/ui/TxFrames.py", line 1536, in prefill
    self.addOneRecipient(hash160, value, comment, plainText=addrStr)
  File "/root/BitcoinArmory/ui/TxFrames.py", line 336, in addOneRecipient
    self.resolveCoinSelection()
  File "/root/BitcoinArmory/ui/TxFrames.py", line 535, in resolveCoinSelection
    raise e
RuntimeError: Invalid spend value. total: 2*[TOTAL BTC SENT], spendable: 0
```

For privacy reasons I replaced the large int value with [TOTAL BTC SENT] - hope that's okay for you

**Comment by Thoro** [comment]
From quickly checking the code, and logically thinking (i have had no idea how exaclty rbf works) - I think the problem is, that this transaction would completly empty the wallet, and therefore the fee can't be increased.

Would it work if I send an additional amount to the Input address?

**Comment by goatpig** [comment]
No that particular issue corner case is covered for. The issue here is the code trying to tally the available coins to spend from finds there is 0 value to be had. That shouldn't happen. Gotta investigate some more.

**Comment by goatpig** [comment]
Before this line:

https://github.com/goatpig/BitcoinArmory/blob/testing/ui/TxFrames.py#L527

Add the following LoC:

            LOGWARN("customUtxoList size: %d" % len(self.customUtxoList))

**Comment by goatpig** [comment]
Out of curiosity, did you cycle Armory between the time you broadcasted the tx and the time your tried to RBF it?

**Comment by Thoro** [comment]
Ok, sorry, think I screwed up before with the log - it was from "Bump fee""

Here is the new log from Send Bitcoins - RBF control

```
(ERROR) TxFrames.py:534 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(ERROR) TxFrames.py:534 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(ERROR) TxFrames.py:534 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(ERROR) TxFrames.py:534 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(WARNING) TxFrames.py:527 - customUtxoList size: 1
(ERROR) TxFrames.py:534 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(WARNING) TxFrames.py:527 - customUtxoList size: 1
(ERROR) TxFrames.py:534 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(WARNING) TxFrames.py:527 - customUtxoList size: 1
(ERROR) TxFrames.py:534 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
(WARNING) TxFrames.py:527 - customUtxoList size: 1
(ERROR) TxFrames.py:534 - CoinSelection error: Invalid spend value. total: 0, spendable: 0
```

**Comment by Thoro** [comment]
@goatpig Yep pretty sure I did. Because somehow the block count wasn't updating even though bitcoind had in the log that the tip changed.

**Comment by goatpig** [comment]
So the issue is the RBF output is botched somewhere.

Before this line:

https://github.com/goatpig/BitcoinArmory/blob/testing/armoryengine/PyBtcWallet.py#L515

add:

LOGWARN("cpputxo val: %d" % utxos[i].getValue())

Try RBF control and see if this added line reports 0 values.

**Comment by Thoro** [comment]
Not 0 - it's the full btc value

**Comment by goatpig** [comment]
that's encouraging. it means the DB isn't corrupt but instead the some of the utxo data gets mangled in the between getting the utxo and before it makes it to the coin selection dialog.

**Comment by goatpig** [comment]
After this line:
https://github.com/goatpig/BitcoinArmory/blob/testing/ui/WalletFrames.py#L295

add these 2 lines:

      for utxo in self.customUtxoList:
         LOGWARN("custom list utxo val: %d" % utxo.getValue())

Be sure to respect the indentation (I'm guessing you know Python)

Then RBF control again. Are the values valid?

**Comment by Thoro** [comment]
Not perfect, but good enough.

Same value as in cpputxo

**Comment by goatpig** [comment]
hmm. need to be away for 30min, will you be available then?

**Comment by Thoro** [comment]
probably still 2:30 h - I will try to output something in the CPP code.

For me everything looks good until it calls "self.coinSelection.processCustomUtxoList"

Where it somehow says that spendableBalance_ < total

I would assume for RBF we do have a spenableBalance of the full amount - right?

**Comment by Thoro** [comment]
Okay, so I uncommented the spendable Check, which makes the dialog usable, but I'm not sure if afterwards everything will run through correctly.

When viewing the transaction now, the log spits out:

```
-ERROR - 18:50:53: (DataObject.h:296) returned ErrorType: ser/deser type error:
expected type id: 4
got type id: 32 instead
```

**Comment by Thoro** [comment]
Okay broadcasted it and it looks like it worked - interesting!

So somehow the spendable Amount is not calculated correctly, because the recipients are not correctly popuplated, and therefore the whole process fails.

**Comment by goatpig** [comment]
I've found the issue, The spendable balance is never updated internally but the coin selection object is recycled in between calls. Will push a fix. You'll have to 
git stash
git pull

then make

**Comment by Thoro** [comment]
will try to validate

**Comment by goatpig** [comment]
Ah I understand the issue even further. The CoinSelection instance is seeded with the wallet's current spendable balance. If the wallet is low or emtpy, it will be seeded with a value that's below the potential RBF value, hence the bug.

**Comment by goatpig** [comment]
pushed the fix. pulled back the privacy leaking verbose too.

**Comment by goatpig** [comment]
https://github.com/goatpig/BitcoinArmory/commit/554816d691bfc5af7f31fbf6088fab80d5768276

**Comment by Thoro** [comment]
can confirm that the dialog works now.

But the dialog from above is still displayed.

The Bump Fee dialog from transactions is still broken and failing with the Invalid spend value (guess it's the same root cause)

**Comment by goatpig** [comment]
> But the dialog from above is still displayed.

The RBF failure message box? I'm working on that atm.

> The Bump Fee dialog from transactions is still broken and failing with the Invalid spend value (guess it's the same root cause)

Now that I know how to reproduce I'll go over it

**Comment by goatpig** [comment]
Fixed the message box issue

**Comment by goatpig** [comment]
bumping from the lobby ledger should be fixed now

**Comment by Thoro** [comment]
Confirmed working, guess we can mark as done!
