### ISSUE TITLE
Tx time outs

### ISSUE THREAD

**Issue by destractions** [goatpig/BitcoinArmory#367]
Amory says that it is connected in green and my wallet has spendable funds. If I try and send funds it always displays the tx timed out, not enough fees error. Ive tried several fees up to .002 with the same results. Any ideas? 
[armorylog_20171126_1616.txt](https://github.com/goatpig/BitcoinArmory/files/1504371/armorylog_20171126_1616.txt)

**Comment by goatpig** [comment]
You're using an old version, update.

**Comment by destractions** [comment]
armory version .96 and core .15.1 are the latest I can find. Am I missing something?

**Comment by goatpig** [comment]
https://github.com/goatpig/BitcoinArmory/releases

**Comment by destractions** [comment]
installed 96.3 but when i loaded it up it kept connecting and dropping with core like a usb device was being unplugged and replugged in making a ding sound over and over again. now it wont load at all crashing in the splash screen. reinstalling 96 works but no longer connects. Im beyond frustrated and have a substantial amount of coin in a back up wallet im trying to extricate. any help starting from scratch would be appreciated

**Comment by goatpig** [comment]
Install 0.96.4 RC1

**Comment by destractions** [comment]
I did but it just crashes on the splash screen with the circle of death. Is there a way to sweep the private keys out of the wallet instead of loading armory? I can see them all in the export feature. Between armory and core not connecting im losing my mind.

**Comment by goatpig** [comment]
Delete your logs, start Armory and post the fresh logs anew.

**Comment by destractions** [comment]
[armorylog_20171127_0711.txt](https://github.com/goatpig/BitcoinArmory/files/1506346/armorylog_20171127_0711.txt)

**Comment by destractions** [comment]
Sorry Im lost and dont know where to find that.

**Comment by goatpig** [comment]
C:\Users\Des\AppData\Roaming\Armory\

**Comment by destractions** [comment]
[dbLog.txt](https://github.com/goatpig/BitcoinArmory/files/1506449/dbLog.txt)

**Comment by destractions** [comment]
It's bitcoin QT I can't get to sync at all. No peers 0% progress over the 2 days. Tried reinstalling a bunch to no avail.

**Comment by goatpig** [comment]
Get some help from Core then.
