### ISSUE TITLE
tx broadcast timed out (send)

### ISSUE THREAD

**Issue by drich1** [goatpig/BitcoinArmory#368]
I got error message when I try to send bitcoins from Armory.  Please find the log file as per attached.

[armorylog_20171127_1523.txt](https://github.com/goatpig/BitcoinArmory/files/1504988/armorylog_20171127_1523.txt)

**Comment by gh0stshell** [comment]
Sill having issues getting your coins out? I did as well and after days of tinkering I came up with a way to get my coins into another wallet without sending from Armory that does not require downloading the blockchain along with taking up so much space building another database and was able to get my coins moved to coinbase. I may be able to help.
