### ISSUE TITLE
Weird problems with viewing transactions

### ISSUE THREAD

**Issue by Rombobeorn** [goatpig/BitcoinArmory#37]
I was moving some bitcoin wallets to another computer with a bigger disk. I installed Armory 0.94.1 on the destination computer. I figured I'd take this opportunity to try restoring from a paper backup, just to see it work, so I transferred one wallet by generating a single-sheet backup on the origin computer and typing it into the destination computer. There was also one watching-only wallet, which I transferred by copying the wallet file. After the destination Armory had synced with the blockchain I entered some comments on the restored wallet and the transactions.

The first sign of trouble came when I clicked "View Details" and got the message "The transaction you requested be displayed does not exist in Armory's database. This is unusual...". There was also one case of two different transactions that seemed to be linked such that any comment I wrote on one was displayed identically on both of them.

After I restarted Armory only the watching-only wallet was displayed. There was no trace of the restored wallet or its transactions in the GUI. I thought the restoration from the paper backup had gone wrong. I found the Wallet Recovery Tool, pointed it at the wallet file of the restored wallet, and chose "Full Recovery". The recovery log is attached.

After another restart both wallets were displayed again, but the recovered one seemed to still be corrupted. Some of the comments I had entered were gone, some transactions weren't found in Armory's database and some had "Unknown Input" instead of a sending address.

I thought Armory might still be reading the original restored wallet, so I tried moving that file and its backup.wallet aside, and renaming the recovered one and its backup.wallet to the original filenames. It didn't help.

Then I moved all versions of the restored wallet aside and copied the original wallet file from the origin computer. Even that one had the same problem: Some transactions weren't found in Armory's database and some had "Unknown Input" instead of a sending address.

So maybe this isn't a problem with restoring from paper backups after all, but rather a problem with displaying a wallet in Armory 0.94.1.

I downgraded to Armory 0.93.1, the version I had on the origin computer. Now comments are displayed correctly, and I can view details of all transactions, but for many received transactions the sending address is displayed as "Non-Standard:" followed by an address that begins with a 3. Those occur in both wallets, and they're all the same non-standard address. They should be different normal Bitcoin addresses beginning with a 1.

I never noticed this "non-standard" thing in Armory 0.93.1 before, but I may not have looked so closely at the sending addresses.

[armory_NG47Z975_RECOVERED.wallet.log.txt](https://github.com/goatpig/BitcoinArmory/files/244171/armory_NG47Z975_RECOVERED.wallet.log.txt)

**Comment by goatpig** [comment]
Tx details issue is explained here:

https://bitcointalk.org/index.php?topic=1385530.msg14111584#msg14111584

---

Wallet displaying:

Make sure to either mark the wallets as yours or select All Wallets in the combo box at the bottom left of the transaction ledger in the lobby.

---

Comment duplicates: If you set a comment in a transaction ledger (like the main lobby ledger), that comment will be attached to the tx ledger. If you set it on an address ledger (like the in wallet properties dialog), that comment will be attached to the address, i.e. it will be displayed for every transaction that hit the particular address.

--- 

Wallet recovery log:

The errors are benign. I added these comments in the report for my own debugging purposes (and unit testing). Your wallet has no issues.
