### ISSUE TITLE
tx broadcast timed out

### ISSUE THREAD

**Issue by tdebont** [goatpig/BitcoinArmory#370]
I got error message when I try to send bitcoins from Armory. Please find the log file as per attached.
[armorylog_20171128_0853.txt](https://github.com/goatpig/BitcoinArmory/files/1508876/armorylog_20171128_0853.txt)

I already re-installed armory and the blockchain with no succes, I also tried to sent it with higer fees.

**Comment by gh0stshell** [comment]
Sill having issues getting your coins out? I did as well and after days of tinkering I came up with a way to get my coins into another wallet without sending from Armory that does not require downloading the blockchain along with taking up so much space building another database and was able to get my coins moved to coinbase. I may be able to help.
