### ISSUE TITLE
What version of Ubuntu is 0.96 built for?

### ISSUE THREAD

**Issue by kfiresmith** [goatpig/BitcoinArmory#372]
I was pretty sure if the latest Ubuntu LTS wasn't going to work with the newest version of Armory out of the box, that it'd be because LTS was too old, not too new, but on an out of the box installation, it appears that Ubuntu 16.04 LTS is somehow too new for 0.96.3 (Sept 2017?!):

`armory: Depends: python (>= 2.6) but 2.7.11-1 is installed
        Depends: python-qt4 but it is not installed
        Depends: python-psutil but it is not installed
        Depends: libc6 (>= 2.15) but 2.23-0ubuntu9 is installed
        Depends: libgcc1 (>= 1:3.0) but 1:6.0.1-0ubuntu1 is installed
        Depends: libstdc++6 (>= 5.2) but 5.4.0-6ubuntu1~16.04.5 is installed
`

**Comment by kfiresmith** [comment]
Nevermind.  I'm an RPM guy who forgot how to use Debian.  (short answer go install gdebi to easily install a local deb with dependency resolution...)

**Comment by goatpig** [comment]
For info, I build on 16.04

**Comment by goatpig** [comment]
There is also a "fail safe" build done one Wheezy with ASM optimizations turned off.
