### ISSUE TITLE
txn mempool conflict. cant send bitcoins 

### ISSUE THREAD

**Issue by cmill01** [goatpig/BitcoinArmory#375]
When i go to send coins, this is the message i get. ive tried upping the tx, but nothing seems to help

[latestlog.txt](https://github.com/goatpig/BitcoinArmory/files/1526002/latestlog.txt)

**Comment by goatpig** [comment]
This error means you are trying to spend an output that is already being spent by another ZC. Did you try to double spend something?

**Comment by cmill01** [comment]
No,  don't even know how to double spend.
