### ISSUE TITLE
tx broadcast timed out

### ISSUE THREAD

**Issue by mocdaniel** [goatpig/BitcoinArmory#376]
Please see the log for further details, I tried rebooting, rebuilding the database and restarting Armory several times, outgoing transactions keep timing out. 

BitcoinCore version is v0.15.1
Armory version is 0.96

[armorylog_20171204_1456.txt](https://github.com/goatpig/BitcoinArmory/files/1527323/armorylog_20171204_1456.txt)

**Comment by goatpig** [comment]
Update Armory
