### ISSUE TITLE
no Win32 release with multi-signature transaction support (i.e. 0.92.3 or later)

### ISSUE THREAD

**Issue by regosen** [goatpig/BitcoinArmory#379]
Many of us followed Armory's recommendations to store our offline wallet on an old laptop.  Those of us who used a 32-bit windows laptop are now stuck with this message when trying to send from a new online client:

![screen shot 2017-11-30 at 9 21 52 am](https://user-images.githubusercontent.com/4589394/33674765-4e87702c-da65-11e7-82ba-e04f4e2b02bd.png)

The problem is https://github.com/goatpig/BitcoinArmory/releases contains no Win32 installers, and the old etothepi repository has no installers at all.  In order to build it myself I need a copy of Visual Studio 2012, which I can't get without a Microsoft subscription and probably an online PC. (I've since moved away from Windows PCs, save for the laptop I'm keeping offline.)

If you provided just one Win32 release (0.92.3, or anything with multi-signature transaction support), we could update our offline laptops and start trading again.  Thank you!

**Comment by goatpig** [comment]
There aren't any. My last attempt at 32bit Windows build was a failure. I just takes too much time to do this stuff. And there wouldn't be XP support anyways. 

Old laptops are fine, but use Debian like distros on them, like Ubuntu.
