### ISSUE TITLE
Please change the version number on bitcoinarmory.com

### ISSUE THREAD

**Issue by yurivict** [goatpig/BitcoinArmory#38]
It is still showing 0.93 there.

**Comment by achow101** [comment]
The current developer (goatpig), does not control bitcoinarmory.com. That website is no longer the official site for armory.

**Comment by yurivict** [comment]
On 05/04/2016 11:48, Andrew C wrote:
> The current developer (goatpig), does not control bitcoinarmory.com. 
> That website is no longer the official site for armory.

This is the problem, because the previous developer said that goatpig is 
a new owner of armory. How come he didn't pass control over the website?

I see that Arch switched to goatpig branch. I will check if major rpms 
and debs also switched, then I will update FreeBSD too.

Thanks,
Yuri

**Comment by achow101** [comment]
No, ownership did not change. All that changed was that all of the other developers at ATI stopped working on Armory and goatpig simply continued to work on it. Nothing was given or transferred except the source code that already existed.

**Comment by goatpig** [comment]
etotheipi does not have the right to give me that domain, it belongs to Armory Technologies Inc. This repo is forked off etotheipi's BitcoinArmory original repo. What you see on bitcoinarmory.com reflects the state of etotheipi's repo, to the best of my knowledge.

I own the code changes to my fork and release them under the MIT license (as opposed to AGPL v3 on the original repo). I post my binaries on the release page of this repo.

**Comment by bartromgens** [comment]
@goatpig Is there a central place where I should go to get information about goatpig/BitcoinArmory? 
I see no links in the readme to any docs or places (website, mailing list, etc..) to read or discuss about this project. Or is GitHub the central place and should I use tickets for user and dev questions? 

Am I missing something or might it be a good idea to provide some direction to interested people, both users and developers?

**Comment by achow101** [comment]
You can use the issues page or the armory sub-forum 
https://bitcointalk.org/index.php?board=97.0. As of now, there is no 
official armory website.

**Comment by kibou** [comment]
Hi,

Armory in Ubuntu remains version 93.

Do you plan to update it here as well?

Thanks.

**Comment by achow101** [comment]
@kibou What ubuntu version? The official release page has all of the releases, including the latest for ubuntu.

**Comment by kibou** [comment]
14.04

I try upgrading from Armory GUI but it says it is already updated and
displays version 93, not 94.

**Comment by achow101** [comment]
The server where Armory got those announcements is not in the control of goatpig nor is the server working anymore. We removed the announcement system for 0.94+

**Comment by goatpig** [comment]
@bartromgens 

All discussions in the ATI era took place on the Armory sub forum at bitcointalk. That is still in place. Difference is, I accept PRs and post binaries on the repo's release page, so bug discussion through the GitHub issue system are welcomed as well.

**Comment by bartromgens** [comment]
@goatpig, thanks for the answer. 

If you want people to find and use this new version (this fork), and maybe attract other developers, it might help to create a simple project website that has some basic information and links to important sources (bitcointalk, github, etc). Maybe even change/modify/extent the name. But I don't know the relation with etotheipi/BitcoinArmory.

But this may not be what you want with this project. Is there a place where I can read about your plans for goatpig/BitcoinArmory? Without going through long threads on bitcointalk. 

Just trying to help make this project public and transparent because I really like what you are doing! Also willing to help if you can tell me where you need help.

**Comment by goatpig** [comment]
Here is Alan's last post:

https://bitcointalk.org/index.php?topic=1351792.0

And the follow up:

https://bitcointalk.org/index.php?topic=1351924.0

If you want to contribute, create a ticket here or a thread on btctalk and announce what you will be working on so people can coordinate. Then submit PRs and we'll take it from there.
