### ISSUE TITLE
insufficient fee error

### ISSUE THREAD

**Issue by Earth4Garret** [goatpig/BitcoinArmory#381]
On sending coins I am given the message 'insufficient fee'.

Attached is the logs.
[armorylog_20171206_1427.txt](https://github.com/goatpig/BitcoinArmory/files/1536616/armorylog_20171206_1427.txt)

**Comment by gh0stshell** [comment]
Sill having issues getting your coins out? I did as well and after days of tinkering I came up with a way to get my coins into another wallet without sending from Armory that does not require downloading the blockchain along with taking up so much space building another database and was able to get my coins moved to coinbase. I may be able to help.
