### ISSUE TITLE
Transactions timeout

### ISSUE THREAD

**Issue by cjenkin005** [goatpig/BitcoinArmory#382]
No matter what I attach as a fee, transaction continuously times out.
[armorylog_20171207_0910.txt](https://github.com/goatpig/BitcoinArmory/files/1539964/armorylog_20171207_0910.txt)

**Comment by gh0stshell** [comment]
Sill having issues getting your coins out? I did as well and after days of tinkering I came up with a way to get my coins into another wallet without sending from Armory that does not require downloading the blockchain along with taking up so much space building another database and was able to get my coins moved to coinbase. I may be able to help.
