### ISSUE TITLE
txn-mempool-conflict error message every time I send coin

### ISSUE THREAD

**Issue by shaztastic** [goatpig/BitcoinArmory#384]
I was able to send it but has yet to confirm so I figured fee wasn't high enough so I sent the bitcoin again with an updated fee but now I am getting the TXN-Mempool-conflict error. I've attached my log, hopefully you guys are able to help. 

Thanks! 
[armorylog_20171208_0143.txt](https://github.com/goatpig/BitcoinArmory/files/1542011/armorylog_20171208_0143.txt)

**Comment by gh0stshell** [comment]
Sill having issues getting your coins out? I did as well and after days of tinkering I came up with a way to get my coins into another wallet without sending from Armory that does not require downloading the blockchain along with taking up so much space building another database and was able to get my coins moved to coinbase. I may be able to help.

**Comment by shaztastic** [comment]
how?
