### ISSUE TITLE
Feature Request: Trezor support

### ISSUE THREAD

**Issue by yonderblue** [goatpig/BitcoinArmory#386]

**Comment by gaillard** [comment]
Bad idea or something?

**Comment by goatpig** [comment]
It's there on the list since trezor became a thing, first need to finalize BIP32 support and a whole bunch of other stuff

**Comment by gaillard** [comment]
"the list" ?

**Comment by achow101** [comment]
> "the list" ? Do you mean you have it in a roadmap somewhere?

In a figurative sense, as in the phrase "it's on the list". This means that there is effectively a list (mostly mental) of things that we want to get done at some point. Said list is not published nor is it likely that an actual roadmap with dates and version numbers be published.

Trezor support is something that I was working on, but then stopped as we need to support BIP 32 before any hardware wallet can be supported.

**Comment by goatpig** [comment]
There are lots of prerequisite for hardware wallet support, some actual requirements, other desirable changes in code/model. So it's not a simple matter of giving an ETA, but there is a commitment to get Armory to a point where it can easily on board hardware wallet support.

**Comment by gaillard** [comment]
Sounds good, but for those looking to track the progress shouldn't the issue stay open if it is desired?

**Comment by goatpig** [comment]
Feel free, but don't expect me to report anything anywhere.

**Comment by aussiehash** [comment]
Any update ? PSBT ?

Thanks

**Comment by goatpig** [comment]
BIP32 and BIP44 are supported so the next version can provide this, most of the effort would be in the GUI and onboarding the API. This is probably something for 0.97.1-2, not 0.97.
