### ISSUE TITLE
Unable to create unsigned TX (macOS)

### ISSUE THREAD

**Issue by dffffffff** [goatpig/BitcoinArmory#389]
Macbook Air 6,2
macOS 10.13.2 (17C88)
Armory 0.96.3.99.-beta

Unable to create an unsigned TX

I've never had any problems with this before but after going through the usual steps, with the only differentiating behaviour being i got prompted because i  reused an old receiving address the dialogue window shuts down when i click continue. After a couple of tries Armory did manage to output a string with an unsigned TX that the corresponding cold wallet does not accept, sign option is greyed out.

A crash log was created during these attempts.

[ArmoryDB_2017-12-11-162759_.txt](https://github.com/goatpig/BitcoinArmory/files/1548445/ArmoryDB_2017-12-11-162759_.txt)

**Comment by dffffffff** [comment]
Apologies, i was using the wrong instance of Armory. This is not a bug.

**Comment by dffffffff** [comment]
At first i thought this was related to https://github.com/goatpig/BitcoinArmory/issues/391
But the problem persisted even after i deleted the database folder. As noted above, no issues making offline TX until the prompt warning about reused addresses came up, and now it's not possible to create them anymore.

**Comment by droark** [comment]
Hello. Like #391, I'm unable to reproduce this issue. Can you also report what's happening at the terminal?

Also, when posting logs, please use Pastebin, and please upload the regular Armory log unless ArmoryDB is what's crashing. Are you saying that ArmoryDB is what's crashing when you go through these steps?

**Comment by dffffffff** [comment]
Hi Droark, 

I tried to replicate the environment i had in Armory when i encountered the problem but this time around Armory is not showing the same prompt warning on reusing the same receiving address.

I found this in /Library/Logs/DiagnosticsReports from around the same time i was experiencing the problem. Not sure if it it helps, if it doesnt feel free to close the issue.

https://pastebin.com/5FU6jP1Y

**Comment by droark** [comment]
Hi. The diagnostics report didn't help. Thanks for trying, though. I'll try again to reproduce the issue. To be honest, Qt4 (the library I mentioned elsewhere that's no longer supported) has always been kinda touchy on Macs. It can get confused when various windows pop up or get nested. But, who knows.

If you can reproduce this, can you show what Armory says at the terminal? That would help a lot.

**Comment by dffffffff** [comment]
I'll do that! Too bad i didn't know about that debug option when it occurred. Anyway, closing this and will reopen if i can reproduce at a later time.
