### ISSUE TITLE
ArmoryDB crashes during restored wallet scan (macOS)

### ISSUE THREAD

**Issue by dffffffff** [goatpig/BitcoinArmory#391]
Macbook Air 6,2
macOS 10.13.2 (17C88)
Armory 0.96.3.99.-beta

Steps taken
Restored a wallet from a paper back up, during the scan of the restored wallet ArmoryDB crashed at 98%
logs attached
[ArmoryDB_2017-12-11-171234_.txt](https://github.com/goatpig/BitcoinArmory/files/1548517/ArmoryDB_2017-12-11-171234_.txt)

restarting the client and having it re-scan yields the same result.

**Comment by dffffffff** [comment]
Deleting the database folder and rebuilding it solves this issue.

**Comment by droark** [comment]
Thanks for reporting that all's well. :) Would you mind closing out this issue?
