### ISSUE TITLE
0.96.3.99 build breaks on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [goatpig/BitcoinArmory#392]
I would like to resurrect the armory port on FreeBSD.

Now its build breaks. confidure leaves HAVE_FILENO_PROTO undefined. It is supposed to test for fileno, but configure log doesn't have "checking for a fileno() prototype in stdio.h" message at all.

**Comment by goatpig** [comment]
That's a FCGI configure.ac issue, you can isolate that in the subtree.

**Comment by yurivict** [comment]
It checks for fileno in cppForSwig/fcgi/perl. Configure script in there does print `checking for a fileno() prototype in stdio.h... yes`, but the overall configure script doesn't.
