### ISSUE TITLE
'Copy Raw Tx (Hex)' copies transaction without witness data in 'Transaction info' window

### ISSUE THREAD

**Issue by mysil2** [goatpig/BitcoinArmory#393]
Armory version: 0.96.3

In 'Review Offline Transaction' window for a Segwit transaction the 'Copy Raw Tx (Hex)' button copies the transaction with witness data so that it can be broadcast from wherever. But when you click 'Click here for more information about this transaction', the 'Copy Raw Tx (Hex)' button copies the transaction without witness data so that it cannot be broadcast using a third party service. 

I would say the full raw transaction with witness data should be copied with both buttons.

**Comment by goatpig** [comment]
Will try to reproduce, thanks for the bug report.
