### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by vendforce** [goatpig/BitcoinArmory#394]
OS: arch
DE: kde

bpp.lo -MD -MP -MF .deps/lmdbpp.Tpo -c lmdbpp.cpp -o lmdbpp.o >/dev/null 2>&1
/bin/sh ../../libtool  --tag=CXX   --mode=link g++ -std=c++11 -fPIC -O2   -o liblmdb.la  mdb.lo midl.lo lmdbpp.lo
libtool: link: ar cr .libs/liblmdb.a .libs/mdb.o .libs/midl.o .libs/lmdbpp.o
libtool: link: ranlib .libs/liblmdb.a
libtool: link: ( cd ".libs" && rm -f "liblmdb.la" && ln -s "../liblmdb.la" "liblmdb.la" )
make[2]: Leaving directory '/bitcoin/Downloads/BitcoinArmory-master/cppForSwig/lmdb'
Making all in fcgi
make[2]: Entering directory '/bitcoin/Downloads/BitcoinArmory-master/cppForSwig/fcgi'
make[2]: *** No rule to make target 'all'.  Stop.
make[2]: Leaving directory '/bitcoin/Downloads/BitcoinArmory-master/cppForSwig/fcgi'
make[1]: *** [Makefile:1513: all-recursive] Error 1
make[1]: Leaving directory '/bitcoin/Downloads/BitcoinArmory-master/cppForSwig'
make: *** [Makefile:412: all-recursive] Error 1

**Comment by goatpig** [comment]
Init the submodules
