### ISSUE TITLE
armory_0.96.3.99_osx.tar crashes on start

### ISSUE THREAD

**Issue by stefek99** [goatpig/BitcoinArmory#396]
https://github.com/goatpig/BitcoinArmory/releases/download/v0.96.3.99/armory_0.96.3.99_osx.tar.gz

Crashes with some debug output:

```
Process:               Python [7747]
Path:                  /Applications/Armory.app/Contents/MacOS/Armory
Identifier:            com.armory.armory
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Python [7747]
User ID:               501

Date/Time:             2017-12-19 16:30:17.245 +0100
OS Version:            Mac OS X 10.13.2 (17C88)
Report Version:        12
Bridge OS Version:     3.0 (14Y618b)
Anonymous UUID:        C31E559D-D7F8-DFC2-9E4A-983818E1A419

Sleep/Wake UUID:       7C31FFD2-F6CE-4CAB-A5FB-F27821B2D991

Time Awake Since Boot: 57000 seconds
Time Since Wake:       22000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_FRAMEWORK_PATH=/Applications/Armory.app/Contents/MacOS/../Dependencies:/Applications/Armory.app/Contents/MacOS/../Frameworks
DYLD_LIBRARY_PATH=/Applications/Armory.app/Contents/MacOS/../Dependencies:/Applications/Armory.app/Contents/MacOS/../Frameworks

Dyld Error Message:
  Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Applications/Armory.app/Contents/MacOS/Python
  Reason: image not found

Binary Images:
       0x100000000 -        0x100000fff +Python (???) <38A4BCC5-FB2E-3090-93C8-34962CEE4B59> /Applications/Armory.app/Contents/MacOS/Python
       0x10fe1e000 -        0x10fe6898f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld

Model: MacBookPro14,3, BootROM MBP143.0167.B00, 4 processors, Intel Core i7, 2.8 GHz, 16 GB, SMC 2.45f0
Graphics: Intel HD Graphics 630, Intel HD Graphics 630, Built-In
Graphics: Radeon Pro 555, Radeon Pro 555, PCIe, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x173), Broadcom BCM43xx 1.0 (7.77.37.5.1a3)
Bluetooth: Version 6.0.2f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 23.1
Thunderbolt Bus: MacBook Pro, Apple Inc., 23.1
```

---

https://github.com/goatpig/BitcoinArmory/releases/download/v0.95.1/armory_0.95.1_osx.tar.gz

Fails silently on start.

**Comment by pauperis** [comment]
Hi, could you tell us on which system and libraries versions did you compile armory? I'm suffering this [1] issue and i'm highly interested on compiling armory.

Also, could you share your armory binary?

[1] https://github.com/goatpig/BitcoinArmory/issues/395

**Comment by goatpig** [comment]
ask @droak

**Comment by droark** [comment]
[Read me](https://github.com/goatpig/BitcoinArmory/blob/master/README_OSX.md).

**Comment by stefek99** [comment]
> users must use brew to install an updated version of OpenSSL in order for Armory 0.95.1 and above to run

Ouch... Wish users read T&C as well as readme.

I think I have homebrew, I have the flags, I have openssl and yet... 

Quick video: https://youtu.be/w_gP2QgQMyg _(30 seconds, no sound)_

**Comment by droark** [comment]
Please run Armory from the terminal (/*Armory location*/Armory.app/Contents/MacOS/Armory) and report back on what happens at the terminal. Also, you don't need 0.95.1. Please delete it unless you have very specific reasons for needing it.

**Comment by stefek99** [comment]
Thanks!

It seems like working from the command line: https://youtu.be/EkGI22dRgGU

```
(ERROR) ArmoryUtils.py:1249 - Error getting system details:
Traceback (most recent call last):
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/armoryengine/ArmoryUtils.py", line 1247, in <module>
    SystemSpecs = GetSystemDetails()
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/armoryengine/ArmoryUtils.py", line 1242, in GetSystemDetails
    out.HddAvailB = getHddSize(BTC_HOME_DIR)    / (1024**3)
  File "/Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/armoryengine/ArmoryUtils.py", line 1239, in getHddSize
    s = os.statvfs(adir)
OSError: [Errno 2] No such file or directory: '/Users/plr/Library/Application Support/Bitcoin'
(ERROR) ArmoryUtils.py:1250 - Skipping.
(ERROR) ArmoryUtils.py:3720 - Unsupported language  specified. Defaulting to English (en)
(ERROR) BDM.py:272 - setSatoshiDir: directory does not exist: /Users/plr/Library/Application Support/Bitcoin
(WARNING) SDM.py:396 - Spawning DB with command: /Applications/Armory.app/Contents/MacOS/py/usr/local/lib/armory/../../bin/ArmoryDB --db-type="DB_FULL" --cookie --datadir="/Users/plr/Library/Application Support/Armory/" --dbdir="/Users/plr/Library/Application Support/Armory/databases"
(ERROR) BDM.py:201 - DB error: /Users/plr/Library/Application Support/Bitcoin/blocks is not a valid path
```

Was using `0.95.1` because of the website:

![image](https://user-images.githubusercontent.com/249703/34215345-5723ca14-e5a5-11e7-8e1f-5daabf900bf6.png)


---

Are you sure card deck is the best source of entropy?

Window does not fit on 15 inch MacBookPro and cannot be resized.

Why not standard BIP39 recovery phrase?

All in all - I highly respect Jimmy Song - but the current state of the wallet on Mac is not user friendly.

**Comment by goatpig** [comment]
If you found this issue page, surely you can find this repo's release page.

**Comment by stefek99** [comment]
> surely you can find this repo's release page

When noticed discrepancy on the downloads page it was my instinctive, natural reaction to visit the releases page and get the latest one.

**Comment by droark** [comment]
@stefek99 - You were looking at the wrong web site. An understandable mistake, of course - I have no clue whatsoever why that one is still in play - but the wrong site nonetheless. [Here's the correct site](https://btcarmory.com/).

Resizing - Works fine for me, at least in general. There are some issues with Qt4 (unsupported library Armory uses) but there's not much I can do about that until Armory finally moves on to Qt5.

Jimmy - I think Jimmy's great too. :) No idea why he's being brought up here.

Terminal error - Is this an online or offline install? It appears that you don't have Core installed.

**Comment by stefek99** [comment]
OMG!

I was looking at wrong website:

![image](https://user-images.githubusercontent.com/249703/34222177-ec53700c-e5ba-11e7-8a19-9b62b5702ab5.png)

I'm following him on Twitter and listening to the video content he creates - I assumed the wallet he was involved goes above and beyond.

I'm experimenting with usability and onboarding, I wanted to see what is the state of the market.
