### ISSUE TITLE
cannot send btc out of armory 

### ISSUE THREAD

**Issue by glabouni** [goatpig/BitcoinArmory#397]
[armorylog_20171219_1824.txt](https://github.com/goatpig/BitcoinArmory/files/1572604/armorylog_20171219_1824.txt)
[armorylog_20171219_1824.txt](https://github.com/goatpig/BitcoinArmory/files/1572606/armorylog_20171219_1824.txt)

**Comment by droark** [comment]
[0.96.4 RC1](https://github.com/goatpig/BitcoinArmory/releases).
