### ISSUE TITLE
Cannot send BTC

### ISSUE THREAD

**Issue by rodrigomichelini** [goatpig/BitcoinArmory#398]
I get the timeout error.

I've sent the same ammount about a week ago, but it never got confirmed, so I am re-spending it. The first transaction attempt was RBF btw.

[ArmoryQt.exe.log](https://github.com/goatpig/BitcoinArmory/files/1573981/ArmoryQt.exe.log)

**Comment by rodrigomichelini** [comment]
It just worked now for some reason.

**Comment by droark** [comment]
Glad it worked. Can you please close this issue? Also, for future reference, that's not the full log that you posted. The entire file would need to be posted. It looks like you posted just a tiny snippet.
