### ISSUE TITLE
after having updated armory wallet to the last version, sending btc out of my wallet still failed

### ISSUE THREAD

**Issue by glabouni** [goatpig/BitcoinArmory#399]
[armorylog_20171220_1224.txt](https://github.com/goatpig/BitcoinArmory/files/1575322/armorylog_20171220_1224.txt)

**Comment by droark** [comment]
The log indicate that there's a mempool conflict in Core. Are you attempting to do RBF or something similar?

**Comment by droark** [comment]
Derp. I just remembered that Armory sometimes issues a timeout error but still sends the transaction anyway. I'm guessing that's what happened here. Have you checked a block explorer to see if the transaction went through?

**Comment by glabouni** [comment]
This is not actually a RBF even though I did cancel a previous transaction which had less fees and that was not confirmed after 5 hours (using the "clear all unconfirmded" in the armory help menu). 
I ve just tried again and nothing is displayed in the block explorer. So my understanding is that the transaction did not go through. 
The BTC came from an "old" wallet on which I made few transaction that I did back up last in August 2014 (I don't know with which vesion of Armory I made the back up).

**Comment by droark** [comment]
Have you restarted Core too? If not, the old transaction is probably still in Core's mempool.

**Comment by glabouni** [comment]
Yes I did restart Core

**Comment by droark** [comment]
Okay. I'm not super familiar with that side of the code. If you've tried after clearing unconfirmed transactions and restarting Core, I'm not sure if there are any other troubleshooting steps you can try.

Paging @goatpig to the OR.

**Comment by goatpig** [comment]
Shutdown core, delete mempool.dat in your Core datadir and restart it. Then start Armory and try again.

**Comment by glabouni** [comment]
Yes this is solving the issue. I am however still waiting for the transfer confirmation.

**Comment by glabouni** [comment]
After 3 hours and a 0.0015 fee I am still not in the blocckchain.
I am opening a new case for this.
thank you for you help
