### ISSUE TITLE
My wallet will not transfer any funds

### ISSUE THREAD

**Issue by pedrofviana** [goatpig/BitcoinArmory#402]
I am unable to send bitcoins from Armory due to a timeout issue. I am sending the transaction with a much higher fees but its still failing. Please find the error log attached.

[armorylog_20171220_2318.txt](https://github.com/goatpig/BitcoinArmory/files/1577557/armorylog_20171220_2318.txt)

**Comment by droark** [comment]
Sometimes, Armory says it times out but then sends it anyway. Chances are the transaction is out there, waiting to be confirmed. Have you checked any block explorers to see if the transaction occurred?

**Comment by pedrofviana** [comment]
I did a RFB on 3 transactions, guess I´ll have to wait for the to be dropped by the network.

**Comment by droark** [comment]
You shouldn't have to wait on RBF. As long as you have the new TXID (as I said, Armory sometimes says it timed out but manages to add the TX anyway in the master list), you should see what's on the network.

**Comment by droark** [comment]
FYI, 0.96.4 RC2 just came out. It has several RBF fixes. Give it a try and see if that helps.
