### ISSUE TITLE
Can't send bitcoin - txn-mempool-conflict

### ISSUE THREAD

**Issue by EdwardHam** [goatpig/BitcoinArmory#405]
Hi. I get this message when I try to send bitcoin "txn-mempool-conflict". I have tried to increase the fee up to 1000 satoshi/byte, but I still get the error message. It instantly pop ut when I try to send.
I got the latest version of both armory (0.96.3) and bitcoin core (0.15.1). I have also downloaded the ledger again, rebuilt the Armory database, but still the same. Please help. The logfile is attached.
[armorylog_20171222_1419.txt](https://github.com/goatpig/BitcoinArmory/files/1582585/armorylog_20171222_1419.txt)

**Comment by droark** [comment]
As mentioned in the forum, delete mempool.dat from Core and try again.

**Comment by droark** [comment]
Hi. I saw on the forum that this solution worked. Glad to hear it. Would you mind closing this issue? Thank you.

**Comment by EdwardHam** [comment]
Closed now. Thank you for your support.


2017-12-24 4:00 GMT+01:00 Douglas Roark <notifications@github.com>:
