### ISSUE TITLE
"TX broadcast timed out (send)" every time

### ISSUE THREAD

**Issue by Normanb666** [goatpig/BitcoinArmory#408]
Hi,
i have now tried several times to send bitcoins from my armory wallet to another one of my wallets (which by the way is new, unused and segwit), but i always only get this message. I think i have the latest installment and had the database rebuilt. I have looked up in the blockchain every time and also tried higher fees, but nothing worked. Please help me  out here ;-)
[armorylog_20171224_1217.txt](https://github.com/goatpig/BitcoinArmory/files/1584778/armorylog_20171224_1217.txt)

Norman

**Comment by Normanb666** [comment]
Solved!
Updated the core, switched back to legacy wallet and tried a couple more times. First same as above, but then it suddenly worked.

**Comment by droark** [comment]
Sometimes, Armory takes awhile to get a Tx out. A timeout gets triggered, even though the Tx still goes out. I haven't encountered one in awhile, but if I do, I just wait a minute. The Tx usually pops up in the main list of transactions eventually.

Anyway, I'm glad you worked this out. :) Would you mind closing this issue, please?
