### ISSUE TITLE
Show BTC-core sync status

### ISSUE THREAD

**Issue by mstenz** [goatpig/BitcoinArmory#411]
Hi, isnt it easy possible to show the percentage of the sync status in the Armory UI? The bitcoin debug logfile already shows the UpdateTip which in my view could be easily parsed:

`2017-12-28 09:35:18 UpdateTip: new best=00000000000000000066e50b6fbda540e08b93a0b24fc9cc14ef885082e86006 height=501105 version=0x20000000 log2_work=87.734701 tx=286091826 date='2017-12-26 11:08:01' progress=0.998191 cache=219.1MiB(1241510txo)
`
This would be a good indicator of how long to wait without doing nerdy stuff and open logfiles manually.

**Comment by droark** [comment]
Kinda seems like more work than it's worth to me. Unless you're running bitcoind, you can just pull up the GUI. Even if you are running bitcoind, you still have to write code that continually monitors the log. That's annoying, and prone to breakage if the log format changes. Finally, I believe there's a way to query bitcoind and find out the current block. I don't recall it offhand but I'm positive it's there.

**Comment by mstenz** [comment]
I don't know if you have any statistics data but i assume the most users running bitcoind, if this can be queried would be really good. I think the status of the own node is very important for wallet owners as this is headache #1. I run Armory only one day a week to stay up2date and had to fix it every 2 times because something is not working by checking the logfile. The green running status is often running for hours or days and without opening the logfile there is no way to know how long it still requires. 
I would assume such information is worth a ton for most of Armory users.

**Comment by goatpig** [comment]
It already does. Try RC1 or the state of the testing branch.

**Comment by mstenz** [comment]
Hi goatpig, 
i have already RC1 running, but i don't see any information of the Percentage of the blocks. I only see "Creating databases 98% with 1 second". This is showed since 2 hours with no change, but the block is already 100% also if i remember correctly this was already there with 0.96.3-beta so i assume this is not the display you mean. 
BTW: as you can see still after everything is synced up 100% my node is offline and i bet i need to restart armory 10-20 times the next days till this get to work as ususal. I don't know if this is how it should be?
