### ISSUE TITLE
Armory duplicating inputs

### ISSUE THREAD

**Issue by jameshilliard** [goatpig/BitcoinArmory#414]
I was sending a transaction and armory somehow constructed the transaction using the same input twice causing the transaction to be invalid. The inputs were all generation transactions with Legacy P2PKH addresses.

**Comment by droark** [comment]
Thanks for the bug report. Can you please post all your logs on Pastebin or elsewhere?

**Comment by jameshilliard** [comment]
@droark PM me on IRC for logs, prefer to keep those private, username Lightsword(I'm in the armory channel).
