### ISSUE TITLE
Issues Sending BTC

### ISSUE THREAD

**Issue by Bbuff101** [goatpig/BitcoinArmory#415]
Hello, we've been trying to send a Bitcoin from Armory to GDAX, but keep running into the following error message:

> tx broadcast timed out

We've tried disabling firewalls/anti-virus, but with no luck.  We've also tried sending the Bitcoin via command line using the bitcoin-cli, but no luck there either.  I've attached the log file.  Please let me know if you need any additional information.

Thanks,
Billy
[armorylog_20171228_1210.txt](https://github.com/goatpig/BitcoinArmory/files/1591814/armorylog_20171228_1210.txt)

**Comment by goatpig** [comment]
Update Armory
