### ISSUE TITLE
cppForSwig/fcgi directory in armory_0.96.3.99_src.tar.gz tarball is empty

### ISSUE THREAD

**Issue by pauperis** [goatpig/BitcoinArmory#417]
cppForSwig/fcgi directory in armory_0.96.3.99_src.tar.gz tarball [1] is empty so build-app.py will always fails to build. A new tarball should be uploaded with cppForSwig/fcgi directory fulfilled  so the build process won't fail at that point.
[1] https://github.com/goatpig/BitcoinArmory/releases/download/v0.96.3.99/armory_0.96.3.99_src.tar.gz

**Comment by goatpig** [comment]
It's not empty. Please double check.

**Comment by pauperis** [comment]
Someone fixed the bug by creating a new tar.gz package. Perfect :)
On 21 Dec 2017 21:44 UTC+1 The file available under the URL pointed on the first message was: 5,3MB size
empty cppForSwig/fcgi directory
shasum v0.96.3.99.tar.gz
a45b90fc1e9e8a3c49de901d746c86700716668d  v0.96.3.99.tar.gz 

I came to that link through [this comment](https://github.com/goatpig/BitcoinArmory/issues/395#issuecomment-353220334) in issue [395](https://github.com/goatpig/BitcoinArmory/issues/395) Obviously someone updated the package during this days. It would been nice to get notified on the issue [395](https://github.com/goatpig/BitcoinArmory/issues/395) as droak pointed me to the download.

Anyway, glad to know someone fixed the issue :)

**Comment by goatpig** [comment]
There's no "someone". There's just me, and droark helps with the OSX stuff.

**Comment by pauperis** [comment]
Then you know who updated the tar.gz package after pointing me to download the buggy one.
I really don't understand why you keep on posting on the closed issue, furthermore  when you know the tar.gz has been buggy for quite some time till someone updated it. At the time I opened this bug i did not know if the tar.gz was fixed or not, by filling the empty cppForSwig/fcgi directory.
