### ISSUE TITLE
Can't send bitcoins

### ISSUE THREAD

**Issue by 2chill888** [goatpig/BitcoinArmory#418]
Any help would be appreciated I have been trying to transfer for over a week but keep getting issues. Sorry but very novice at this.
[armorylog_20171229_1626.txt](https://github.com/goatpig/BitcoinArmory/files/1592662/armorylog_20171229_1626.txt)

**Comment by droark** [comment]
Please use the [new Armory web site](https://btcarmory.com/) to obtain Armory, and please use [0.96.4 RC2](https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.3.991).
