### ISSUE TITLE
armoryQT hangs after armoryDB crashes with the new released client and other issues

### ISSUE THREAD

**Issue by 4zap** [goatpig/BitcoinArmory#420]
Win10 enterprise  - build 1709

I had updated the armory client to the latest release because it was not possible to send coins. (same as all the entrys here in the list). I was able to start a send transaction but i get no confirmation. After a restart 
 from win10 i can not start armory anymore. First i get the message that armoryDB crashes and the armoryQT hangs. I need to kill the processes. i reinstalled armory_0.96.3.991_win64 with the same result.
i tried to start armoryDB.exe first before armoryQT. armoryQT starts into the dashboard but without any actions. no sync, no search in the transaction chain. nothing happen.
Is there are an option to start armoryDB.exe with some parameters? Which string need i append after the armoryDB.exe command? -path to blocks?
Any other ideas? I want to avoid a remove and reinstall of armory if possible.
(bitcoin.exe is the latest release- blockchain is complete)

Cheers
Rainer

**Comment by droark** [comment]
Have you checked [this thread](https://bitcointalk.org/index.php?topic=2660500.0)? I don't know if it's the same problem but somebody mentioned some Windows issues that weren't part of RC1.
