### ISSUE TITLE
offline issue

### ISSUE THREAD

**Issue by r123451** [goatpig/BitcoinArmory#422]
Hi, I've downloaded v0.96.3.991 and wondering how long on average does it take to finish scanning the global transaction history? I've left my computer on for two days now and there's no indication of any progress. The only progress that I saw on this was upon starting Armory, it shows at the bottom wallet that it was conducting a consistency check and then it confirms that all wallets are consistent. Thanks.

**Comment by droark** [comment]
Did you upgrade from a previous version of Armory? Are you running Bitcoin Core at the same time? Can you please post your logs?

**Comment by r123451** [comment]
Yes I have core running at the same time. Please see attached.
[armorylog_20180101_0945.txt](https://github.com/goatpig/BitcoinArmory/files/1596120/armorylog_20180101_0945.txt)

**Comment by droark** [comment]
Looks like it could be a database issue. Could you delete your Armory database directory and start Armory up after you're done? Thanks.

**Comment by r123451** [comment]
I'm sorry where can i find the database? Thanks.

**Comment by droark** [comment]
Info [here](https://btcarmory.com/docs/pathing).

**Comment by r123451** [comment]
Hi Douglas, I went through that link at it looks completely different from what I have here. For instance,  the example given "C:\Users\Adam\AppData\Roaming\Armory\databases" does not exist on my system. The furthest I can reach is "C:\Users\myname" I couldn't locate "appdata" and the subsequent path. Thanks.

**Comment by droark** [comment]
Not a Windows user, so I can't comment. That location is my understanding of what it's installed. The Armory settings might say where it is.

That said, you might want to downgrade to 0.96.4 RC1 (0.96.3.99) for now. RC2 has a Windows bug that requires a manual workaround. I don't think it affects you but you may bump into it before goatpig fixes it.

**Comment by r123451** [comment]
Ok thanks I'll try that.

**Comment by r123451** [comment]
By the way, I had withdrawn my BTW from armory around June of of 2016. I had not logged onto my armory since and now I see the same balance that I had withdrawn and labelled BTC. Would that happen to be my BCH?

**Comment by droark** [comment]
Definitely not BCH unless you're running ABC or Unlimited. Must be a DB issue of some sort.

**Comment by r123451** [comment]
Ok thanks.

**Comment by r123451** [comment]
So why can't i see my BCH on my ledger? I've followed all the steps to claim them : (

**Comment by droark** [comment]
What steps? Are you referring to [this guide](https://bitcointalk.org/index.php?topic=2070058.0)? If you're referring to the Ledger Nano in general, Armory doesn't support it.

**Comment by droark** [comment]
Just to confirm, you're talking Armory -> Exchange -> Nano, correct? If so, and the exchange got your BTC, your coins aren't going to be in Armory. You'll have to take it up with Ledger.

**Comment by r123451** [comment]
Yes that is correct. I understand that my BCH will not be in Armory. I was wondering where that original balance came from and thought it may be my BCH. But aside from that, BCT from Armory to exchange, then to Ledger nano and still no BCH showing. I will check with Ledger. Thank you for your help.

**Comment by droark** [comment]
Ahhh, okay. Some people have been reporting DB issues. My guess is that Armory somehow had a screwy DB and somehow wasn't aware of the exchange Tx. You can do a rebuild & rescan, and that should fix things.

**Comment by kmeyerhofer** [comment]
>Hi Douglas, I went through that link at it looks completely different from what I have here. >For instance, the example given "C:\Users\Adam\AppData\Roaming\Armory\databases" >does not exist on my system. The furthest I can reach is "C:\Users\myname" I couldn't >locate "appdata" and the subsequent path. Thanks.

Do you have hidden folders displayed? AppData is a hidden folder in Windows.
