### ISSUE TITLE
can't send BitCoin

### ISSUE THREAD

**Issue by SankarPersaud** [goatpig/BitcoinArmory#426]
[armorylog_20180105_2118.txt](https://github.com/goatpig/BitcoinArmory/files/1608417/armorylog_20180105_2118.txt)

**Comment by droark** [comment]
[0.96.4 RC2](https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.3.991) (and the [new web site](https://btcarmory.com/), not the old one). You may want to [delete your Armory database folder](https://btcarmory.com/docs/pathing) while you're at it.

**Comment by SankarPersaud** [comment]
Thanks.

so I downloaded armory_0.96.3.99_win64.exe, and got it installed.  I also deleted my Armory database folder.

Now with I can't start Armory, i get the loading 100% screen, and it doesn't do anything.  I've left it running overnight and i come back to the same screen.

I've since tried to uninstall and re-install Armory, but it still doesn't work.

Any thoughts?  I tried to do the log dump from offline mode, not sure if that would have any good info...

[armorylog_20180106_2138.txt](https://github.com/goatpig/BitcoinArmory/files/1609456/armorylog_20180106_2138.txt)

**Comment by SankarPersaud** [comment]
so I ended up running "ArmoryDB.exe", letting that run for a bit then running "ArmoryQT.exe", and it seems to be working now, although the building databases will take a while.  fingers crossed...

**Comment by droark** [comment]
Check the task manager and see if ArmoryDB is still running. If so, kill it and start up Armory again.

**Comment by SankarPersaud** [comment]
there was no ArmoryDB running...

**Comment by droark** [comment]
Okay. For some reason, some people end up not being able to run ArmoryDB. I think it's a permissions issue of some sort, at least on Windows, but I can't swear to it. (I don't run Windows day-to-day.)

**Comment by SankarPersaud** [comment]
So, it's been running over night and Armory loads now, but still shows 'node offline'...  

[armorylog_20180107_1033.txt](https://github.com/goatpig/BitcoinArmory/files/1609898/armorylog_20180107_1033.txt)

**Comment by droark** [comment]
Thanks. Check out [this forum post](https://bitcointalk.org/index.php?topic=2200306.msg22126330#msg22126330). Some of it is a bit unorthodox but I guess some people need to go through the steps mentioned here. The bitcoin.conf stuff is good to do no matter what, though. Try it and report back.

**Comment by droark** [comment]
@SankarPersaud - Any updates?
