### ISSUE TITLE
After "no spend" problem, rebuild & rescan has apparently damaged a wallet

### ISSUE THREAD

**Issue by fumblefingers53fy** [goatpig/BitcoinArmory#43]
I left this post on Armory's Bitcointalk.org forum yesterday, 6-15-16 as user fumblefingers:

 Re: Armory 94.1 -- Can't send any transactions
June 15, 2016, 10:00:45 PM
	
Reply with quote Edit message Delete message  #6
I'm having the same problem, sorta. 0.94.1 has been working well past two days. Tonight I get the error:

Quote
There was an error constructing your transaction, due to a quirk in the way Bitcoin transactions work. If you see this error more than once, try sending your BTC in two or more separate transactions

Smaller amounts still would not send, and, as I have been doing, I have my fee set to 0.0015

Win7

EDIT:  Rescanning made no difference. Rebuild? Rebuild what, the blockchain download? I sure hope that's not what you mean. It took me a WEEK to get the whole thing.

Although it may be important that I have the blockchain downloaded into Bitcoin Core, as when I installed Armory again, (after not having it for a couple years,) it seemed to just be "offline" and doing nothing for days. The only way I could get Armory to work, after trying all the methods described here, was to start Bitcoin Core first, then start armory with the setting for "Allow Armory to manage bitcoinqt" unchecked. Worked beautifully for a few days.(END OF MY POST)

So I rescanned and it made no difference. Then I rebuilt and rescanned, and the wallet that would not send was rebuilt with the 5 coins I had spent one and two days prior added back. (Started with 18 coins when I reinstalled Armory and restored the wallet from a paper backup, spent it down to 13 coins, but now it is showing 18 again. I cannot send from that wallet.

I was however able to, this morning, send a transaction from a different wallet successfully. But how do I now retrieve and use the 13 coins left in the first wallet?

Below is my log file:
[armorylog_20160616_1205.txt](https://github.com/goatpig/BitcoinArmory/files/318880/armorylog_20160616_1205.txt)

The "rebuild and rescan" operation also returned coins to two restored wallets from a cold storage wallet that I had not yet restored to the client. These two wallets correctly displayed 0 coins until the rebuild. It was from one of these wallets that I was able to spend this morning. The original wallet that worked earlier in the week, but malfunctioned yesterday still will not allow me to spend. So I have 13 some coins in limbo with this first wallet.

**Comment by achow101** [comment]
First of all, in Bitcointalk, don't hijack other people's threads. Make a new thread for your problem.

At the bottom right hand corner, is Armory connected and does the number of blocks match what Bitcoin Core says? Also, does the number of blocks in Bitcoin Core match what block explorers say the highest block is?

**Comment by goatpig** [comment]
-INFO  - 1466059872: (..\BlockchainScanner.cpp:636) scanned from height #384349 to #385360
-INFO  - 1466059873: (..\DatabaseBuilder.cpp:149) scanned new blocks in 2788.3s
-INFO  - 1466059873: (..\DatabaseBuilder.cpp:153) init db in 4372s

Your blockchain data is corrupt, it only has up to block 385360. You need to redownload the chain.

**Comment by fumblefingers53fy** [comment]
@goatpig 

I was unable to reply to the email sent to me, so here is my response:

Thank  you for taking the time to look at my problem.

It has been many years since I actively used a forum like Bitcointalk, and as a newbie, I was unaware of the breech of protocol in "hijacking" a thread. Thanks for pointing that out.

My Bitcoin Core GUI nowhere shows how many blocks are downloaded, nor could I find any such number in any settings or in any of the files of the installed program. But I can see that the blocks are now in the 416 thousands on blockchain.info, so I guess I have a problem.

Although it will probably take another week to re-download the chain, that's what I'll do. My method would be to completely uninstall and then reinstall both Bitcoin Core and the Armory client. Is this overkill, or is there a simpler, faster way to accomplish what you suggest?

Seven million users, and you are able to deal with individual users like me. That is amazing.

I'd like to give you a donation. Could you give me an address to send to when I'm back up and running?

.

**Comment by achow101** [comment]
Uninstalling and reinstalling will not help as this DOES NOT delete the blockchain. Instead, open up Armory and go to Help > Factory Reset and choose the last option to "Also re-download the blockchain". Then follow the instructions.

**Comment by goatpig** [comment]
@fumblefingers53fy 

You can run Core with -disablewallet (or add disablewallet=1 to bitcoin.conf) to display statistics such as the top height in the main lobby.

You do not need to redownload the entire blockchain, deleting the last 100 blkXXXXX.dat files should do it.

You can find those here: C:\Users\Me\AppData\Roaming\Bitcoin\blocks

Do that, start BitcoinQt and let it catch up, then rebuild & rescan your ArmoryDB.

One thing I can suggest is to back up that folder and the C:\Users\Me\AppData\Roaming\Bitcoin\chainstate that goes with it once every 2~3 months to prevent this kind of issues from blowing up your setup for a week
