### ISSUE TITLE
Txn-mempool-conflict

### ISSUE THREAD

**Issue by khaleesi747** [goatpig/BitcoinArmory#430]
Sent transactions several weeks ago with too low fees (around 32SAT/kb) and they haven't disappeared yet

[armorylog_20180107_1436.txt](https://github.com/goatpig/BitcoinArmory/files/1610129/armorylog_20180107_1436.txt)

**Comment by droark** [comment]
Thanks. Take a look at [this thread](https://bitcointalk.org/index.php?topic=2664629.0). If you do Help -> Clear All Unconfirmed, I believe this will clear the Tx. Please report back either way.

**Comment by droark** [comment]
@khaleesi747 - Any updates?

**Comment by khaleesi747** [comment]
Yeah it resolved, i had to put it in the free txn accelerator and it
worked, so no real solution

**Comment by droark** [comment]
Glad to hear it resolved. Can you please close the issue now? Thanks!
