### ISSUE TITLE
Small Logging Error in ArmoryUtils.py

### ISSUE THREAD

**Issue by Gee19** [goatpig/BitcoinArmory#432]
Stack Trace:
```
2018-01-08 08:06:56 (INFO) -- SDM.pyc:459 - Called stopBitcoind
2018-01-08 08:06:57 (ERROR) -- ArmoryQt.py:5458 - Strange error during shutdown
Traceback (most recent call last):
  File "ArmoryQt.py", line 5449, in closeForReal
  File "SDM.pyc", line 485, in stopBitcoind
  File "armoryengine\ArmoryUtils.pyc", line 836, in LOGERROR
TypeError: cannot concatenate 'str' and 'exceptions.RuntimeError' objects
```

Error occurs here:
```
def LOGERROR(msg, *a):
   try:
      logstr = msg if len(a)==0 else (msg%a)
      callerStr = getCallerLine() + ' - '
      logging.error(callerStr + logstr)
```

msg or msg%a is returning exceptions.RuntimeError object. 

Not 100% sure of the fix because I couldn't reproduce it. Could be as simple as `str(logstr)`

The error occurred while armory was stuck Preparing Databases, after allowing bitcoind/armory through firewall. 

Win10 x64
Armory v0.96.3

**Comment by droark** [comment]
Thanks for the report. Just curious, would you mind running [0.96.4 RC1](https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.3.99) (Windows) or [RC2](https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.3.991) (other systems, or Windows if you don't mind having to use a workaround) and seeing if it still happens? It probably will but I'd like to confirm this before going further.

**Comment by Gee19** [comment]
I'll try and do it tonight or tomorrow and report back.

**Comment by droark** [comment]
@Gee19 - Any updates? If not, RC3 should be out in the next day or two, and it should fix the Windows issue if that's a concern of yours.

**Comment by Gee19** [comment]
Not seeing this error on RC3.
