### ISSUE TITLE
support for regtest

### ISSUE THREAD

**Issue by 0xae** [goatpig/BitcoinArmory#435]
Does armory support regtest ?

**Comment by droark** [comment]
I don't believe so. The closest Armory comes is usage of a tool called testnet-in-a-box. I believe it's still in the repo if you don't mind tinkering with it.

**Comment by achow101** [comment]
There should be regtest support. I remember adding it while implementing 
segwit support.

**Comment by 0xae** [comment]
i failed to find a --regtest option in the ArmoryQt.py frontend

**Comment by droark** [comment]
I stand corrected! I see --regtest in the options.

@0xe - Which version are you running?

**Comment by 0xae** [comment]
are there any more binaries i could use,
i even tried to change the datadir to ~/.bitcoin/regtest to see if it would recognize

**Comment by 0xae** [comment]
i am using the version 0.93.3-beta

**Comment by 0xae** [comment]
i'm on the master branch

**Comment by droark** [comment]
Whoa. That's waaaaaaaay old. You need to read the info in the README and upgrade to 0.96.4 RC1 (Windows) or RC2 (macOS or Linux).

**Comment by 0xae** [comment]
ohhh, i cloned this repo (https://github.com/etotheipi/BitcoinArmory), i guess i should've cloned the goatpig's one

**Comment by droark** [comment]
Yep, the goatpig one is the correct one. For now, the latest code is on the testing branch, although it'll get moved to master once the final 0.96.4 is released.

**Comment by 0xae** [comment]
Humm i see, this is a great wallet, i love all the flexibility, regtest support was the only thing missing.
I am thinking contributing

**Comment by droark** [comment]
Glad you like it. :) Patches are welcome. We may ask that you move the patch to a particular branch but we're happy to review whatever comes our way.

In the meantime, would you mind closing this issue?

**Comment by 0xae** [comment]
Yep, thank you very much
