### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by simong1080** [goatpig/BitcoinArmory#437]
After make command I get this error:

`/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘int _mm_extract_epi32(__m128i, int)’: target specific option mismatch
 _mm_extract_epi32 (__m128i __X, const int __N)
 ^
rijndael.cpp:223:44: error: called from here
    rk[keylen/4] = rk[0] ^ _mm_extract_epi32(_mm_aeskeygenassist_si128(temp, 0),
                                            ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘int _mm_extract_epi32(__m128i, int)’: target specific option mismatch
 _mm_extract_epi32 (__m128i __X, const int __N)
 ^
rijndael.cpp:223:44: error: called from here
    rk[keylen/4] = rk[0] ^ _mm_extract_epi32(_mm_aeskeygenassist_si128(temp, 0),
                                            ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:406:1: error: inlining failed in call to always_inline ‘__m128i _mm_insert_epi32(__m128i, int, int)’: target specific option mismatch
 _mm_insert_epi32 (__m128i __D, int __S, const int __N)
 ^
rijndael.cpp:235:45: error: called from here
     temp = _mm_insert_epi32(temp, rk[11], 3);
                                             ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:406:1: error: inlining failed in call to always_inline ‘__m128i _mm_insert_epi32(__m128i, int, int)’: target specific option mismatch
 _mm_insert_epi32 (__m128i __D, int __S, const int __N)
 ^
rijndael.cpp:244:45: error: called from here
     temp = _mm_insert_epi32(temp, rk[15], 3);
                                             ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘int _mm_extract_epi32(__m128i, int)’: target specific option mismatch
 _mm_extract_epi32 (__m128i __X, const int __N)
 ^
rijndael.cpp:240:43: error: called from here
        rk[12] = rk[ 4] ^ _mm_extract_epi32(_mm_aeskeygenassist_si128(temp, 0), 
                                           ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:406:1: error: inlining failed in call to always_inline ‘__m128i _mm_insert_epi32(__m128i, int, int)’: target specific option mismatch
 _mm_insert_epi32 (__m128i __D, int __S, const int __N)
 ^
rijndael.cpp:239:45: error: called from here
     temp = _mm_insert_epi32(temp, rk[11], 3);
                                             ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:406:1: error: inlining failed in call to always_inline ‘__m128i _mm_insert_epi32(__m128i, int, int)’: target specific option mismatch
 _mm_insert_epi32 (__m128i __D, int __S, const int __N)
 ^
rijndael.cpp:244:45: error: called from here
     temp = _mm_insert_epi32(temp, rk[15], 3);
                                             ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘int _mm_extract_epi32(__m128i, int)’: target specific option mismatch
 _mm_extract_epi32 (__m128i __X, const int __N)
 ^
rijndael.cpp:240:43: error: called from here
        rk[12] = rk[ 4] ^ _mm_extract_epi32(_mm_aeskeygenassist_si128(temp, 0), 
                                           ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:406:1: error: inlining failed in call to always_inline ‘__m128i _mm_insert_epi32(__m128i, int, int)’: target specific option mismatch
 _mm_insert_epi32 (__m128i __D, int __S, const int __N)
 ^
rijndael.cpp:247:44: error: called from here
     temp = _mm_insert_epi32(temp, rk[7], 3);
                                            ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘int _mm_extract_epi32(__m128i, int)’: target specific option mismatch
 _mm_extract_epi32 (__m128i __X, const int __N)
 ^
rijndael.cpp:223:44: error: called from here
    rk[keylen/4] = rk[0] ^ _mm_extract_epi32(_mm_aeskeygenassist_si128(temp, 0),
                                            ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:406:1: error: inlining failed in call to always_inline ‘__m128i _mm_insert_epi32(__m128i, int, int)’: target specific option mismatch
 _mm_insert_epi32 (__m128i __D, int __S, const int __N)
 ^
rijndael.cpp:235:45: error: called from here
     temp = _mm_insert_epi32(temp, rk[11], 3);
                                             ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:406:1: error: inlining failed in call to always_inline ‘__m128i _mm_insert_epi32(__m128i, int, int)’: target specific option mismatch
 _mm_insert_epi32 (__m128i __D, int __S, const int __N)
 ^
rijndael.cpp:239:45: error: called from here
     temp = _mm_insert_epi32(temp, rk[11], 3);
                                             ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:406:1: error: inlining failed in call to always_inline ‘__m128i _mm_insert_epi32(__m128i, int, int)’: target specific option mismatch
 _mm_insert_epi32 (__m128i __D, int __S, const int __N)
 ^
rijndael.cpp:244:45: error: called from here
     temp = _mm_insert_epi32(temp, rk[15], 3);
                                             ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘int _mm_extract_epi32(__m128i, int)’: target specific option mismatch
 _mm_extract_epi32 (__m128i __X, const int __N)
 ^
rijndael.cpp:240:43: error: called from here
        rk[12] = rk[ 4] ^ _mm_extract_epi32(_mm_aeskeygenassist_si128(temp, 0), 
                                           ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:41:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from rijndael.h:7,
                 from rijndael.cpp:72:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:406:1: error: inlining failed in call to always_inline ‘__m128i _mm_insert_epi32(__m128i, int, int)’: target specific option mismatch
 _mm_insert_epi32 (__m128i __D, int __S, const int __N)
 ^
rijndael.cpp:247:44: error: called from here
     temp = _mm_insert_epi32(temp, rk[7], 3);
                                            ^
Makefile:625: recipe for target 'rijndael.lo' failed
make[3]: *** [rijndael.lo] Error 1
make[3]: Leaving directory '/home/shimon/BitcoinArmory/cppForSwig/cryptopp'
Makefile:1446: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/shimon/BitcoinArmory/cppForSwig'
Makefile:430: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/shimon/BitcoinArmory'
Makefile:362: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by goatpig** [comment]
Your compiler can't handle the SSE calls. How did you configure the makefiles?

**Comment by psymyn** [comment]
I followed the build instructions on the readme:

 ./autogen.sh
./configure
make

I also installed dependencies:
sudo apt-get install git-core pkg-config build-essential pyqt4-dev-tools swig libqtcore4 libqt4-dev python-qt4 python-dev python-twisted python-psutil

and
sudo apt-get install libtool-bin
was also required

**Comment by goatpig** [comment]
What CPU and OS is this?

**Comment by psymyn** [comment]
CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 37
Model name:            Intel(R) Pentium(R) CPU        P6100  @ 2.00GHz
Stepping:              5
CPU MHz:               1999.000
CPU max MHz:           1999.0000
CPU min MHz:           933.0000
BogoMIPS:              3989.58
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              3072K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm pcid popcnt lahf_lm dtherm arat

OS:
Linux trichome 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by goatpig** [comment]
This is chocking on -maes found in this makefile:

https://github.com/goatpig/BitcoinArmory/blob/master/cppForSwig/cryptopp/Makefile.am#L26

I got no idea why your system detect aes when your cpu doesn't have it. At any rate, comment that line out then:

make clean
./configure
make

**Comment by psymyn** [comment]
I couldn't find a `AM_CXXFLAGS += -maes -DCRYPTOPP_ENABLE_AESNI` in the makefile.am under ~/BitcoinArmory/cppForSwig/cryptopp/

**Comment by goatpig** [comment]
What branch did you pull from?

**Comment by psymyn** [comment]
I ran
`git clone https://github.com/goatpig/BitcoinArmory.git`
per readme

**Comment by goatpig** [comment]
Double check the makefile, this line should be there. If it's missing, post your makefile for inspection.

**Comment by psymyn** [comment]
Ok, I found the line and commented out as follows:
`if ! BUILD_DARWIN
# AM_CXXFLAGS += -march=native -mtune=generic -mpclmul -maes $(X86_FEATURE_CFLAGS)
endif	# ! BUILD_DARWIN`

Then I ran 
make clean
./cnfigure
make 
and now this:
`cpu.h:51:1: error: redefinition of ‘__m128i _mm_clmulepi64_si128(__m128i, __m128i, int)’
 _mm_clmulepi64_si128 (__m128i a, __m128i b, const int i)
 ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:43:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from strciphr.h:31,
                 from sosemanuk.h:4,
                 from sosemanuk.cpp:9:
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:116:1: note: ‘__m128i _mm_clmulepi64_si128(__m128i, __m128i, int)’ previously defined here
 _mm_clmulepi64_si128 (__m128i __X, __m128i __Y, const int __I)
 ^
In file included from sosemanuk.cpp:11:0:
cpu.h: In function ‘__m128i _mm_aeskeygenassist_si128(__m128i, int)’:
cpu.h:57:1: error: redefinition of ‘__m128i _mm_aeskeygenassist_si128(__m128i, int)’
 _mm_aeskeygenassist_si128 (__m128i a, const int i)
 ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:43:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from strciphr.h:31,
                 from sosemanuk.h:4,
                 from sosemanuk.cpp:9:
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:87:1: note: ‘__m128i _mm_aeskeygenassist_si128(__m128i, int)’ previously defined here
 _mm_aeskeygenassist_si128 (__m128i __X, const int __C)
 ^
In file included from sosemanuk.cpp:11:0:
cpu.h: In function ‘__m128i _mm_aesimc_si128(__m128i)’:
cpu.h:64:1: error: redefinition of ‘__m128i _mm_aesimc_si128(__m128i)’
 _mm_aesimc_si128 (__m128i a)
 ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:43:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from strciphr.h:31,
                 from sosemanuk.h:4,
                 from sosemanuk.cpp:9:
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:77:1: note: ‘__m128i _mm_aesimc_si128(__m128i)’ previously defined here
 _mm_aesimc_si128 (__m128i __X)
 ^
In file included from sosemanuk.cpp:11:0:
cpu.h: In function ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’:
cpu.h:71:1: error: redefinition of ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’
 _mm_aesenc_si128 (__m128i a, __m128i b)
 ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:43:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from strciphr.h:31,
                 from sosemanuk.h:4,
                 from sosemanuk.cpp:9:
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:61:1: note: ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’ previously defined here
 _mm_aesenc_si128 (__m128i __X, __m128i __Y)
 ^
In file included from sosemanuk.cpp:11:0:
cpu.h: In function ‘__m128i _mm_aesenclast_si128(__m128i, __m128i)’:
cpu.h:77:1: error: redefinition of ‘__m128i _mm_aesenclast_si128(__m128i, __m128i)’
 _mm_aesenclast_si128 (__m128i a, __m128i b)
 ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:43:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from strciphr.h:31,
                 from sosemanuk.h:4,
                 from sosemanuk.cpp:9:
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:69:1: note: ‘__m128i _mm_aesenclast_si128(__m128i, __m128i)’ previously defined here
 _mm_aesenclast_si128 (__m128i __X, __m128i __Y)
 ^
In file included from sosemanuk.cpp:11:0:
cpu.h: In function ‘__m128i _mm_aesdec_si128(__m128i, __m128i)’:
cpu.h:83:1: error: redefinition of ‘__m128i _mm_aesdec_si128(__m128i, __m128i)’
 _mm_aesdec_si128 (__m128i a, __m128i b)
 ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:43:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from strciphr.h:31,
                 from sosemanuk.h:4,
                 from sosemanuk.cpp:9:
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:44:1: note: ‘__m128i _mm_aesdec_si128(__m128i, __m128i)’ previously defined here
 _mm_aesdec_si128 (__m128i __X, __m128i __Y)
 ^
In file included from sosemanuk.cpp:11:0:
cpu.h: In function ‘__m128i _mm_aesdeclast_si128(__m128i, __m128i)’:
cpu.h:89:1: error: redefinition of ‘__m128i _mm_aesdeclast_si128(__m128i, __m128i)’
 _mm_aesdeclast_si128 (__m128i a, __m128i b)
 ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:43:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from stdcpp.h:18,
                 from cryptlib.h:83,
                 from seckey.h:8,
                 from strciphr.h:31,
                 from sosemanuk.h:4,
                 from sosemanuk.cpp:9:
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:52:1: note: ‘__m128i _mm_aesdeclast_si128(__m128i, __m128i)’ previously defined here
 _mm_aesdeclast_si128 (__m128i __X, __m128i __Y)
 ^
Makefile:624: recipe for target 'sosemanuk.lo' failed
make[3]: *** [sosemanuk.lo] Error 1
make[3]: Leaving directory '/home/shimon/BitcoinArmory/cppForSwig/cryptopp'
Makefile:1446: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/shimon/BitcoinArmory/cppForSwig'
Makefile:430: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/shimon/BitcoinArmory'
Makefile:362: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by goatpig** [comment]
This is unreadable, use some sort paste service that preserves the line break. Also I need to see the invocation line.

**Comment by psymyn** [comment]
Sorry about that: https://pastebin.com/BDABK1x4

**Comment by goatpig** [comment]
This is just the error, I want to see the compiler invocation line as well. Typically starts with g++

**Comment by psymyn** [comment]
See the paste again?

**Comment by goatpig** [comment]
Install clang and try to build with that:

make clean
CC=clang ./configure
make

**Comment by psymyn** [comment]
I did and got: https://pastebin.com/gaE45j72

What if I just do an OS reinstall and try again?

**Comment by goatpig** [comment]
This is a CPU thing. 

Still using clang, add this line to the makefile:

AM_CXXFLAGS += -DCRYPTOPP_DISABLE_ASM

you'll have to make clean and ./configure again.

**Comment by goatpig** [comment]
it's not in the g++ call so it's not getting triggered. Humor me, force it.

**Comment by psymyn** [comment]
I put it here:
if IS_X86
if CRYPTOPP_HAVE_GCC
if ! BUILD_DARWIN
AM_CXXFLAGS += -DCRYPTOPP_DISABLE_ASM

Yet still error...

**Comment by goatpig** [comment]
Then i've got nothing, your CPU is too old for this. You'll either have to dig in the cryptopp code to disable all things mAES, or try one of my own builds.

**Comment by droark** [comment]
@psymyn - If you want to poke around, [this](https://github.com/weidai11/cryptopp/blob/master/GNUmakefile) is the newest Crypto++ Makefile. There might be a hint in there somewhere if you're willing to poke around a bit.

@goatpig - I'm not convinced this is a case of a CPU that's too old. The CPU is the [P6100](https://en.wikipedia.org/wiki/List_of_Intel_Pentium_microprocessors#%22Arrandale%22_(MCP,_32_nm)). It's far from new, and it doesn't have Intel's AES extensions, but Armory should be able to support this CPU.

**Comment by psymyn** [comment]
I installed using [this](https://github.com/goatpig/BitcoinArmory/releases/download/v0.96/armory_0.96-gcc5.4_amd64.deb) .deb yet when I start armory I get
`Traceback (most recent call last):
  File "update_version.py", line 14, in <module>
    f = open(hash_loc, "r")
IOError: [Errno 2] No such file or directory: '.git/aa72293f82c3ef3f1d29f93c83ad70099f4'
/home/shimon
Illegal instruction (core dumped)
`

**Comment by goatpig** [comment]
You can't use this build, use the gcc4.7 one.

**Comment by psymyn** [comment]
I've given up in the meantime. After installation and running the wallet I get
`/home/shimon
(ERROR) ArmoryUtils.py:3716 - Unsupported language  specified. Defaulting to English (en)
/usr/lib/armory/armoryengine/Transaction.py:2882: SyntaxWarning: import * only allowed at module level
  def PyCreateAndSignTx_old(srcTxOuts, dstAddrsVals):
(ERROR) ArmoryQt.py:5951 - Socket already in use.  Sent CLI args to existing proc.
(ERROR) ArmoryQt.py:5952 - Exiting...
shimon@trichome:~$ armory 
/home/shimon
(ERROR) ArmoryUtils.py:3716 - Unsupported language  specified. Defaulting to English (en)
/usr/lib/armory/armoryengine/Transaction.py:2882: SyntaxWarning: import * only allowed at module level
  def PyCreateAndSignTx_old(srcTxOuts, dstAddrsVals):
(ERROR) ArmoryQt.py:5951 - Socket already in use.  Sent CLI args to existing proc.
(ERROR) ArmoryQt.py:5952 - Exiting...
`
I'm just gonna reinstall the system afresh and then try. Thanks for your help anyhow.

**Comment by goatpig** [comment]
This is working fine actually. The armory interop socket is in use, you need to free that up (8223)

**Comment by psymyn** [comment]
How do I do that?

**Comment by goatpig** [comment]
I don't know, some process is running on that port, close it. You can also try the interport arg:

https://github.com/goatpig/BitcoinArmory/blob/master/armoryengine/ArmoryUtils.py#L104
