### ISSUE TITLE
Wallet won't start ERROR: Cannot resolve reference Microsoft.VC90.CRT,processorArchitecture

### ISSUE THREAD

**Issue by kanewinter** [goatpig/BitcoinArmory#438]
Wallet won't start on my windows server. Armory Version 0.96.0 Trace results below

#=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Program Files (x86)\Armory\ArmoryQt.exe
	AssemblyDirectory = C:\Program Files (x86)\Armory\
	Application Config File = 
#-----------------
INFO: Parsing Manifest File C:\Program Files (x86)\Armory\ArmoryQt.exe.
	INFO: Manifest Definition Identity is (null).
	INFO: Reference: Microsoft.VC90.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8"
INFO: Resolving reference Microsoft.VC90.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8".
	INFO: Resolving reference for ProcessorArchitecture amd64.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\Windows\assembly\GAC_64\Microsoft.VC90.CRT\9.0.21022.8__1fc8b3b9a1e18e3b\Microsoft.VC90.CRT.DLL.
				INFO: Attempt to probe manifest at C:\Program Files (x86)\Armory\Microsoft.VC90.CRT.DLL.
				INFO: Attempt to probe manifest at C:\Program Files (x86)\Armory\Microsoft.VC90.CRT.MANIFEST.
				INFO: Attempt to probe manifest at C:\Program Files (x86)\Armory\Microsoft.VC90.CRT\Microsoft.VC90.CRT.DLL.
				INFO: Attempt to probe manifest at C:\Program Files (x86)\Armory\Microsoft.VC90.CRT\Microsoft.VC90.CRT.MANIFEST.
				INFO: Did not find manifest for culture Neutral.
			INFO: End assembly probing.
	ERROR: Cannot resolve reference Microsoft.VC90.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8".
ERROR: Activation Context generation failed.
End Activation Context Generation.

**Comment by droark** [comment]
[0.96.4 RC1](https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.3.99).

**Comment by droark** [comment]
@kanewinter - Any updates?
