### ISSUE TITLE
Cannot Send BTC

### ISSUE THREAD

**Issue by kristiani75** [goatpig/BitcoinArmory#439]
Hello,

I seem to be having a similar issue to others. I am unable to send funds. Orignally I received a failed to broadcast error, suggesting my fee/by
[armorylog_20180113_2150.txt](https://github.com/goatpig/BitcoinArmory/files/1628246/armorylog_20180113_2150.txt)
te was to low. I upgraded to the latest BTcore, and aso Armory 0.6.4 RC1. I cleared and rebuilt the database and I am still unable to send funds. However now I receive a mem pool conflict error. Any help you can provide me would be greatly appreciated.

**Comment by droark** [comment]
Help -> Clear All Unconfirmed

If that still doesn't work, go into your Armory DB folder and delete the *zeroconf* files. These are Armory's mempool files. Transactions can get stuck there sometimes.

**Comment by kristiani75** [comment]
I have done all this.....im still getting the txn-mempool-conflict
However I am not getting the fee warning (using auto fee setting)

[armorylog_20180114_0948.txt](https://github.com/goatpig/BitcoinArmory/files/1628820/armorylog_20180114_0948.txt)

**Comment by droark** [comment]
Bitcoin Core is the one rejecting the Tx. Try deleting mempool.dat in your Core data directory and see if that helps.

**Comment by kristiani75** [comment]
Ok....that has worked...however all the previous transactions which have failed over the last few dayas are now throwing my balance out as unconfirmed and havent appeared at the other end????

**Comment by kristiani75** [comment]
Mmmm...problem...the previous transactions have now spooled. Confirmed on blockchain. But are not appearing at the other end???

**Comment by droark** [comment]
I'm not sure I understand what you're saying. I can see one Tx that went through on the blockchain. If you're seeing more than one in Armory, Help -> Clear All Unconfirmed should work. If not, try Help -> Rescan Balance, then Help -> Rescan Databases if that doesn't work, then Help -> Rebuild and Rescan Databases if that doesn't work. Don't do a factory reset.

**Comment by kristiani75** [comment]
That did the trick! Im breathing normally now. lol
Thankyou very much mate!

**Comment by droark** [comment]
You're welcome. :) Would you mind closing this issue now? Thanks.
