### ISSUE TITLE
Armory crash after scanning block at startup

### ISSUE THREAD

**Issue by Nyutag** [goatpig/BitcoinArmory#44]
`$ armory 
/usr/lib/armory/armoryengine/Transaction.py:2653: SyntaxWarning: import * only allowed at module level
  def PyCreateAndSignTx_old(srcTxOuts, dstAddrsVals):
(WARNING) ArmoryQt.py:2422 - Tried to start bitcoind, but satoshi already running
(WARNING) ArmoryUtils.py:624 - Killing process pid=1166
(ERROR) ArmoryQt.py:1336 - 4 attempts to load blockchain failed.  Remove mempool.bin.
(ERROR) ArmoryQt.py:1341 - File mempool.bin does not exist. Nothing deleted.
-INFO  - 1466429212: (BlockUtils.cpp:924) blkfile dir: /home/user/.bitcoin/blocks
-INFO  - 1466429212: (BlockUtils.cpp:925) lmdb dir: /home/user/.armory/databases
-INFO  - 1466429212: (lmdb_wrapper.cpp:387) Opening databases...
-INFO  - 1466429213: (BlockUtils.cpp:1105) Executing: doInitialSyncOnLoad
-INFO  - 1466429213: (DatabaseBuilder.cpp:162) Reading headers from db
-INFO  - 1466429218: (DatabaseBuilder.cpp:195) Found 414338 headers in db
-INFO  - 1466429220: (DatabaseBuilder.cpp:43) updating HEADERS db
-DEBUG - 1466429220: (Blockchain.cpp:213) Organizing chain 
-INFO  - 1466429220: (DatabaseBuilder.cpp:47) updated HEADERS db in 0.025958s
-INFO  - 1466429220: (DatabaseBuilder.cpp:98) scanning new blocks from #0 to #414277
--ERROR - ERROR - 14664292211466429221: : ((BlockchainScanner.cppBlockchainScanner.cpp::276276) unknown block deser error during scan at height #) unknown block deser error during scan at height #01

terminate called without an active exception
Abandon (core dumped)`

**Comment by goatpig** [comment]
Do a rebuild & rescan.

**Comment by Nyutag** [comment]
Had to do it two time, but working fine now! Thanks!
