### ISSUE TITLE
Cannot install Armory - runtime error

### ISSUE THREAD

**Issue by AlanMiddleton** [goatpig/BitcoinArmory#443]
Hi all, I am in a spot of bother here.  Trying to install Armory most recent versions but keep getting a runtime problem as per the image below.  Have tried deleting everything and installing 0.96.3.99, but same message.  This is a new windows 10 computer with Malwarebytes installed and running.  Please help. 

![image](https://user-images.githubusercontent.com/35561326/35092101-7774adf2-fc92-11e7-98a1-f3beb4346286.png)

**Comment by droark** [comment]
Which version are you trying to install? 0.96.4 RC1? 0.96.4 RC3 (0.96.3.992) should install just fine.

**Comment by droark** [comment]
@AlanMiddleton - Any updates?

**Comment by AlanMiddleton** [comment]
Hello Douglas, I have seen you latest post and now see that you have been sending me emails.  Perhaps I can use this email rather than posting on the site?

The link to my logs is:
https://pastebin.com/7FHrUm0j

Pleas let me know if this does not work.  Thanks, Alan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by droark** [comment]
Hi. I'd prefer to use the site. I'd prefer that everything be done in the open.

Can you please install [0.96.4 RC3](https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.3.992) and see if the problem persists? If it does, when exactly do you see this error happen?
