### ISSUE TITLE
Trying to move BCH out of armory wallet

### ISSUE THREAD

**Issue by hedgehawg** [goatpig/BitcoinArmory#452]
Hi goatpig. You are great, and your help would be greatly appreciated. I am trying to access my BCH. I have had BTC stored in my Armory wallet since pre-fork. I read your post about moving BCH out of armory -- "using Armory on the BCH chain" https://bitcointalk.org/index.php?topic=2070058.msg20673808#msg20673808. So I am now trying to send my BCH to a BCH wallet. The program rejects my BCH wallet address. When I try to click "Send BTC", i get the following error message: "You have entered 1 invalid addresses. The errors have been highlighted on the entry screen." Log file attached. So I don't even get the chance to change the Signer. Do i need to separately download a BCH database? If so, how do I point Armory at it? Thank you!
[armorylog_20180206_2058.txt](https://github.com/goatpig/BitcoinArmory/files/1701441/armorylog_20180206_2058.txt)
Thank you!

**Comment by goatpig** [comment]
Does the BCH address start with 1 or 3?

**Comment by hedgehawg** [comment]
the address does not start with either, it is being generated by coinbase:
qzrg89n4uncunmzwa25jmfw5h80mzk4vaquh6fvpcx

**Comment by droark** [comment]
That would [appear](https://bitcoin.stackexchange.com/questions/69056/bitcoin-cash-cash-address-format) to be an address in Bcash's "Cash Address" format (i.e., a cheap knockoff of Bech32). It looks like 1DGFBaj8N3kfTE9nH9W1nNFgCKdnMQUmAv is the equivalent address but please double-check with Coinbase and make sure they'll actually get the coins if you send them to this address. (Better yet, get Coinbase to supply you with an address that starts with 1.)

This issue can be closed. Armory will support Bech32 in 0.97 (AFAIK) but not this Cash Address silliness.

**Comment by hedgehawg** [comment]
Ok thank you.
