### ISSUE TITLE
Can't Send Bitcoin

### ISSUE THREAD

**Issue by scottjack791** [goatpig/BitcoinArmory#462]
I am trying to send Bitcoin to a different wallet, but it continues to say the transaction didn't go through.  It keeps saying that the reason it didn't go through is possibly due to the fee being too low.  I have tried increasing the fee up to .001 bitcoin and it still doesn't accept it.  Please help.  I don't know what to do from here.  We need this Bitcoin sent ASAP!!!!

[Uploading armorylog.txt…]()

[Uploading armorylog_20180223_2121.txt…]()

**Comment by goatpig** [comment]
The links to your logs are invalid. You most likely need to update Armory anyways.

**Comment by scottjack791** [comment]
How do I update Armory?

**Comment by goatpig** [comment]
https://github.com/goatpig/BitcoinArmory/releases

Install the newest stuff. Stick to one issue.
