### ISSUE TITLE
Can't send Bitcoin

### ISSUE THREAD

**Issue by scottjack791** [goatpig/BitcoinArmory#463]
I am trying to send bitcoin to a different wallet, but the transaction won't go through.  I keep getting a message saying "If the transaction failed it is likely because the fee is too low.  Try a higher fee.  If the problem persists...contact support.  That is what I am doing now.  I'm not sure really what to do.  It says to attach some files.  I don't know if these are the correct ones, but here you go.  Please help me resolve this issue.  I need to send this Bitcoin ASAP!!!!

[armorylog_20180223_2121.txt](https://github.com/goatpig/BitcoinArmory/files/1751852/armorylog_20180223_2121.txt)

**Comment by goatpig** [comment]
Same thing, update Armory.
