### ISSUE TITLE
Updated Armory and Still Can't Send Bitcoin

### ISSUE THREAD

**Issue by scottjack791** [goatpig/BitcoinArmory#464]
I'm updated Armory, and still can't send Bitcoin.  I don't get the error I got before, but when I send nothing happens.  I've tried to close Armory and restart, but still no change.  Any advise?  Need to get this Bitcoin sent ASAP!!  Thank you!!

[armorylog_20180223_2315.txt](https://github.com/goatpig/BitcoinArmory/files/1752159/armorylog_20180223_2315.txt)

**Comment by goatpig** [comment]
> scanning new blocks from #502366 to #502365

Your node is not up to date. Do the following:

1) In your Bitcoin datadir (C:\Users\Kristian\AppData\Roaming\Bitcoin), find bitcoin.conf. If the file is missing, create it. Add the following lines in there if they are missing:

`listen=1
server=1`

2) Start BitcoinQt manually and let it catch up.

3) Delete your Armory logs (C:\Users\Kristian\AppData\Roaming\Armory\dbLog.txt, C:\Users\Kristian\AppData\Roaming\Armory\armorylog.txt)

4) Start Armory while BitcoinQt is still running and try to spend again. Report here afterwards.

**Comment by scottjack791** [comment]
I need more help with this.  I am not very good with computers.  I go to C: drive, and then Kristian, but in that file there is nothing that says "AppData"
Also, I don't know what you mean when you say "add these lines" if they are missing.
Please help me.
Thank you!
