### ISSUE TITLE
Getting an error when opening Armory

### ISSUE THREAD

**Issue by scottjack791** [goatpig/BitcoinArmory#466]
I've updated Armory...I believe, but now when I open Armory, I get this message "ArmoryDB.exe   ArmoryDB.exe has stopped working.  A problem caused the program to stop working correctly.  Windows will close the program and notify you if a solution is available.

What do I need to do?  Did I delete the ArmoryDB?

Please help.  Thank you!!!!

[armorylog_20180224_2249.txt](https://github.com/goatpig/BitcoinArmory/files/1754468/armorylog_20180224_2249.txt)

**Comment by droark** [comment]
Why did you revert back to 0.96? That's not a good idea.

**Comment by scottjack791** [comment]
I went to the Armory home page and tried installing it from there.  Figured that was also the latest version.
What should I do.  I think my ArmoryDB is gone.

**Comment by droark** [comment]
> I went to the Armory home page and tried installing it from there.  Figured that was also the latest version.

You checked the wrong site. [Here's the right one.](https://btcarmory.com/) That said, you'll have to go [here](https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.3.992) for the latest version (0.96.4 RC3, which it looks like you were already running).

> What should I do.  I think my ArmoryDB is gone.

Reinstall 0.96.4 RC3 and try again.

**Comment by scottjack791** [comment]
Hi Douglas,
Honestly, I was just trying to do something, anything I can do to get Armory to work.  I read on the advise thread that I should delete the ArmoryDB and then re-update.  That just seemed to make things worse.
Please let me know what I should do.  You are the expert....not me.
I REALLY need to get this Bitcoin sent ASAP...like 3 days ago.
Now, it won't even open.  Armory loads to 100% and then freezes...never opens.
I also try to open bitcoin-qt but it never goes past 0% when loading.
Please try to help me.  Should I re-install anything?
I need step by step instructions please.

Thank you!

**Comment by droark** [comment]
Hi. You were probably told to delete your Armory database folder, not the ArmoryDB binary. You really ought to go [here](https://bitcointalk.org/index.php?board=97.0) if you need step-by-step instructions. There are plenty of users there who will be happy to help. In the meantime, reinstall 0.96.4 RC3. Also, check the Task Manager. If ArmoryDB is running (it occasionally gets stuck), kill it before re-running Armory.

**Comment by droark** [comment]
Okay. I was poking around and noticed that this is the fourth or fifth time you've posted here. Frankly, it sounds like you need to find someone local to help you understand some basic computer concepts. If you're unsure if you deleted ArmoryDB or dbLog.txt, that's not good, and you really shouldn't be trying to run Armory. My suggestion is to simply post on the site I mentioned (I know you're having issues with the site but you're going to have to ride them out) and ask how to extract your keys and import them into Electrum or a similar program. The learning curve will still be sharp for you but it won't be nearly as sharp.

**Comment by scottjack791** [comment]
Hi Douglas,
I really want you to help.  I appreciate the referral to the other site for help, but I feel comfortable that you can do the best job.
I updated the blockchain so I know it is up to date.  Now when I try to open Armory, it won't go past the initial load screen...never even opens.  Is it possible for me to uninstall Armory and delete all it's files and then simply re-install it?  Then I can bring back my wallet with my code.
I simply want to get my Bitcoin to a different wallet so I can sell it.
What do you suggest?
Thank you for your help!
Scott Jackson

**Comment by scottjack791** [comment]
Hi Douglas,
I updated the blockchain so it is current.  Then I uninstalled Armory.  After I re-install Armory, I still get nothing.  It won't load, and nothing ever opens.  This doesn't make any sense.  I even tried to update the new installation with the updated version your partner sent me.

Can you send me a link that I can re-install Armory with.  I have deleted Armory again and want to start from scratch.  Is there anything else I need to delete before I re-install again?

I hope to hear back from you today.
Thank you,
Scott

**Comment by droark** [comment]
Hi. To be honest, I'm busy working on some Armory code. I really don't have time to troubleshoot these kinds of problems. That's why you were encouraged earlier to post on bitcointalk.org. There's an [Armory subforum](https://bitcointalk.org/index.php?board=97.0) where people are happy to help troubleshoot. Install [the latest version of Armory](https://github.com/goatpig/BitcoinArmory/releases/download/v0.96.3.992/armory_0.96.3.992_win64.exe) and post on the forum.
