### ISSUE TITLE
Armory 0.93 to 0.94.1 crashes Loading Database Headers

### ISSUE THREAD

**Issue by mdance** [goatpig/BitcoinArmory#48]
The last time I was able to check my account balances was using a version prior to Armory 0.93.

Once I upgraded to 0.93, and also when attempted to run 0.94.1, the application crashes after ~45 minutes during the application initialisation.

Due to the crash its hard to see the exact step it gets to, but it says:

Loading Database Headers 2 minutes
Scan Transaction History

**Comment by achow101** [comment]
Post the log file. Go to File > Export Log File and post the contents.

**Comment by mdance** [comment]
I attempted to upgrade Bitcoin Core in order to trouble shoot this issue, and unfortunately now Bitcoin Core is crashing upon launch with the following message:

2016-07-24 20:35:01 init message: Verifying blocks...
2016-07-24 20:35:01 Verifying last 288 blocks at level 3
fish: '/Applications/Bitcoin-Qt.app/Co…' terminated by signal SIGBUS (Misaligned address error)

**Comment by mdance** [comment]
I'm going to have to fix the issue with Bitcoin Core before I can troubleshoot Armory now

**Comment by Rudd-O** [comment]
```
-INFO  - 1470998830: (DatabaseBuilder.cpp:223) parsed block file #592
-DEBUG - 1470998832: (Blockchain.cpp:213) Organizing chain 
-INFO  - 1470998836: (DatabaseBuilder.cpp:47) updated HEADERS db in 1076.4s
-INFO  - 1470998836: (DatabaseBuilder.cpp:98) scanning new blocks from #0 to #424834
-ERROR - -ERROR - 1470998838-1470998838: ERROR : -- ((ERROR BlockchainScanner.cppBlockchainScanner.cpp- 1470998838:: (BlockchainScanner.cpp::1470998838276276: 276) ) unknown block deser error during scan at height #(unknown block deser error during scan at height #) 03BlockchainScanner.cpp:unknown block deser error during scan at height #
-ERROR - 1470998838: (BlockchainScanner.cpp:276) unknown block deser error during scan at height #4
2

-ERROR - 1470998838: (BlockchainScanner.cpp:276) unknown block deser error during scan at height #5
-ERROR - 1470998838: (BlockchainScanner.cpp:276) unknown block deser error during scan at height #7276
-) unknown block deser error during scan at height #1
ERROR - 1470998838: (BlockchainScanner.cpp:276) unknown block deser error during scan at height #6
terminate called without an active exception
-ERROR - -1470998838: (ERROR BlockchainScanner.cpp:276- ) unknown block deser error during scan at height #14709988382
-ERROR - 1470998838: (BlockchainScanner.cpp-: -ERROR - 1470998838: (BlockchainScanner.cpp:276) unknown block deser error during scan at height #4
ERROR :276) unknown block deser error during scan at height #-ERROR - 1470998838: (- 1470998838: (BlockchainScanner.cpp:276) unknown block deser error during scan at height #5BlockchainScanner.cpp
Aborted (core dumped)
```

Says here: https://bitcointalk.org/index.php?topic=1427026.40

"You can't use the same DB as 0.93 for 0.94. Point to another folder using the --dbdir command line argument"

If the old database format is not compatible with the new database format, it should have been a priority ZERO work item to present the user with a dialog box asking him if he wants to move the existing data files to a backup directory, before recreating the database from scratch.

Development discipline, please.

**Comment by achow101** [comment]
> "You can't use the same DB as 0.93 for 0.94. Point to another folder using the --dbdir command line argument"

> If the old database format is not compatible with the new database format, it should have been a priority ZERO work item to present the user with a dialog box asking him if he wants to move the existing data files to a backup directory, before recreating the database from scratch.

> Development discipline, please.

You are reading that quote out of context. The actual databases themselves from 0.93.3 cannot be used in 0.94+. There is nothing in the code that handles them. However, the same dbdir can be used; 0.94+ can write its new databases into the same folder and ignores the stuff that is already there. There is no compatibility issue except the 0.93.3 databases are there and taking up space. Armory will not break with those database files there.

The error you are seeing looks like you have corrupted blocks from your Bitcoin Core, it has nothing to do with the database.

**Comment by Rudd-O** [comment]
There is no corruption in my Bitcoin Core database.  The 0.93.3 version handled it fine.

**Comment by achow101** [comment]
Something failed in here https://github.com/goatpig/BitcoinArmory/blob/master/cppForSwig/BlockDataMap.cpp#L13. It has nothing to do with the databases.

**Comment by Rudd-O** [comment]
I am running master.  The error message I got does not correspond with the link to the source code that you shared right now.

**Comment by achow101** [comment]
Actually it does. Go to the line that the error says https://github.com/goatpig/BitcoinArmory/blob/master/cppForSwig/BlockchainScanner.cpp#L276. See how that is inside a catch block? The try block is here https://github.com/goatpig/BitcoinArmory/blob/master/cppForSwig/BlockchainScanner.cpp#L263. The only thing in that block which could throw an exception is the deserialize function it calls. The source for that deserialize function is the link I gave earlier.

**Comment by Rudd-O** [comment]
Oh, I must have fumbled when searching the page with Firefox, sorry.

**Comment by Rudd-O** [comment]
How do I check for corruption in the Bitcoin Core database?

**Comment by achow101** [comment]
Start up Bitcoin Core without Armory and see if it has any errors. Look at the debug.log file that Core creates and check that for any errors, particularly about block corruption or checksum mismatches.

**Comment by Rudd-O** [comment]
No errors so far.  Still running tho.  It's updating and 2 days behind.

**Comment by Rudd-O** [comment]
After restoring from snapshot, updating the blockchain to the latest block, and moving the 0.93 Armory databases out of the way, Armory finally launched without crashing.

So yes, I was right in my supposition that launching Armory 0.94 with the 0.93 databases would cause it to crash.  I can't tell you why that is, and my observation certainly disagrees with the code, but that's what I saw.

**Comment by goatpig** [comment]
data is not serialized the same way in 0.94. 0.95 has db version detection.

**Comment by Rudd-O** [comment]
There should have been a way to detect this issue.

**Comment by mdance** [comment]
Hello! 

I have FINALLY resolved my issue with Bitcoin Core (as per https://github.com/bitcoin/bitcoin/issues/8395) and am finally synced with the latest blockchain.

I ended up having to run Bitcoin client with -reindex -dbcache=2500 as there was a few corrupted chainstate ldb files.

Unfortunately, Armory is still crashing with the following error, any ideas?

-INFO  - 1473136440: (DatabaseBuilder.cpp:162) Reading headers from db
-INFO  - 1473136449: (DatabaseBuilder.cpp:195) Found 407070 headers in db
-INFO  - 1473136451: (DatabaseBuilder.cpp:43) updating HEADERS db
-INFO  - 1473137751: (DatabaseBuilder.cpp:378) Found next block after skipping 0bytes
-DEBUG - 1473137859: (Blockchain.cpp:213) Organizing chain 
-INFO  - 1473137925: (DatabaseBuilder.cpp:47) updated HEADERS db in 1797.12s
-INFO  - 1473137925: (DatabaseBuilder.cpp:98) scanning new blocks from #0 to #406734
fish: '/Applications/Armory.app/Conten…' terminated by signal SIGSEGV (Address boundary error)

**Comment by goatpig** [comment]
Did you start from a fresh Armory db folder?

**Comment by mdance** [comment]
No, how do I go about doing that?

**Comment by goatpig** [comment]
delete the content of your /databases folder in the armory datadir

**Comment by mdance** [comment]
So after renaming the databases folder and running:

/Applications/Armory.app/Contents/MacOS/Armory --debug --logfile=~/Desktop/armory-crash.log

This is the crash details:

-INFO  - 1473209544: (DatabaseBuilder.cpp:223) parsed block file #616
-DEBUG - 1473209544: (Blockchain.cpp:213) Organizing chain 
fish: '/Applications/Armory.app/Conten…' terminated by signal SIGBUS (Misaligned address error)

**Comment by Rudd-O** [comment]
Can you reliably reproduce the issue?  As in, does it fail again on the same block #616?
