### ISSUE TITLE
I need get back a little amount of satoshi's of my wallet

### ISSUE THREAD

**Issue by williamatr** [goatpig/BitcoinArmory#480]
I want to recover a small amount of satoshi's from one of my Armory's wallets, I do not have so much in this wallet, but I want to recover this satoshis. But every time I try to get the little amount out of the wallet, armory show me a error message, saing me, I can not because the amount is to low. 
I hope someone has a solution for this, I really need this little amount, and the application does not tell me, how much is the minimum value that can be sent from the armory.

thanks

**Comment by droark** [comment]
Hey. Sorry to hear that you're having issues. For the record, you'll get more support [here](https://bitcointalk.org/index.php?board=97.0). Please ask over there if you can help it.

Thanks.
