### ISSUE TITLE
Can't launch the app (0.96.4 RC3) on Mac 

### ISSUE THREAD

**Issue by Janaka-Steph** [goatpig/BitcoinArmory#482]
Hello,

I can't launch the app (0.96.4 RC3) on Mac.
 
It fails with this error report:

> Process:               Python [3641]
Path:                  /Applications/Armory.app/Contents/MacOS/Armory
Identifier:            com.armory.armory
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Python [3641]
User ID:               501
Date/Time:             2018-03-27 20:51:41.854 +0100
OS Version:            Mac OS X 10.13.3 (17D102)
Report Version:        12
Anonymous UUID:        7FC08AA4-6645-29E4-56A4-54C51EF7B8CF
Sleep/Wake UUID:       5F7B4300-7157-4CB0-A95C-3E025C0233C6
Time Awake Since Boot: 19000 seconds
Time Since Wake:       5700 seconds
System Integrity Protection: enabled
Crashed Thread:        0
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
Termination Reason:    DYLD, [0x1] Library missing
Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_FRAMEWORK_PATH=/Applications/Armory.app/Contents/MacOS/../Dependencies:/Applications/Armory.app/Contents/MacOS/../Frameworks
DYLD_LIBRARY_PATH=/Applications/Armory.app/Contents/MacOS/../Dependencies:/Applications/Armory.app/Contents/MacOS/../Frameworks
Dyld Error Message:
  Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Applications/Armory.app/Contents/MacOS/Python
  Reason: image not found
Binary Images:
       0x100000000 -        0x100000fff +Python (???) <52CF8A42-E7D0-342D-AF33-A00A2FEDCC9E> /Applications/Armory.app/Contents/MacOS/Python
       0x100ef3000 -        0x100f3d98f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld
Model: MacBookPro11,3, BootROM MBP112.0142.B00, 4 processors, Intel Core i7, 2,5 GHz, 16 GB, SMC 2.19f12
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: NVIDIA GeForce GT 750M, NVIDIA GeForce GT 750M, PCIe, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.37.5.1a3)
Bluetooth: Version 6.0.2f2, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500,28 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

Thank you for your work,
Best,

Stéphane

**Comment by droark** [comment]
[Install OpenSSL](https://github.com/goatpig/BitcoinArmory/blob/v0.96.3.992/README_macOS.md).
