### ISSUE TITLE
Armory built from 0.96.4 frequently crashes on open - unregistered bdv

### ISSUE THREAD

**Issue by CLL80** [goatpig/BitcoinArmory#484]
I built armory from `0.96.4` source on a Mac OS v10.11.6 following the instructions [here](https://github.com/goatpig/BitcoinArmory/blob/master/osxbuild/macOS_build_notes.md). I can start Armory consistently one time per restart, but after quitting once and trying to start the app again, it will crash before opening the UI. I think this is the relevant message in the dbLog.txt:

```
-INFO  - 15:56:02: (BDM_Server.cpp:1150) unregistered bdv: ffb36fb5aac47544f9df
-INFO  - 15:56:02: (BDM_Server.cpp:1061) proceeding to shutdown
-ERROR - 15:56:57: (BitcoinP2P.cpp:1027) caught SocketError exception in processDataStackThread: POLLNVAL in readFromSocketThread
-INFO  - 15:56:57: (BitcoinP2P.cpp:969) Disconnected from Bitcoin node
-ERROR - 15:56:57: (BDM_mainthread.cpp:294) caught exception in main thread: terminate
```

I can *sometimes* start Armory again without restarting, but I don't know any reason why it would be different in these cases.

**Comment by goatpig** [comment]
Make sure there is no ArmoryDB process running between cycles.

**Comment by CLL80** [comment]
Yes, there was an ArmoryDB process that is running. Armory starts normally when this is quit. Is there anything I can do to ensure this is also quit properly when Armory is closed?

**Comment by goatpig** [comment]
It has had issues shutting down on OSX because of the fcgi library. The long term plan is to drop that protocol for websockets. In the short term, there is no go to solution but making sure the binary is terminating between cycles manually.
