### ISSUE TITLE
Seting wallet password

### ISSUE THREAD

**Issue by andrux2016** [goatpig/BitcoinArmory#494]
i get wierd error when seting up password app frezzes and the whole system is frozen for a bit of time

>	ArmoryDB.exe!00007ff78472dff4()	Unknown
 	ArmoryDB.exe!00007ff784722636()	Unknown
 	ArmoryDB.exe!00007ff78478019a()	Unknown
 	ArmoryDB.exe!00007ff7847484b0()	Unknown
 	ArmoryDB.exe!00007ff78473054d()	Unknown
 	[External Code]	
 	ArmoryDB.exe!00007ff78471b3f4()	Unknown
 	ArmoryDB.exe!00007ff78472e8b3()	Unknown
 	ArmoryDB.exe!00007ff78472ea5a()	Unknown
 	[External Code]

**Comment by goatpig** [comment]
need to see armorylog.txt. what locale are you using?
