### ISSUE TITLE
tx broadcast timed out (get)

### ISSUE THREAD

**Issue by fatnonsenses** [goatpig/BitcoinArmory#501]
Hello,

I get the error in the title when I try to send BTC from my Armory wallet.

I tried increasing the fee, but I'm not comfortable sending more than .01 BTC until I'm confident the transmission will work.  I've sent smaller amounts in the past, and they seemed to work.  What should I do?

[armorylog_20180619_1520.txt](https://github.com/goatpig/BitcoinArmory/files/2116614/armorylog_20180619_1520.txt)

**Comment by darwin** [comment]
_Disclaimer: I'm no Armory expert and writing this from top of my head._

When you switch Armory to "Expert/Advanced" mode. It should give you an option/button to copy prepared fully signed transaction (as "raw" transaction in HEX format). You can take it and broadcast it via bitcoind command-line interface or via Bitcoin Qt Console.

First, you want to inspect the raw transaction produced by Armory via `decoderawtransaction` command. And then if all looks ok, you can broadcast it via `sendrawtransaction` command.

**Comment by goatpig** [comment]
Update, you're using a year old version

https://github.com/goatpig/BitcoinArmory/releases
