### ISSUE TITLE
Can't send bitcoin

### ISSUE THREAD

**Issue by russiacro2** [goatpig/BitcoinArmory#511]
Hi, second post for this issue. I have updated armory and bitcoin core, reset and rebuild databases, done a factory reset, cleared unconfirmed, checked wallet? Hope someone can help, here's the log...cheers              
[armorylog_20180710_1556.txt](https://github.com/goatpig/BitcoinArmory/files/2180929/armorylog_20180710_1556.txt)

**Comment by goatpig** [comment]
This log file still shows armory 0.96. You need to update. If you need help with that, create a thread on the community forums:

https://bitcointalk.org/index.php?board=97.0
