### ISSUE TITLE
Can't send bitcoin 

### ISSUE THREAD

**Issue by russiacro2** [goatpig/BitcoinArmory#512]
Hi, updatedto armory 96.4, still no joy
[armorylog_20180710_1635.txt](https://github.com/goatpig/BitcoinArmory/files/2181062/armorylog_20180710_1635.txt)

**Comment by goatpig** [comment]
You now need to rebuild your armory db from scratch.

**Comment by russiacro2** [comment]
Ok, thank you, anything else I will need to do?
