### ISSUE TITLE
can't send bitcoin

### ISSUE THREAD

**Issue by russiacro2** [goatpig/BitcoinArmory#513]
Have reset and rebuilt db's, still can't send
[armorylog_20180711_0352.txt](https://github.com/goatpig/BitcoinArmory/files/2182783/armorylog_20180711_0352.txt)

**Comment by russiacro2** [comment]
Hi, still can't send, here's another log
[armorylog_20180711_1612.txt](https://github.com/goatpig/BitcoinArmory/files/2185098/armorylog_20180711_1612.txt)

**Comment by goatpig** [comment]
Ask on the community forum.
