### ISSUE TITLE
Armory has no version information on MacOS

### ISSUE THREAD

**Issue by core-code** [goatpig/BitcoinArmory#517]
the 
osxbuild/Info.plist
file misses the CFBundleVersion and CFBundleShortVersionString keys

therefore selecting Armory in the Finder or QuickLook doesn't show which version it is. also, third party updater tools that keep apps up-to-date don't work.

**Comment by gusandrews** [comment]
This might be the same issue I'm having — I just tried to install and run Armory on Mac 10.14 (Mojave), and it won't open, giving me an error that says "Check with the developer to make sure Armory works with this version of macOS."

**Comment by core-code** [comment]
there is no connection between version information and what you are seeing

**Comment by gusandrews** [comment]
ok cool I guess I open another ticket for that thank you for the welcoming and verbose feedback on what my issue might be

**Comment by droark** [comment]
@gusandrews - Thanks for letting us know. Can you please open a separate issue? I don't think this is the issue that you're seeing. I have started Armory on 10.14, so it can run on Mojave.

**Comment by core-code** [comment]
closed as completed?

**Comment by goatpig** [comment]
This is an old ticket for old code. The current dev branch has no xcode nor cross compiling support yet. I have to consider a package manager as this point (if that's a thing on OSX). Versioning that's compatible with OSX only makes sense then.
