### ISSUE TITLE
Armory won't open on macOS 10.14 (Mojave)

### ISSUE THREAD

**Issue by gusandrews** [goatpig/BitcoinArmory#523]
I just installed Armory from the Mac package at https://www.bitcoinarmory.com/download/ , and it will not run once installed. When I try to open it it tells me "Check with the developer to make sure Armory works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS."

Here's the report:

Process:               Python [9585]
Path:                  /Applications/* Wallets/Armory.app/Contents/MacOS/Armory
Identifier:            com.armory.armory
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Python [9585]
User ID:               501

Date/Time:             2018-10-05 13:35:19.074 -0400
OS Version:            Mac OS X 10.14 (18A391)
Report Version:        12
Bridge OS Version:     3.0 (14Y667)
Anonymous UUID:        CDC5DDD8-A996-EE12-56D5-3186DD189053

Sleep/Wake UUID:       365CC8ED-6840-4746-8987-EFED2BCEBC84

Time Awake Since Boot: 140000 seconds
Time Since Wake:       2800 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_FRAMEWORK_PATH=/Applications/* Wallets/Armory.app/Contents/MacOS/../Dependencies:/Applications/* Wallets/Armory.app/Contents/MacOS/../Frameworks
DYLD_LIBRARY_PATH=/Applications/* Wallets/Armory.app/Contents/MacOS/../Dependencies:/Applications/* Wallets/Armory.app/Contents/MacOS/../Frameworks

Dyld Error Message:
  Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Applications/* Wallets/Armory.app/Contents/MacOS/Python
  Reason: image not found

Binary Images:
       0x100000000 -        0x100000fff +Python (???) <52CF8A42-E7D0-342D-AF33-A00A2FEDCC9E> /Applications/* Wallets/Armory.app/Contents/MacOS/Python
       0x1063a4000 -        0x1064226a7  dyld (625.13) <D6387150-2FB8-3066-868D-72E1B1C43982> /usr/lib/dyld

Model: MacBookPro14,3, BootROM MBP143.0178.B00, 4 processors, Intel Core i7, 2.9 GHz, 16 GB, SMC 2.45f0
Graphics: Intel HD Graphics 630, Intel HD Graphics 630, Built-In
Graphics: Radeon Pro 560, Radeon Pro 560, PCIe
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x173), Broadcom BCM43xx 1.0 (7.77.61.1 AirPortDriverBrcmNIC-1305.2)
Bluetooth: Version 6.0.8f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: iBridge
USB Device: Lenovo USB Receiver
USB Device: 4-Port USB 3.0 Hub
Thunderbolt Bus: MacBook Pro, Apple Inc., 37.1
Thunderbolt Bus: MacBook Pro, Apple Inc., 37.1

**Comment by droark** [comment]
Wrong site. Please use [the correct site](https://btcarmory.com/), download 0.96.4, and try again.

**Comment by gusandrews** [comment]
Wow. Kind of a security risk to continue to have multiple instances of the site up, some with outdated versions of the software. Bigger attack surface, more likelihood of user error. Maybe that's something your project should fix?

**Comment by achow101** [comment]
@gusandrews It is not something that this project can fix because bitcoinarmory.com is not owned by anyone active in this project.

**Comment by droark** [comment]
Yeah, what @achow101 said. It has been explained elsewhere, but long story short, bitcoinarmory.com is owned by a company that (AFAIK) owns the IP rights to Armory. The version under goatpig's repo (i.e., this one) is a "community fork" that is free and will always be free. But, goatpig has no say over the other site.
