### ISSUE TITLE
"tx broadcast timed out (send)"

### ISSUE THREAD

**Issue by SandroMarques46** [goatpig/BitcoinArmory#526]
Hey ,im trying to make a transaction but it doesnt let me. i've tried with diferrent fees and it always says the same  thing.

Here is my Log File:
[armorylog_20181007_1640.txt](https://github.com/goatpig/BitcoinArmory/files/2454048/armorylog_20181007_1640.txt)

**Comment by droark** [comment]
Your version of Armory is way old. Please update to the newest version (0.96.4), and follow the [correct website](https://btcarmory.com/) moving forward.
