### ISSUE TITLE
"node is offline, cannot broadcast"

### ISSUE THREAD

**Issue by sharonGA** [goatpig/BitcoinArmory#535]
I have been struggling to get Armory online ever since I managed to do so about a week ago. I finally got it online today, or so I thought. It turns out that whenever I send a transaction it says "node is offline, cannot broadcast". In the bottom right corner it says "Node offline (550727 blocks)". I have attached my log file, which shows how many times I tried to send a transaction.

Version: 0.96.4
Bitcoin Core: 0.17
Operating System: Windows 10 Home x64

[armorylog_20181119_1628.txt](https://github.com/goatpig/BitcoinArmory/files/2597289/armorylog_20181119_1628.txt)

**Comment by goatpig** [comment]
Looks like you got it fixed, closing this.
