### ISSUE TITLE
tx broadcast timed out (send)

### ISSUE THREAD

**Issue by zores62** [goatpig/BitcoinArmory#573]
So i've been trying to figure this out all day. This happened last night and reinstalled armory completely and then the wallet worked for a little bit (still couldn't send funds but I finally actually saw my money). So I just send a little bit more money to this wallet and its confirmed but I haven't received it. No big deal or anything because I have the private keys backed up so I can always get it back somehow. BUT my wallet is fully synced to the latest blocks and it says its connected and online. Whenever I tried and send btc anywhere it just says "tx broadcast timed out (send)". I've tried running in administrator mode and that doesn't do anything and i've tried rescanning everything and that doesn't do anything.  help is greatly appreciated 
[armorylog_20190214_0139.txt](https://github.com/goatpig/BitcoinArmory/files/2863803/armorylog_20190214_0139.txt)

Edit: just realized i had 0.96 installed and not 0.96.5 installed
I was using https://www.bitcoinarmory.com/ and not https://btcarmory.com/ woops ill update once all the blocks have resynced :)

**Comment by goatpig** [comment]
update to 0.96.5

**Comment by JomBb** [comment]
where do I get 0.96.5 ? I see 0.96 at the armory download site.

**Comment by goatpig** [comment]
https://github.com/goatpig/BitcoinArmory/releases
