### ISSUE TITLE
0.96.5 will not load

### ISSUE THREAD

**Issue by zores62** [goatpig/BitcoinArmory#574]
No matter what i do it just will not scan the databases or the block chain.

**Comment by goatpig** [comment]
Delete your existing databases folder: C:\Users\Corey\AppData\Roaming\Armory\databases

**Comment by zores62** [comment]
> Delete your existing databases folder: C:\Users\Corey\AppData\Roaming\Armory\databases

That didn't work It just stays on "preparing databases" and its not opening up the armorydb file like it used to with 0.96

**Comment by goatpig** [comment]
Post a fresh log

**Comment by zores62** [comment]
Hey sorry for the late reply. I saw ur message and couldnt upload the dblog at first bc it was too large but i made a mega account and uploaded it.

https://mega.nz/#!GjolXYqT!Mnc2bTZnMgBP7sME7NBbYWn9HzlrK9foJOZBbWoco5o

**Comment by goatpig** [comment]
Well that's an issue. This log is too big, it is most likely choking the DB. Delete it and post a fresh log, as directed previously.

**Comment by zores62** [comment]
[dbLog.txt](https://github.com/goatpig/BitcoinArmory/files/2872424/dbLog.txt)

**Comment by goatpig** [comment]
Start BitcoinQt first then Armory.

**Comment by zores62** [comment]
Ok so i got the wallet open and running but now i can't send transactions "the rpc interface of your node is disabled therefore armory cannot use it to gather information"

**Comment by goatpig** [comment]
This isn't related to sending transactions, although having the RPC setup makes the experience smoother overall.

Create a thread here, posting your logs for further help:

https://bitcointalk.org/index.php?board=97.0

**Comment by zores62** [comment]
Um, no idea what i did but i restarted my wallet and it now is working fully. I was able to send the TX without an issue. Thanks for all your help I appreciate it :)
