### ISSUE TITLE
Consider doing flatpak releases

### ISSUE THREAD

**Issue by orium** [goatpig/BitcoinArmory#576]
Currently installing armory in most distributions is not trivial.  For instance, in Arch Linux, you can either build it yourself and having to deal with build and runtime dependencies (which sometimes break on system update) or use the AUR package which implies trusting all of those packages in the dependency tree.

A more convenient and secure solution would be to package armory with flatpak.

**Comment by orium** [comment]
I gave this one a go, but got stuck because there is no flatpak runtime to run qt4 apps.  When armory switches to qt5 this should be doable.

**Comment by goatpig** [comment]
That's WIP. Currently working on moving from SWIG to cppyy. This is to facilitate the move from Python2 to Python3. Then I have contributors line up help migrate from pyqt4 to PySide.
