### ISSUE TITLE
Running ./configure throws "missing QtCore library, make sure libqtcore4 and libqt4-dev are installed" because of missing pkg-config

### ISSUE THREAD

**Issue by stevenengland** [goatpig/BitcoinArmory#581]
System: Lubuntu 18.04 minimal installation but with all dependencies listed in official build guide
```
sudo apt-get install git-core build-essential pyqt4-dev-tools swig libqtcore4 libqt4-dev python-qt4 python-dev python-twisted python-psutil automake autotools-dev libtool
```
When running ./configure following error is thrown:
```
missing QtCore library, make sure libqtcore4 and libqt4-dev are installed
```
Looking at the source I wanted to evaluate the commands that lead to this specific error and I found that I needed to (re-)install pkg-config via 
```
apt install pkg-config
```
Maybe you can add a pre-check for this?

**Comment by droark** [comment]
Hi. Thanks for the report. I'll add a check for it.
