### ISSUE TITLE
Running under Arch leads to sip-probs

### ISSUE THREAD

**Issue by vanbreukelingen** [goatpig/BitcoinArmory#584]
Heya!

What's this like?

```
==> Finished making: armory-git v0.96.5.r0.g1d02a664-1 (Tue Apr  2 09:39:38 2019)
==> Installing package armory-git with pacman -U...
Identified face as miranda
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) armory-git-v0.96.5.r0.g1d02a664-1

Total Installed Size:  36.85 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                 [#######################################################] 100%
(1/1) checking package integrity                                                               [#######################################################] 100%
(1/1) loading package files                                                                    [#######################################################] 100%
(1/1) checking for file conflicts                                                              [#######################################################] 100%
(1/1) checking available disk space                                                            [#######################################################] 100%
:: Processing package changes...
(1/1) installing armory-git                                                                    [#######################################################] 100%
Optional dependencies for armory-git
    bitcoin-daemon: Communicate with the Bitcoin network [installed]
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Updating the desktop file MIME type cache...
[miranda@arch armory-git]$ armory      
Traceback (most recent call last):
  File "/opt/armory-git/ArmoryQt.py", line 36, in <module>
    from PyQt4.QtCore import *
ImportError: No module named sip
```

The package sip is installed!

Any suggestions?

Miranda

**Comment by droark** [comment]
Hi. Thanks for the heads up. Can you explain how you installed sip, and check which version you installed? I don't run Arch, so I'm having to troubleshoot in the dark.

**Comment by vanbreukelingen** [comment]
Ok, _uname -a_

`Linux arch 5.0.5-zen1-1-zen #1 ZEN SMP PREEMPT Wed Mar 27 17:50:38 UTC 2019 x86_64 GNU/Linux
`

Armory's been installed through the AUR port (armory-git) in the version _0.96.5-1_, having had troubles with checksum and integrity so I had to do the --skipchesum flag  to install it via makepkg -i from the /tmp folder manually, but i also tried package armory-bin that gave the same result. The sip package was on the repositories and has been automatically installed after resolving dependencies and before git clone of course.

**Comment by goatpig** [comment]
I dont understand the need for sip in the first place. It's a package developed by the PyQt maintainers to generate bindinds for the native C++ Qt code over to Python. It shouldn't be necessary at all with an already compiled or existing install of PyQt4. 

I'd see with whoever generated this Armory package (we don't officially support arch) why sip is listed as a dependency.

**Comment by vanbreukelingen** [comment]
Yup, got it! Have to build the .tar.gz package "python2-sip-pyqt4" and install it, armory works now perfectly!
