### ISSUE TITLE
TX Broadcast

### ISSUE THREAD

**Issue by Bitlove22** [goatpig/BitcoinArmory#585]

**Comment by Bitlove22** [comment]
[armorylog_20190423_1007.txt](https://github.com/goatpig/BitcoinArmory/files/3108517/armorylog_20190423_1007.txt)

Hello there, cannot send Bitcoin with the error: TX Broadcast timed out (send). Please help, log attached.

**Comment by goatpig** [comment]
Update, you're using an old version.

**Comment by Bitlove22** [comment]
Hello goatpig thank you for your response, sorry i'm new to this. How to upgrade? what version should I used? help please

**Comment by Bitlove22** [comment]
Can you please send the link sir?

**Comment by goatpig** [comment]
https://github.com/goatpig/BitcoinArmory/releases
