### ISSUE TITLE
Transactions Frozen - Deleted mempool.dat and the zeroconf files... still Frozen

### ISSUE THREAD

**Issue by rmalisos** [goatpig/BitcoinArmory#589]
I have Armory version 0.96win64. I installed bitcoin core and it says Armory is Connected.
I see my 2 wallets and the amounts in them (all is correct).  I even see my old transactions.
Now when I try to send it keeps giving me timeout errors.

I've uninstalled/reinstalled 3 separate times. I tried it on a different machine... I keep getting timeouts.
How am I supposed to get my bitcoins out of armory?  Thanks to anyone who can help!!

[armorylog_20190515_2005.txt](https://github.com/goatpig/BitcoinArmory/files/3185010/armorylog_20190515_2005.txt)

**Comment by rmalisos** [comment]
Try version 0.96.5 and delete mempool.dat.  Let me know if that works...

**Comment by rmalisos** [comment]
Okay, I see the transactions at the bottom but they are not hitting the blockchain... "0" confirmations.

What do I do now?  

Here is the most recent log file:

**Comment by rmalisos** [comment]
[armorylog_20190516_1254 - Log Files.txt](https://github.com/goatpig/BitcoinArmory/files/3188358/armorylog_20190516_1254.-.Log.Files.txt)

**Comment by samilamour** [comment]
> Essayez la version 0.96.5 et supprimez mempool.dat. Faites-moi savoir si cela fonctionne ...

Comment instaler la version 0.96.5
