### ISSUE TITLE
Armory does not open on macOS 10.14.6 Mojave

### ISSUE THREAD

**Issue by raspulton** [goatpig/BitcoinArmory#600]
Hi Guys, 

do you know if Armory 0.96.5 can be installed on macOS 10.14.6 ? 

I followed the steps on https://github.com/goatpig/BitcoinArmory/blob/master/README_macOS.md to verify the download file and install it, but many things didn`t work out:

- After step 1 being successful, Step 2 in the guide says: „If everything is successful, execute the following command: "brew install openssl“  
Here I get „command not found“ - What can I do about this?
<img width="901" alt="Screenshot 2019-09-13_3" src="https://user-images.githubusercontent.com/54560585/64846978-83dc1380-d640-11e9-8413-495d3d8d3cbb.png">

- Continuing successfully until step 5, here it says „Verify the SHA-256 hash of the macOS build.“  The only feedback I get here is a square bracket open to the left side, but no confirmation.

- At step 6 „Verify that the SHA-256 hash list was actually signed by goatpig.“  I receive the message „No such file or directory“ and in the second row „verify signature failed: No such file or directory“
<img width="1108" alt="Screenshot 2019-09-13_4" src="https://user-images.githubusercontent.com/54560585/64846995-8a6a8b00-d640-11e9-8515-108da589d1a0.png">

- Next thing I did was using OpenPGP to verify armory_0.96.5_osx.tar.gz by using the „Verify Signature of File“ option. This gave me the message: „Verification FAILED:No Signatures found.“
<img width="1153" alt="Screenshot 2019-09-13_1" src="https://user-images.githubusercontent.com/54560585/64847023-9a826a80-d640-11e9-81be-d25f6be0dce3.png">

- Last thing I did: Install it anyways. After running, it immediately displayed a huge error message saying: „Armory cannot be opened because of a problem. Check with the developer to make sure armory works with this version of macOS. You may need to reinstall the application“  etc. 
<img width="952" alt="Screenshot 2019-09-13_2" src="https://user-images.githubusercontent.com/54560585/64847032-a110e200-d640-11e9-8c89-a2d267e06c0c.png">

Is there anything I can do to make the latest version of Armory run on a current macOS 10.14.6?

Thank you guys in advance!

**Comment by droark** [comment]
Hi. It looks like you didn't use all the lines in Step 1. Please confirm that every line is correct first. If you can run `brew` by itself, you've successfully installed it.

**Comment by whisperjungle** [comment]
Hi all, I've also run into trouble with this process.
Attempting install Armory .96.5
OS 10.13.6
"brew install openssl" just brings up error :

Error: openssl@1.1: no bottle available!

it also warns about the version of OS being old.

Not sure what to do, have tried Mac Ports, which also fails. I'd rather do it this official way via Homebrew.

Any help gratefully received.
