### ISSUE TITLE
Armory error: 'tx broadcast timed out (get)'

### ISSUE THREAD

**Issue by rogerrabbit29** [goatpig/BitcoinArmory#604]
having problems sending bitcoin. keep getting "tx broadcast timed out (get)"

i have updated armory and bitcoin core without any luck.

any ideas? log attached.

[armorylog_20191026_2024.txt](https://github.com/goatpig/BitcoinArmory/files/3775493/armorylog_20191026_2024.txt)

**Comment by goatpig** [comment]
Update

**Comment by rogerrabbit29** [comment]
i have updated both armory and bitcoin core and it still shows the same error.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by goatpig** [comment]
The log would be vastly different from 0.96 to 0.96.5. Post it.
