### ISSUE TITLE
Cannot send Bitcoins from Amory.

### ISSUE THREAD

**Issue by bdirkpitt** [goatpig/BitcoinArmory#606]
[armorylog_20191122_1123.txt](https://github.com/goatpig/BitcoinArmory/files/3881089/armorylog_20191122_1123.txt)
See attached log file per your instructions

**Comment by goatpig** [comment]
You're using an outdated version. Grab the newest release, delete your db folder (C:\Users\bgillispie\AppData\Roaming\Armory\databases) and try again.

https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.5
