### ISSUE TITLE
Problem launching Armorydb

### ISSUE THREAD

**Issue by austrianminded** [goatpig/BitcoinArmory#608]
When armorydb is launched armorydb and python become zombie processes.

**Comment by austrianminded** [comment]
I started the app (Armory a bitcoin wallet) from the cli with the 
following messages:

(ERROR) ArmoryUtils.py:3735 - Unsupported language  specified. 
Defaulting to English (en)
/usr/lib/armory/armoryengine/Transaction.py:3126: SyntaxWarning:
import 
* only allowed at module level
   def PyCreateAndSignTx_old(srcTxOuts, dstAddrsVals):

On Linux Mint 19.1, bitcoind 18, Armory 0.96.5  gcc7.2

**Comment by droark** [comment]
How exactly did you start the binary? What were the command line options?

**Comment by austrianminded** [comment]
Usually I just use the Linux Mint menu and click the icon for Armory.  However sometimes I use the terminal and just launch armory by entering "armory".  In the past, both options have successfully launched Armory.  I don't know any options for the command line.
Thanks,

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by austrianminded** [comment]
Using Linux Mint's system monitor, after attempting to launch Armory, I noted that Python2 is also zombied (along with 3 additional python2 instances) appears to be the problem.  Perhaps an update of Python2 has caused this problem?
Thanks

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
