### ISSUE TITLE
tx broadcast timed out (get)

### ISSUE THREAD

**Issue by rogerrabbit29** [goatpig/BitcoinArmory#622]
Getting error tx broadcast timed out (get) when trying to send bitcoin. Any idea what I can do for this transaction to go through?
[armorylog_20200201_1426.txt](https://github.com/goatpig/BitcoinArmory/files/4143311/armorylog_20200201_1426.txt)

**Comment by goatpig** [comment]
This log file looks busted, possibly infected, closing this issue. In the remote possibility that you are in need of help, try updating to 0.96.5
