### ISSUE TITLE
Replace openssl 1.0 with openssl 1.1 on macOS build

### ISSUE THREAD

**Issue by n370** [goatpig/BitcoinArmory#639]
The macOS client crashes immediately when initialized if the installed openssl version isn't 1.0.

Recently brew openssl default version was changed and `brew install openssl` will install version 1.1. It can be worked around so that version 1.0.x is installed but it is not straightforward and may break other binaries depending on version 1.1.

**Comment by whisperjungle** [comment]
Hi there - do you think this is why the problems I'm having in issue 653?

https://github.com/goatpig/BitcoinArmory/issues/653

any help appreciated!
WN

**Comment by n370** [comment]
> Hi there - do you think this is why the problems I'm having in issue 653?
> 
> 
> 
> https://github.com/goatpig/BitcoinArmory/issues/653
> 
> 
> 
> any help appreciated!
> 
> WN

yeah, I think you got the same issue.
