### ISSUE TITLE
Armory Send BTC Issues: TX Broadcast Timeout (sent)

### ISSUE THREAD

**Issue by gregzaf** [goatpig/BitcoinArmory#640]
Hi, 

I"m having issues sending BTC from my Armory Wallet. 
Please send me any instructions that can resolve the problem. 

See attachment

Thanks!
[armorylog_20200718_1639.txt](https://github.com/goatpig/BitcoinArmory/files/4941747/armorylog_20200718_1639.txt)

Greg Zaf

**Comment by JomBb** [comment]
How do you open an issue? got kinda the same thing happening. And got a pastebin of my text.

**Comment by goatpig** [comment]
Don't necro, use the forums for trouble shooting. The github issue page is for technical stuff.

https://bitcointalk.org/index.php?board=97.0

**Comment by JomBb** [comment]
What's necro? I figured out how to solve my problem reading what others did. Thanks for the release info.

Sent from AT&T Yahoo Mail on Android 
 
  On Mon, Dec 7, 2020 at 4:40 AM, goatpig<notifications@github.com> wrote:   


Closed #640.
