### ISSUE TITLE
Dependency issues when running configure during build process

### ISSUE THREAD

**Issue by CodeCracker-oss** [goatpig/BitcoinArmory#650]
Hello,

When I started performing the compiltaion, after reviewing the readme I already had most packages, the one I didn't (python-dev) installed from official repo no problem. The other 3, python-psutil, python-twisted & pyqt4-dev-tools were not found in official apt repo. I've managed to install python-psutil from ubuntus webpage, the build for ubuntu xenial (version 3.4.2 of python-psutil), however pyqt4-dev-tools is the missing package found during configure and installing that resorts in a bunch of dependencies needed for it, that are not found in repo.  When adding the whole official repo, where those packages are, then it resorts in package conflicts, unheld broken packages. I don't really want to have to track down all packages, since there are a lot just to get it installed, as it would also be harder to cleanup aftterward, and may just restort in more errors down the line.

How would I get these packages installed?

some like psutil installed via pip dont seem to work, as its just not detected when running configure even though its part of my PATH.

I'm using Kubuntu 20.10 groovy, x64 (amd64)

**Comment by goatpig** [comment]
Ubuntu 20 dropped python2 support. I'm working on the py3 migration in the dev branch.

**Comment by yurivict** [comment]
The FreeBSD port ```finance/bitcoin-armory``` has been removed on ```2019-03-16``` because ```Qt4 has been EOL since december 2015```.

I can reinstate it once it would be based on Qt5 and Py3.

**Comment by goatpig** [comment]
Will you know
