### ISSUE TITLE
BitcoinArmory will not run OS 11.1 Big Sur

### ISSUE THREAD

**Issue by whisperjungle** [goatpig/BitcoinArmory#653]
Hi anyone who can help!

Downloaded 
armory_0.96.5_osx.tar.gz from 
https://btcarmory.com/0.96.5-release/
Have Homebrew running nicely with openssl with caveats:

A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.1i: 8,067 files, 18.5MB
<img width="1141" alt="Screen Shot 2021-01-05 at 5 08 52 pm" src="https://user-images.githubusercontent.com/76931983/103612595-e9ac8700-4f78-11eb-972f-5d361ec008f6.png">

Armory is in Applications folder
launching brings up errors
Process:               Python [12277]
Path:                  /Applications/Armory.app/Contents/MacOS/Armory
Identifier:            com.armory.armory
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Python [12277]
User ID:               501

Date/Time:             2021-01-05 17:10:55.060 +1100
OS Version:            macOS 11.1 (20C69)
Report Version:        12
Anonymous UUID:        B8B0EE68-9449-E22A-FF31-FDA9E80A2178

Time Awake Since Boot: 22000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_FRAMEWORK_PATH=/Applications/Armory.app/Contents/MacOS/../Dependencies:/Applications/Armory.app/Contents/MacOS/../Frameworks
DYLD_LIBRARY_PATH=/Applications/Armory.app/Contents/MacOS/../Dependencies:/Applications/Armory.app/Contents/MacOS/../Frameworks

Dyld Error Message:
  dyld: Using shared cache: 467A83CB-BA86-3F07-B652-B9256C74080A
Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Applications/Armory.app/Contents/MacOS/Python
  Reason: image not found

Binary Images:
       0x104f0f000 -        0x104f0ffff +Python (0) <323F5F65-13A0-3067-9591-6432083EE72E> /Applications/Armory.app/Contents/MacOS/Python
       0x10c4fc000 -        0x10c597fff  dyld (832.7.1) <DEA51514-B4E8-3368-979B-89D0F8397ABC> /usr/lib/dyld

Again thankyou very much in advance for assistance!

**Comment by goatpig** [comment]
Python2 and Qt4 are a mess, barely supported on newer MacOS. You'll have to wait for the next release for those systems to be supported. For now I suggest you run Armory in a Ubuntu VM (19 and older).

**Comment by whisperjungle** [comment]
Thanks so much mate - would I use GCC 4.9 or 7.2 if I was going to do the virtual machine route?
I guess the question on everyone's lips is if there is a scheduled next release and if so when?
many thanks again

**Comment by goatpig** [comment]
If you're using a VM, gcc7.2 builds will do. 4.9 builds are for really old machines.

> I guess the question on everyone's lips is if there is a scheduled next release and if so when?

As soon as the batch of changes I have locally are stable, I'll push to the repo and look to start a testing phase.

**Comment by whisperjungle** [comment]
Awesome!
I can't get it to run on ubuntu 18.04.5 on virtual box tbh, so I'll just wait for the update. 
many thanks
WJ

**Comment by IrPgFKS0** [comment]
Any update on when this will be released?

**Comment by goatpig** [comment]
> update on when the update 
Update-ception

Still WIP
