### ISSUE TITLE
Can't see privbase58 "used' key

### ISSUE THREAD

**Issue by easdale** [goatpig/BitcoinArmory#655]
I'm trying to get my kitchen off armoury and exported the keyless and i was told i should find the used private key to then use this to move my bitcoin to an exchange but every line say "Unused" there are none that are used for my wallet.

Hoe can that be and how can i find my private key?

**Comment by HardCorePawn** [comment]
Is your Bitcoin Core fully synced and Armory is connected and was able to build/scan the databases OK? ie. Do you see all your transaction history in Armory?

If not, it will think that all your private keys are "unused", as it has no record of them being used in transactions!

So, in that case, just import all the keys that you see into another wallet, that should show your Bitcoins.
