### ISSUE TITLE
tx broadcast timed out

### ISSUE THREAD

**Issue by Shadow-Dog** [goatpig/BitcoinArmory#658]
I am able to receive but unable to transmit:

Version 0.96-beta-a3d01aa722
Edition	Windows 10 Pro
Version	20H2
Installed on	‎12/‎26/‎2020
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0

Logs uploaded
[armorylog_20210203_1546.txt](https://github.com/goatpig/BitcoinArmory/files/5921370/armorylog_20210203_1546.txt)

**Comment by vanastassiou** [comment]
I've noticed I almost always get timeout error messages (`Failure message: tx broadcast timed out (get)`) in Armory as well, but when I check the blockchain.com page for my transaction hash, the transaction does appear and eventually confirms (most of the time).

@Shadow-Dog from your logfile, I got your `TxHash` value and appended it to `https://www.blockchain.com/btc/tx/`, and [it looks like it confirmed](https://www.blockchain.com/btc/tx/77b15f2772e15d0879f08249bbf8eb953295a5f7ade84d91495d35f0d9c52f73).

It would be good to change the error URL in the Armory popup to use the above formatting. That would give users an easy means to check on their transaction status while investigating the reason why a timeout is immediately reported.

(I'm not a C++ dev but I'm having a look to see whether this is a problem I can help with at all.)
