### ISSUE TITLE
Tx Broadcast timed out

### ISSUE THREAD

**Issue by bitnewbie** [goatpig/BitcoinArmory#661]
Hi I am a new user. I am able to receive bitcoins to my armory wallet but cannot send them. After much tinkering I am finally able to get armory to show up as online. When I try to send I get the Tx broadcast timed out message and when I check blockchain reference site my transactions are not showing up. Fees are set to auto. I'm using armory 0.96-beta-a3d01aa722. I have tried restarting armory, restarting computer, and rebuilding database. Your help is greatly appreciated. Log file:

[armorylog_20210414_1614.txt](https://github.com/goatpig/BitcoinArmory/files/6313755/armorylog_20210414_1614.txt)

**Comment by goatpig** [comment]
Use 0.96.5: https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.5 

Clean up your DB before updating, it's not compatible with 0.96. Core's blockchain data can be left untouched but you need to start Core with -server.

If you still experience issues, ask for help on the community forum: https://bitcointalk.org/index.php?board=97.0. This is more of an issue page for devs.
