### ISSUE TITLE
error: variable has incomplete type 'union semun'

### ISSUE THREAD

**Issue by yurivict** [goatpig/BitcoinArmory#668]
```
lmdb/libraries/liblmdb/mdb.c:5157:14: error: variable has incomplete type 'union semun'
        union semun semu;
                    ^
lmdb/libraries/liblmdb/mdb.c:5157:8: note: forward declaration of 'union semun'
        union semun semu;
              ^
```

OS: FreeBSD 13

**Comment by goatpig** [comment]
I dont dev for lmdb. Try to update the code and see if it helps:

https://github.com/LMDB/lmdb/tree/mdb.master/libraries/liblmdb

**Comment by goatpig** [comment]
What compiler btw? This code builds on gcc, clang and msvc.

**Comment by yurivict** [comment]
clang-11

You have ```lmdb``` bundled. Can you remove it? The ```lmdb``` package wouldn't have such problem because it is already built.

**Comment by yurivict** [comment]
About every distro has ```lmdb``` packaged: https://repology.org/project/lmdb/versions

**Comment by goatpig** [comment]
I used to have custom changes in LMDB but eventually LMDB itself implemented those extra functionalities. I could now get rid of the bundled LMDB now indeed. I don't have time for that at the moment however. If I had time to go over the build system, there would be certain things I'd clean up prior to dealing with this specific item.

**Comment by yurivict** [comment]
I tried to copy in the latest lmdb version, but you have custom ```lmdbpp.{h,cpp}``` there that aren't compatible with it.

**Comment by yurivict** [comment]
IMO the correct course of action here is:
1. Make sure ```lmdbpp.{h,cpp}``` compile with the latest ```lmdb```
2. Submit the pull request to ```lmdb``` with ```lmdbpp.{h,cpp}```
3. Unbundle ```lmdb``

**Comment by goatpig** [comment]
There's a liblmdb++ available on my system, I could look into migrating to that this week end.

**Comment by yurivict** [comment]
Here is some lmdb++: https://sourceforge.net/projects/lmdbxx/files/
Maybe they are same.

**Comment by goatpig** [comment]
https://github.com/goatpig/BitcoinArmory/commit/ab5972b6f108de879c085f83f7e5389b22c91042

lmdb++ would result in too big a change, I don't have time to even consider that. This change uses system LMDB, but my own cpp wrapper.
