### ISSUE TITLE
BitcoinArmory not updating wallet with transaction

### ISSUE THREAD

**Issue by Kludge1** [goatpig/BitcoinArmory#67]
Running Armory 0.94.1 on Ubuntu 16.04 LTS. Incoming transaction shows on blockchain.info as confirmed 43 times, but exact same address in Armory shows 0.00 BTC balance.

**Comment by goatpig** [comment]
log files please

**Comment by Kludge1** [comment]
[armorylog_20160819_0635.txt](https://github.com/goatpig/BitcoinArmory/files/426792/armorylog_20160819_0635.txt)

**Comment by Kludge1** [comment]
Update: Funds finally populated after a rebuild and rescan of the databases. Many thanks for your time, and for continuing to support this excellent piece of software!
