### ISSUE TITLE
 Bump the master branch so the project doesn't get dismissed as obsolete

### ISSUE THREAD

**Issue by Giszmo** [goatpig/BitcoinArmory#670]
I was looking for Multi Vendor Multi Signature wallets and almost missed that

> goatpig bump version and update changelog 1d02a66 on Dec 23, 2018

on the repository's main page doesn't mean the project is obsolete. The dev branch is active and 1142 commits ahead of master.

I would suggest to maybe point to that fact with an edit of the Readme.md on master ;)

**Comment by goatpig** [comment]
Thanks for the reminder. I guess most projects develop in the master branch and simply tag releases, which isn't the case here.

**Comment by dermoth** [comment]
maybe a suggestion, make dev the default branch? or move dev to master and master to maint or stable

**Comment by goatpig** [comment]
I'll look into that after the next release, don't want to change things around here without new code to go with it.

**Comment by MCM-Mike** [comment]
Cleaning up is a good thing at the beginning of this year :smile: 
Could you keep one issue open about status updates like https://github.com/goatpig/BitcoinArmory/issues/638#issuecomment-738136505 ?  or even a more general issue, if you need help let me know I can try to come up with something.

**Comment by goatpig** [comment]
Reopened the target distro issue.

> if you need help let me know I can try to come up with something.

I could use some help with GUI development if you're willing to suffer (py3/pyside2)

**Comment by goatpig** [comment]
Made dev the default branch. Closing this.
