### ISSUE TITLE
Unable to load file when attempting to recover fragment backup

### ISSUE THREAD

**Issue by ralstonba** [goatpig/BitcoinArmory#675]
Armory Version: 0.96-beta-a3d01aa722
OS: Windows 10 Pro, Build 19044.1320

### Replication
1. Wallets -> Import or Restore Wallet
2. Fragmented Backup
3. Load Data

### Behavior Observed
- Nothing happens when clicking "Load File"
- Clicking "Type Data" correctly opens dialog to enter details manually

### Expected Behavior
- Clicking "Load File" opens Windows File Explorer dialog to select fragment file.

**Comment by goatpig** [comment]
You are using an old version, update to the 0.96.5

https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.5
