### ISSUE TITLE
Tx timeout BTC do not transfer 

### ISSUE THREAD

**Issue by kokakid** [goatpig/BitcoinArmory#680]
[armorylog_20220504_0000.txt](https://github.com/goatpig/BitcoinArmory/files/8610995/armorylog_20220504_0000.txt)
![Tx Timeout](https://user-images.githubusercontent.com/104843844/166469591-506833d6-58c4-4a48-9d34-b0e1628dbcca.png)

Please see these log files and screenshot of Timeout error .
Trying to send BTC from Armory to Ledger wallet using Segwit ( not native SegWit ).
Armory accepts the receiving address and the transaction appears to go through , but no BTC moves at either end.
This Tx timeout popup has come up before, but the transaction has still happened when going elsewhere, other than Ledger.
This is only a problem going from Armory to Ledger.
BTC moves fine from Armory to a variety of trading platforms.
Please help !!
Do you know why this might be happening, and have a solution ?
Thank you ,
kokakid.

**Comment by kokakid** [comment]
Update :
Now this problem is happening wherever I try to send BTC from Armory to anywhere !!
Please help !! 
The same error message and the blockchain .info link comes up with an error page 
What is going on ?

**Comment by goatpig** [comment]
This is a known error, you need to setup core RPC to avoid it. You can get help on the community forums: https://bitcointalk.org/index.php?board=97.0

**Comment by kokakid** [comment]
Thank you , GP.

So, is it a relatively easy fix ?

My Norton antivirus says the bitcointalk page is dangerous - do you know
why Norton would say that ?

Regards,

kokakid.

**Comment by goatpig** [comment]
> So, is it a relatively easy fix ?

Old shenanigans with how Armory interfaces with Bitcoin Core. Basically you need to create a bitcoin.conf file in Core's datadir and add server=1 in the file. This will allow Armory to talk to Core's RPC and the issue will be fixed.

> My Norton antivirus says the bitcointalk page is dangerous - do you know
why Norton would say that ?

Some libelous stance by Norton. bitcointalk.org is the birth place of the Bitcoin community, every major historical actor is still active there.

**Comment by kokakid** [comment]
Thank you, GP.

I'll go ahead and do that.

Yes, I'm not sure why Norton would say that about Bitcointalk-it looks
pretty harmless to me.

Thanks again for your help and for all the wonderful work you've done with
Armory.

Kind Regards,

Kokakid.
