### ISSUE TITLE
Impossible to start ArmoryQT when bitcoin uses different datadir and blocksdir

### ISSUE THREAD

**Issue by de-served** [goatpig/BitcoinArmory#690]
Seems like project is abandoned, but I try, maybe have some luck.
1. Bitcoin data is divided:
bitcoin-qt/cli starting parameters:
```-datadir=W:/BitcoinCore/DataDir
-blocksdir=W:/BitcoinCore/BlocksDir
-walletdir=W:/BitcoinCore/WalletDir
```
Data is really splitted.
blk*.dat and rev*.dat are in BlocksDir/blocks for main chain and in BlocksDir/chain/blocks for test chains;
blocks index, chainstate and peers/mempool/fee/anchors .dat's are in DataDir;
wallets are in WalletDir.

2. ArmoryQT starts with:
```
--datadir=W:\Armory\DataDir
--dbdir=W:\Armory\DBDir
--satoshi-datadir=W:\BitcoinCore\BlocksDir
```
and even tried (with no luck): `--blocksdir=W:\_Data_\BitcoinCore\BlocksDir`

3. In armorylog.txt I see this:
> ArmoryUtils.pyc:1294 - Satoshi BTC directory : W:\BitcoinCore\BlocksDir\regtest
> ArmoryUtils.pyc:1311 - satoshiHome     : W:\BitcoinCore\BlocksDir
> ArmoryQt.py:1891 - Setting satoshi datadir = W:\BitcoinCore\DataDir
> SDM.pyc:445 - Spawning bitcoind with command: bitcoind.exe -datadir=W:\BitcoinCore\DataDir -dbcache=2000
> ArmoryQt.py:1198 - 4 attempts to load blockchain failed. Remove mempool.bin.

4. In Process Explorer I see that Armory tries to get blk*.dat and rev*.dat in "satoshi datadir" and it is impossible to change that value - no config parameter for ArmoryQT and it is ignoring settings in bitcoin .conf settings.

PS: 5. Settings in ArmorySettings are differs with log messages in ArmoryQT log - 

> ArmoryDbdir                          | W:\Armory\\**DataDir**
> LastDirectory                        | W:\Armory\DataDir

> ArmoryUtils.pyc:1295 -    Armory home dir       : W:\Armory\DataDir
> ArmoryUtils.pyc:1309 - Named options/arguments to armoryengine.py:
> ArmoryUtils.pyc:1311 -     datadir         : W:\Armory\DataDir
> ArmoryUtils.pyc:1311 -     armoryDBDir     : W:\Armory\DBDir

**Comment by de-served** [comment]
I tried everythin you can not even imagine :|

**Comment by goatpig** [comment]
Can I see a full log, I still don't know what version of Armory you're using.

**Comment by de-served** [comment]
Almost year passed. Do you think I I keep logs for such long time? I wiped everything including Armory.
It was latest (not updated for a long time as I remember) version. If my memory is ok, it was something like 0.96.5.
I asked someone (maybe you) at btf to give instruction how to compile Armory in 2023, this someone answered that he will look later after some party/wedding/etc and after some time my topic was just deleted without any resolution.
So no, I can't give any more specific information. All is in startpost.
Too much time passed.

**Comment by goatpig** [comment]
Ok, godspeed.
