### ISSUE TITLE
Python2 is deprecated and end of life since Jan 2020

### ISSUE THREAD

**Issue by FalcoGer** [goatpig/BitcoinArmory#694]
Please port this to python 3. Modern systems don't even offer python 2 in their repositories anymore and installing python 2 by hand will just invite a whole lot of problems that most people don't want to deal with.

**Comment by goatpig** [comment]
dev branch is py3.10, but i dont have free time to progress lately T_T. There's trello page to follow up on things if you'd like:
https://trello.com/b/wJOsu12D/dev
