### ISSUE TITLE
tx broadcast timed out

### ISSUE THREAD

**Issue by HappyDayEvryDay** [goatpig/BitcoinArmory#695]
no broo noooooo broo what the fck is this tool just to recieve btc i transformed my self to stev jobs bitcoin itself dont know what i know what the hell is that tool and to send bitcoin too i need do new shits no there is limits OMGGGGGGGGGG i have 7k$ stuck in thereeee please need help i cant send btc to another wallets NEED HELP 
[armorylog_20231216_0922.txt](https://github.com/goatpig/BitcoinArmory/files/13691852/armorylog_20231216_0922.txt)

**Comment by goatpig** [comment]
The log file is only showing db related stuff. Look for armorylog.txt in your Armory datadir and post that here. Alternatively, you can copy the hex tx from this log file you posted and broadcast it from Core's RPC:
https://bitcoincore.org/en/doc/26.0.0/rpc/rawtransactions/sendrawtransaction/
