### ISSUE TITLE
TX Timed out

### ISSUE THREAD

**Issue by Randy8822** [goatpig/BitcoinArmory#696]
Tried to send to a Ledger wallet and a Coinbase wallet. 

It said the TX timed out.

I looked through the issues section, but did not find a current answer to this problem.

[armorylog_20240111_1447.txt](https://github.com/goatpig/BitcoinArmory/files/13909411/armorylog_20240111_1447.txt)

**Comment by goatpig** [comment]
You're using 0.96.

0.96.5 addresses this issue (as long as you can setup Bitcoin Core RPC correctly). Check the release page to grab the upgrade.

**Comment by Randy8822** [comment]
Thank you very much for your prompt reply.
