### ISSUE TITLE
Can't send coins

### ISSUE THREAD

**Issue by cxj30** [goatpig/BitcoinArmory#697]
When I have it set to autocalculate the fee I get a value error, when I manually override I get a time out message. I have tried using the same fee that would be autocalculated and still get a time out issue. 
[armorylog_20240411_1500.txt](https://github.com/goatpig/BitcoinArmory/files/14950283/armorylog_20240411_1500.txt)

**Comment by goatpig** [comment]
From the looks of it, you're using 0.96. Update to 0.96.5 (https://github.com/goatpig/BitcoinArmory/releases), rebuild your DB and try again.

**Comment by goatpig** [comment]
Closing this.
