### ISSUE TITLE
Will latest Bitcoin Armory run on Windows 11?

### ISSUE THREAD

**Issue by KipIngram** [goatpig/BitcoinArmory#698]
Hi.  I need to set up a new machine and get Bitcoin Armory running on it.  Would my best bet be Windows 11, or would I be better off with a Linux distribution of some flavor?  Thanks!

**Comment by goatpig** [comment]
Windows for ease of use, Linux for security. Distro target for Linux is Ubuntu but it should work out of the box for Debian based distros.
