### ISSUE TITLE
updates to this wallet? 

### ISSUE THREAD

**Issue by ghost** [goatpig/BitcoinArmory#73]
Will you guys update the wallet to work with Segwit?(NOTE: check the GPG keys so that you don't get hacked see: bitcoin.org)

PS: why don't you guys update the website & have a twitter page so that people can give feedback to you guys?

**Comment by achow101** [comment]
Yes segwit wallets are coming. We already have segwit compatibility so it 
won't break when segwit is deployed.

**Comment by briannyeko** [comment]
Nice! when will you open a twitter page(so that people can give you guys
feedback on issues regarding the armory wallet)?

**Comment by achow101** [comment]
Right now we have the forum in bitcointalk and a website right now. Other 
stuff will come later after the software is updated.

**Comment by goatpig** [comment]
I don't really like social media. The github issue page is perfectly suited for getting developers' attention. Otherwise, you can get good help from the community by posting on the btctalk subforum.

**Comment by Nerotool** [comment]
SEND A DM TO NEROTOOL_ ON INSTAGRAM FOR HACKING
