### ISSUE TITLE
Plural strings

### ISSUE THREAD

**Issue by pryds** [goatpig/BitcoinArmory#76]
I'm not entirely sure what's going on in the following code from qtdialogs.py, but I think plural strings are not handled correctly in this case.

```
if nError > 0:
   pluralStr = 'error' if nError == 1 else 'errors'

   msg = tr("""
      Detected %(error)d error in the data you entered.
      Armory attempted to fix the errors but it is not
      always right.  Be sure to verify the "Wallet Unique ID"
      closely on the next window.""","""
      Detected %(error)d errors in the data you entered.
      Armory attempted to fix the errors but it is not
      always right.  Be sure to verify the "Wallet Unique ID"
      closely on the next window.""") % { 'error' : nError }

   QMessageBox.question(self, tr('Errors Corrected'), msg, \
      QMessageBox.Ok)
```

I'm a bit worried by the first line, which seems to use "error" if number of errors is 1, and "errors" otherwise. This won't work in a lot of languages besides English, of course.

But then again, the pluralStr variable doesn't seem to be used later on, so it might be leftovers from before?

Anyway, the code also seems to send two strings for translation (a singular and a plural version). However, Transifex doesn't seem to recognize this, and it shows only the singular version. Normally, in Transifex, when you translate a proper plural string, you are presented with tab-like options, one per plural form that your languages has (English has two, sing and plur, some have more, some have less). The plural string also doesn't appear as its own string.

**Example of plural string in Transifex:**
![Example of plural string in Transifex](http://i.imgur.com/3INqVLU.png)

**How this string looks for me:**
![How this string looks for me](http://i.imgur.com/dz4Vk76.png)

**Comment by achow101** [comment]
This can be closed. Fixed in #89
